//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/modules/encryption/entity/EncryptedBox.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreModulesEncryptionEntityEncryptedBox")
#ifdef RESTRICT_ImDiyalogCoreModulesEncryptionEntityEncryptedBox
#define INCLUDE_ALL_ImDiyalogCoreModulesEncryptionEntityEncryptedBox 0
#else
#define INCLUDE_ALL_ImDiyalogCoreModulesEncryptionEntityEncryptedBox 1
#endif
#undef RESTRICT_ImDiyalogCoreModulesEncryptionEntityEncryptedBox

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImDiyalogCoreModulesEncryptionEntityEncryptedBox_) && (INCLUDE_ALL_ImDiyalogCoreModulesEncryptionEntityEncryptedBox || defined(INCLUDE_ImDiyalogCoreModulesEncryptionEntityEncryptedBox))
#define ImDiyalogCoreModulesEncryptionEntityEncryptedBox_

@class IOSByteArray;
@class IOSObjectArray;

@interface ImDiyalogCoreModulesEncryptionEntityEncryptedBox : NSObject

#pragma mark Public

- (instancetype)initWithImDiyalogCoreModulesEncryptionEntityEncryptedBoxKeyArray:(IOSObjectArray *)keys
                                                                   withByteArray:(IOSByteArray *)encryptedPackage;

- (IOSByteArray *)getEncryptedPackage;

- (IOSObjectArray *)getKeys;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogCoreModulesEncryptionEntityEncryptedBox)

FOUNDATION_EXPORT void ImDiyalogCoreModulesEncryptionEntityEncryptedBox_initWithImDiyalogCoreModulesEncryptionEntityEncryptedBoxKeyArray_withByteArray_(ImDiyalogCoreModulesEncryptionEntityEncryptedBox *self, IOSObjectArray *keys, IOSByteArray *encryptedPackage);

FOUNDATION_EXPORT ImDiyalogCoreModulesEncryptionEntityEncryptedBox *new_ImDiyalogCoreModulesEncryptionEntityEncryptedBox_initWithImDiyalogCoreModulesEncryptionEntityEncryptedBoxKeyArray_withByteArray_(IOSObjectArray *keys, IOSByteArray *encryptedPackage) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogCoreModulesEncryptionEntityEncryptedBox *create_ImDiyalogCoreModulesEncryptionEntityEncryptedBox_initWithImDiyalogCoreModulesEncryptionEntityEncryptedBoxKeyArray_withByteArray_(IOSObjectArray *keys, IOSByteArray *encryptedPackage);

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogCoreModulesEncryptionEntityEncryptedBox)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreModulesEncryptionEntityEncryptedBox")
