//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/modules/encryption/entity/EncryptedBoxKey.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreModulesEncryptionEntityEncryptedBoxKey")
#ifdef RESTRICT_ImDiyalogCoreModulesEncryptionEntityEncryptedBoxKey
#define INCLUDE_ALL_ImDiyalogCoreModulesEncryptionEntityEncryptedBoxKey 0
#else
#define INCLUDE_ALL_ImDiyalogCoreModulesEncryptionEntityEncryptedBoxKey 1
#endif
#undef RESTRICT_ImDiyalogCoreModulesEncryptionEntityEncryptedBoxKey

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImDiyalogCoreModulesEncryptionEntityEncryptedBoxKey_) && (INCLUDE_ALL_ImDiyalogCoreModulesEncryptionEntityEncryptedBoxKey || defined(INCLUDE_ImDiyalogCoreModulesEncryptionEntityEncryptedBoxKey))
#define ImDiyalogCoreModulesEncryptionEntityEncryptedBoxKey_

@class IOSByteArray;
@protocol ARPredicate;

@interface ImDiyalogCoreModulesEncryptionEntityEncryptedBoxKey : NSObject

#pragma mark Public

- (instancetype)initWithInt:(jint)uid
                    withInt:(jint)keyGroupId
               withNSString:(NSString *)keyAlg
              withByteArray:(IOSByteArray *)encryptedKey;

+ (id<ARPredicate>)FILTERWithInt:(jint)myUid
                         withInt:(jint)keyGroupId;

- (IOSByteArray *)getEncryptedKey;

- (NSString *)getKeyAlg;

- (jint)getKeyGroupId;

- (jint)getUid;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogCoreModulesEncryptionEntityEncryptedBoxKey)

FOUNDATION_EXPORT id<ARPredicate> ImDiyalogCoreModulesEncryptionEntityEncryptedBoxKey_FILTERWithInt_withInt_(jint myUid, jint keyGroupId);

FOUNDATION_EXPORT void ImDiyalogCoreModulesEncryptionEntityEncryptedBoxKey_initWithInt_withInt_withNSString_withByteArray_(ImDiyalogCoreModulesEncryptionEntityEncryptedBoxKey *self, jint uid, jint keyGroupId, NSString *keyAlg, IOSByteArray *encryptedKey);

FOUNDATION_EXPORT ImDiyalogCoreModulesEncryptionEntityEncryptedBoxKey *new_ImDiyalogCoreModulesEncryptionEntityEncryptedBoxKey_initWithInt_withInt_withNSString_withByteArray_(jint uid, jint keyGroupId, NSString *keyAlg, IOSByteArray *encryptedKey) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogCoreModulesEncryptionEntityEncryptedBoxKey *create_ImDiyalogCoreModulesEncryptionEntityEncryptedBoxKey_initWithInt_withInt_withNSString_withByteArray_(jint uid, jint keyGroupId, NSString *keyAlg, IOSByteArray *encryptedKey);

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogCoreModulesEncryptionEntityEncryptedBoxKey)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreModulesEncryptionEntityEncryptedBoxKey")
