//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/runtime/runtime-shared/src/main/java/im/diyalog/runtime/actors/Actor.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogRuntimeActorsActor")
#ifdef RESTRICT_ImDiyalogRuntimeActorsActor
#define INCLUDE_ALL_ImDiyalogRuntimeActorsActor 0
#else
#define INCLUDE_ALL_ImDiyalogRuntimeActorsActor 1
#endif
#undef RESTRICT_ImDiyalogRuntimeActorsActor

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARActor_) && (INCLUDE_ALL_ImDiyalogRuntimeActorsActor || defined(INCLUDE_ARActor))
#define ARActor_

@class ARActorContext;
@class ARActorRef;
@class ARActorSystem;
@class ARPromise;
@class ImDiyalogRuntimeActorsDispatchMailbox;
@class JavaLangException;
@protocol ARActorCancellable;
@protocol ARReceiver;
@protocol ARSimpleDispatcher;
@protocol ImDiyalogRuntimeActorsAskAskCallback;
@protocol ImDiyalogRuntimeActorsAskAskMessage;

/*!
 @brief Actor object
 */
@interface ARActor : NSObject

#pragma mark Public

- (instancetype)init;

- (ARPromise *)askWithARActorRef:(ARActorRef *)dest
withImDiyalogRuntimeActorsAskAskMessage:(id<ImDiyalogRuntimeActorsAskAskMessage>)msg;

- (void)askWithARActorRef:(ARActorRef *)dest
                   withId:(id)message;

- (void)askWithARActorRef:(ARActorRef *)dest
                   withId:(id)message
withImDiyalogRuntimeActorsAskAskCallback:(id<ImDiyalogRuntimeActorsAskAskCallback>)callback;

- (void)becomeWithARReceiver:(id<ARReceiver>)receiver;

/*!
 @brief Dropping of message
 @param message message for dropping
 */
- (void)dropWithId:(id)message;

- (void)forwardWithARActorRef:(ARActorRef *)dest;

/*!
 @brief <p>INTERNAL API</p>
 */
- (id<ARSimpleDispatcher>)getDispatcher;

/*!
 @brief Actor mailbox
 @return mailbox
 */
- (ImDiyalogRuntimeActorsDispatchMailbox *)getMailbox;

- (void)haltWithNSString:(NSString *)message;

- (void)haltWithNSString:(NSString *)message
   withJavaLangException:(JavaLangException *)e;

/*!
 @brief <p>INTERNAL API</p>
 Handling of a message in Actor
 @param message message
 */
- (void)handleMessageWithId:(id)message
             withARActorRef:(ARActorRef *)sender;

/*!
 @brief <p>INTERNAL API</p>
 Initialization of actor
 @param path    path of actor
 @param context context of actor
 @param mailbox mailbox of actor
 */
- (void)initActorWithNSString:(NSString *)path
           withARActorContext:(ARActorContext *)context
withImDiyalogRuntimeActorsDispatchMailbox:(ImDiyalogRuntimeActorsDispatchMailbox *)mailbox OBJC_METHOD_FAMILY_NONE;

/*!
 @brief Receiving of message
 @param message message
 */
- (void)onReceiveWithId:(id)message;

/*!
 @brief Called after actor shutdown
 */
- (void)postStop;

/*!
 @brief Called before first message receiving
 */
- (void)preStart;

/*!
 @brief Reply message to sender of last message
 @param message reply message
 */
- (void)replyWithId:(id)message;

- (id<ARActorCancellable>)scheduleWithId:(id)obj
                                withLong:(jlong)delay;

/*!
 @brief Self actor reference
 @return self reference
 */
- (ARActorRef *)self__;

/*!
 @brief Sender of last received message
 @return sender's ActorRef
 */
- (ARActorRef *)sender;

- (void)stash;

- (void)stashWithInt:(jint)index;

/*!
 @brief Actor System
 @return Actor System
 */
- (ARActorSystem *)system;

- (void)unbecome;

- (void)unstashAll;

- (void)unstashAllWithInt:(jint)index;

#pragma mark Protected

/*!
 @brief Actor path
 @return path
 */
- (NSString *)getPath;

@end

J2OBJC_EMPTY_STATIC_INIT(ARActor)

FOUNDATION_EXPORT void ARActor_init(ARActor *self);

FOUNDATION_EXPORT ARActor *new_ARActor_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARActor *create_ARActor_init();

J2OBJC_TYPE_LITERAL_HEADER(ARActor)

@compatibility_alias ImDiyalogRuntimeActorsActor ARActor;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogRuntimeActorsActor")
