//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/runtime/runtime-shared/src/main/java/im/diyalog/runtime/actors/ActorContext.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogRuntimeActorsActorContext")
#ifdef RESTRICT_ImDiyalogRuntimeActorsActorContext
#define INCLUDE_ALL_ImDiyalogRuntimeActorsActorContext 0
#else
#define INCLUDE_ALL_ImDiyalogRuntimeActorsActorContext 1
#endif
#undef RESTRICT_ImDiyalogRuntimeActorsActorContext

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARActorContext_) && (INCLUDE_ALL_ImDiyalogRuntimeActorsActorContext || defined(INCLUDE_ARActorContext))
#define ARActorContext_

@class ARActorRef;
@class ARActorScope;
@class ARActorSystem;

/*!
 @brief <p>INTERNAL API</p>
 Context of actor
 */
@interface ARActorContext : NSObject

#pragma mark Public

/*!
 @brief <p>INTERNAL API</p>
 Creating of actor context
 @param scope actor scope
 */
- (instancetype)initWithARActorScope:(ARActorScope *)scope;

/*!
 @brief Actor Reference
 @return reference
 */
- (ARActorRef *)getSelf;

/*!
 @brief Actor system
 @return Actor system
 */
- (ARActorSystem *)getSystem;

- (id)message;

/*!
 @brief Sender of last received message
 @return sender's ActorRef
 */
- (ARActorRef *)sender;

- (void)setMessageWithId:(id)message;

/*!
 @brief Setting sender
 @param ref sender's ActorRef
 */
- (void)setSenderWithARActorRef:(ARActorRef *)ref;

@end

J2OBJC_EMPTY_STATIC_INIT(ARActorContext)

FOUNDATION_EXPORT void ARActorContext_initWithARActorScope_(ARActorContext *self, ARActorScope *scope);

FOUNDATION_EXPORT ARActorContext *new_ARActorContext_initWithARActorScope_(ARActorScope *scope) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARActorContext *create_ARActorContext_initWithARActorScope_(ARActorScope *scope);

J2OBJC_TYPE_LITERAL_HEADER(ARActorContext)

@compatibility_alias ImDiyalogRuntimeActorsActorContext ARActorContext;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogRuntimeActorsActorContext")
