//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/runtime/runtime-shared/src/main/java/im/diyalog/runtime/promise/Tuple4.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogRuntimePromiseTuple4")
#ifdef RESTRICT_ImDiyalogRuntimePromiseTuple4
#define INCLUDE_ALL_ImDiyalogRuntimePromiseTuple4 0
#else
#define INCLUDE_ALL_ImDiyalogRuntimePromiseTuple4 1
#endif
#undef RESTRICT_ImDiyalogRuntimePromiseTuple4

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARTuple4_) && (INCLUDE_ALL_ImDiyalogRuntimePromiseTuple4 || defined(INCLUDE_ARTuple4))
#define ARTuple4_

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARTuple4 : NSObject
@property (readonly, nonatomic, getter=getT1) id t1;
@property (readonly, nonatomic, getter=getT2) id t2;
@property (readonly, nonatomic, getter=getT3) id t3;
@property (readonly, nonatomic, getter=getT4) id t4;

#pragma mark Public

- (instancetype)initWithId:(id __nullable)t1
                    withId:(id __nullable)t2
                    withId:(id __nullable)t3
                    withId:(id __nullable)t4;

- (id __nullable)getT1;

- (id __nullable)getT2;

- (id __nullable)getT3;

- (id __nullable)getT4;

@end

J2OBJC_EMPTY_STATIC_INIT(ARTuple4)

FOUNDATION_EXPORT void ARTuple4_initWithId_withId_withId_withId_(ARTuple4 *self, id t1, id t2, id t3, id t4);

FOUNDATION_EXPORT ARTuple4 *new_ARTuple4_initWithId_withId_withId_withId_(id t1, id t2, id t3, id t4) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARTuple4 *create_ARTuple4_initWithId_withId_withId_withId_(id t1, id t2, id t3, id t4);

J2OBJC_TYPE_LITERAL_HEADER(ARTuple4)

@compatibility_alias ImDiyalogRuntimePromiseTuple4 ARTuple4;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogRuntimePromiseTuple4")
