//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/runtime/runtime-shared/src/main/java/im/diyalog/runtime/promise/Tuple3.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogRuntimePromiseTuple3")
#ifdef RESTRICT_ImDiyalogRuntimePromiseTuple3
#define INCLUDE_ALL_ImDiyalogRuntimePromiseTuple3 0
#else
#define INCLUDE_ALL_ImDiyalogRuntimePromiseTuple3 1
#endif
#undef RESTRICT_ImDiyalogRuntimePromiseTuple3

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARTuple3_) && (INCLUDE_ALL_ImDiyalogRuntimePromiseTuple3 || defined(INCLUDE_ARTuple3))
#define ARTuple3_

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARTuple3 : NSObject
@property (readonly, nonatomic, getter=getT1) id t1;
@property (readonly, nonatomic, getter=getT2) id t2;
@property (readonly, nonatomic, getter=getT3) id t3;

#pragma mark Public

- (instancetype)initWithId:(id __nullable)t1
                    withId:(id __nullable)t2
                    withId:(id __nullable)t3;

- (id __nullable)getT1;

- (id __nullable)getT2;

- (id __nullable)getT3;

@end

J2OBJC_EMPTY_STATIC_INIT(ARTuple3)

FOUNDATION_EXPORT void ARTuple3_initWithId_withId_withId_(ARTuple3 *self, id t1, id t2, id t3);

FOUNDATION_EXPORT ARTuple3 *new_ARTuple3_initWithId_withId_withId_(id t1, id t2, id t3) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARTuple3 *create_ARTuple3_initWithId_withId_withId_(id t1, id t2, id t3);

J2OBJC_TYPE_LITERAL_HEADER(ARTuple3)

@compatibility_alias ImDiyalogRuntimePromiseTuple3 ARTuple3;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogRuntimePromiseTuple3")
