//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/runtime/runtime-shared/src/main/java/com/google/j2objc/annotations/Weak.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ComGoogleJ2objcAnnotationsWeak")
#ifdef RESTRICT_ComGoogleJ2objcAnnotationsWeak
#define INCLUDE_ALL_ComGoogleJ2objcAnnotationsWeak 0
#else
#define INCLUDE_ALL_ComGoogleJ2objcAnnotationsWeak 1
#endif
#undef RESTRICT_ComGoogleJ2objcAnnotationsWeak

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ComGoogleJ2objcAnnotationsWeak_) && (INCLUDE_ALL_ComGoogleJ2objcAnnotationsWeak || defined(INCLUDE_ComGoogleJ2objcAnnotationsWeak))
#define ComGoogleJ2objcAnnotationsWeak_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
@import j2objc;

/*!
 @brief Annotation that indicates a variable has a weak relationship to its owner.
 @author Tom Ball
 */
@protocol ComGoogleJ2objcAnnotationsWeak < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleJ2objcAnnotationsWeak)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleJ2objcAnnotationsWeak)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComGoogleJ2objcAnnotationsWeak")
