//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/runtime/runtime-shared/src/main/java/im/diyalog/runtime/function/Function.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogRuntimeFunctionFunction")
#ifdef RESTRICT_ImDiyalogRuntimeFunctionFunction
#define INCLUDE_ALL_ImDiyalogRuntimeFunctionFunction 0
#else
#define INCLUDE_ALL_ImDiyalogRuntimeFunctionFunction 1
#endif
#undef RESTRICT_ImDiyalogRuntimeFunctionFunction

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARFunction_) && (INCLUDE_ALL_ImDiyalogRuntimeFunctionFunction || defined(INCLUDE_ARFunction))
#define ARFunction_

@protocol ARFunction < NSObject, JavaObject >

- (id)applyWithId:(id)t;

@end

J2OBJC_EMPTY_STATIC_INIT(ARFunction)

J2OBJC_TYPE_LITERAL_HEADER(ARFunction)

#define ImDiyalogRuntimeFunctionFunction ARFunction

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogRuntimeFunctionFunction")
