//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/events/AppVisibleChanged.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreEventsAppVisibleChanged")
#ifdef RESTRICT_ImDiyalogCoreEventsAppVisibleChanged
#define INCLUDE_ALL_ImDiyalogCoreEventsAppVisibleChanged 0
#else
#define INCLUDE_ALL_ImDiyalogCoreEventsAppVisibleChanged 1
#endif
#undef RESTRICT_ImDiyalogCoreEventsAppVisibleChanged

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImDiyalogCoreEventsAppVisibleChanged_) && (INCLUDE_ALL_ImDiyalogCoreEventsAppVisibleChanged || defined(INCLUDE_ImDiyalogCoreEventsAppVisibleChanged))
#define ImDiyalogCoreEventsAppVisibleChanged_

#define RESTRICT_ImDiyalogRuntimeEventbusEvent 1
#define INCLUDE_ImDiyalogRuntimeEventbusEvent 1
#include "../../../../im/diyalog/runtime/eventbus/Event.h"

@interface ImDiyalogCoreEventsAppVisibleChanged : ImDiyalogRuntimeEventbusEvent

+ (NSString *)EVENT;

#pragma mark Public

- (instancetype)initWithBoolean:(jboolean)isVisible;

- (NSString *)getType;

- (jboolean)isVisible;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogCoreEventsAppVisibleChanged)

inline NSString *ImDiyalogCoreEventsAppVisibleChanged_get_EVENT();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ImDiyalogCoreEventsAppVisibleChanged_EVENT;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ImDiyalogCoreEventsAppVisibleChanged, EVENT, NSString *)

FOUNDATION_EXPORT void ImDiyalogCoreEventsAppVisibleChanged_initWithBoolean_(ImDiyalogCoreEventsAppVisibleChanged *self, jboolean isVisible);

FOUNDATION_EXPORT ImDiyalogCoreEventsAppVisibleChanged *new_ImDiyalogCoreEventsAppVisibleChanged_initWithBoolean_(jboolean isVisible) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogCoreEventsAppVisibleChanged *create_ImDiyalogCoreEventsAppVisibleChanged_initWithBoolean_(jboolean isVisible);

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogCoreEventsAppVisibleChanged)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreEventsAppVisibleChanged")
