//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/api/updates/UpdateOwnStickersChanged.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreApiUpdatesUpdateOwnStickersChanged")
#ifdef RESTRICT_ImDiyalogCoreApiUpdatesUpdateOwnStickersChanged
#define INCLUDE_ALL_ImDiyalogCoreApiUpdatesUpdateOwnStickersChanged 0
#else
#define INCLUDE_ALL_ImDiyalogCoreApiUpdatesUpdateOwnStickersChanged 1
#endif
#undef RESTRICT_ImDiyalogCoreApiUpdatesUpdateOwnStickersChanged

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARUpdateOwnStickersChanged_) && (INCLUDE_ALL_ImDiyalogCoreApiUpdatesUpdateOwnStickersChanged || defined(INCLUDE_ARUpdateOwnStickersChanged))
#define ARUpdateOwnStickersChanged_

#define RESTRICT_ImDiyalogCoreNetworkParserUpdate 1
#define INCLUDE_ACUpdate 1
#include "../../../../../im/diyalog/core/network/parser/Update.h"

@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;
@protocol JavaUtilList;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARUpdateOwnStickersChanged : ACUpdate

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithJavaUtilList:(id<JavaUtilList> __nonnull)collections;

+ (ARUpdateOwnStickersChanged *)fromBytesWithByteArray:(IOSByteArray *)data;

- (id<JavaUtilList> __nonnull)getCollections;

- (jint)getHeaderKey;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARUpdateOwnStickersChanged)

inline jint ARUpdateOwnStickersChanged_get_HEADER();
#define ARUpdateOwnStickersChanged_HEADER 161
J2OBJC_STATIC_FIELD_CONSTANT(ARUpdateOwnStickersChanged, HEADER, jint)

FOUNDATION_EXPORT ARUpdateOwnStickersChanged *ARUpdateOwnStickersChanged_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARUpdateOwnStickersChanged_initWithJavaUtilList_(ARUpdateOwnStickersChanged *self, id<JavaUtilList> collections);

FOUNDATION_EXPORT ARUpdateOwnStickersChanged *new_ARUpdateOwnStickersChanged_initWithJavaUtilList_(id<JavaUtilList> collections) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARUpdateOwnStickersChanged *create_ARUpdateOwnStickersChanged_initWithJavaUtilList_(id<JavaUtilList> collections);

FOUNDATION_EXPORT void ARUpdateOwnStickersChanged_init(ARUpdateOwnStickersChanged *self);

FOUNDATION_EXPORT ARUpdateOwnStickersChanged *new_ARUpdateOwnStickersChanged_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARUpdateOwnStickersChanged *create_ARUpdateOwnStickersChanged_init();

J2OBJC_TYPE_LITERAL_HEADER(ARUpdateOwnStickersChanged)

@compatibility_alias ImDiyalogCoreApiUpdatesUpdateOwnStickersChanged ARUpdateOwnStickersChanged;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreApiUpdatesUpdateOwnStickersChanged")
