//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/api/updates/UpdateEmptyUpdate.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreApiUpdatesUpdateEmptyUpdate")
#ifdef RESTRICT_ImDiyalogCoreApiUpdatesUpdateEmptyUpdate
#define INCLUDE_ALL_ImDiyalogCoreApiUpdatesUpdateEmptyUpdate 0
#else
#define INCLUDE_ALL_ImDiyalogCoreApiUpdatesUpdateEmptyUpdate 1
#endif
#undef RESTRICT_ImDiyalogCoreApiUpdatesUpdateEmptyUpdate

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARUpdateEmptyUpdate_) && (INCLUDE_ALL_ImDiyalogCoreApiUpdatesUpdateEmptyUpdate || defined(INCLUDE_ARUpdateEmptyUpdate))
#define ARUpdateEmptyUpdate_

#define RESTRICT_ImDiyalogCoreNetworkParserUpdate 1
#define INCLUDE_ACUpdate 1
#include "../../../../../im/diyalog/core/network/parser/Update.h"

@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

@interface ARUpdateEmptyUpdate : ACUpdate

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

+ (ARUpdateEmptyUpdate *)fromBytesWithByteArray:(IOSByteArray *)data;

- (jint)getHeaderKey;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARUpdateEmptyUpdate)

inline jint ARUpdateEmptyUpdate_get_HEADER();
#define ARUpdateEmptyUpdate_HEADER 85
J2OBJC_STATIC_FIELD_CONSTANT(ARUpdateEmptyUpdate, HEADER, jint)

FOUNDATION_EXPORT ARUpdateEmptyUpdate *ARUpdateEmptyUpdate_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARUpdateEmptyUpdate_init(ARUpdateEmptyUpdate *self);

FOUNDATION_EXPORT ARUpdateEmptyUpdate *new_ARUpdateEmptyUpdate_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARUpdateEmptyUpdate *create_ARUpdateEmptyUpdate_init();

J2OBJC_TYPE_LITERAL_HEADER(ARUpdateEmptyUpdate)

@compatibility_alias ImDiyalogCoreApiUpdatesUpdateEmptyUpdate ARUpdateEmptyUpdate;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreApiUpdatesUpdateEmptyUpdate")
