//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/modules/messaging/actors/entity/Delete.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreModulesMessagingActorsEntityDelete")
#ifdef RESTRICT_ImDiyalogCoreModulesMessagingActorsEntityDelete
#define INCLUDE_ALL_ImDiyalogCoreModulesMessagingActorsEntityDelete 0
#else
#define INCLUDE_ALL_ImDiyalogCoreModulesMessagingActorsEntityDelete 1
#endif
#undef RESTRICT_ImDiyalogCoreModulesMessagingActorsEntityDelete

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImDiyalogCoreModulesMessagingActorsEntityDelete_) && (INCLUDE_ALL_ImDiyalogCoreModulesMessagingActorsEntityDelete || defined(INCLUDE_ImDiyalogCoreModulesMessagingActorsEntityDelete))
#define ImDiyalogCoreModulesMessagingActorsEntityDelete_

#define RESTRICT_ImDiyalogRuntimeBserBserObject 1
#define INCLUDE_ARBserObject 1
#include "../../../../../../../im/diyalog/runtime/bser/BserObject.h"

@class ACPeer;
@class ARBserValues;
@class ARBserWriter;
@protocol JavaUtilList;

@interface ImDiyalogCoreModulesMessagingActorsEntityDelete : ARBserObject

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithACPeer:(ACPeer *)peer
              withJavaUtilList:(id<JavaUtilList>)rids;

- (ACPeer *)getPeer;

- (id<JavaUtilList>)getRids;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogCoreModulesMessagingActorsEntityDelete)

FOUNDATION_EXPORT void ImDiyalogCoreModulesMessagingActorsEntityDelete_initWithACPeer_withJavaUtilList_(ImDiyalogCoreModulesMessagingActorsEntityDelete *self, ACPeer *peer, id<JavaUtilList> rids);

FOUNDATION_EXPORT ImDiyalogCoreModulesMessagingActorsEntityDelete *new_ImDiyalogCoreModulesMessagingActorsEntityDelete_initWithACPeer_withJavaUtilList_(ACPeer *peer, id<JavaUtilList> rids) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogCoreModulesMessagingActorsEntityDelete *create_ImDiyalogCoreModulesMessagingActorsEntityDelete_initWithACPeer_withJavaUtilList_(ACPeer *peer, id<JavaUtilList> rids);

FOUNDATION_EXPORT void ImDiyalogCoreModulesMessagingActorsEntityDelete_init(ImDiyalogCoreModulesMessagingActorsEntityDelete *self);

FOUNDATION_EXPORT ImDiyalogCoreModulesMessagingActorsEntityDelete *new_ImDiyalogCoreModulesMessagingActorsEntityDelete_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogCoreModulesMessagingActorsEntityDelete *create_ImDiyalogCoreModulesMessagingActorsEntityDelete_init();

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogCoreModulesMessagingActorsEntityDelete)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreModulesMessagingActorsEntityDelete")
