//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/modules/security/SecurityModule.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreModulesSecuritySecurityModule")
#ifdef RESTRICT_ImDiyalogCoreModulesSecuritySecurityModule
#define INCLUDE_ALL_ImDiyalogCoreModulesSecuritySecurityModule 0
#else
#define INCLUDE_ALL_ImDiyalogCoreModulesSecuritySecurityModule 1
#endif
#undef RESTRICT_ImDiyalogCoreModulesSecuritySecurityModule

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImDiyalogCoreModulesSecuritySecurityModule_) && (INCLUDE_ALL_ImDiyalogCoreModulesSecuritySecurityModule || defined(INCLUDE_ImDiyalogCoreModulesSecuritySecurityModule))
#define ImDiyalogCoreModulesSecuritySecurityModule_

#define RESTRICT_ImDiyalogCoreModulesAbsModule 1
#define INCLUDE_ACAbsModule 1
#include "../../../../../im/diyalog/core/modules/AbsModule.h"

@protocol ACCommand;
@protocol ACModuleContext;

@interface ImDiyalogCoreModulesSecuritySecurityModule : ACAbsModule

#pragma mark Public

- (instancetype)initWithACModuleContext:(id<ACModuleContext>)context;

- (id<ACCommand>)loadSessions;

- (id<ACCommand>)terminateAllSessions;

- (id<ACCommand>)terminateSessionWithInt:(jint)id_;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogCoreModulesSecuritySecurityModule)

FOUNDATION_EXPORT void ImDiyalogCoreModulesSecuritySecurityModule_initWithACModuleContext_(ImDiyalogCoreModulesSecuritySecurityModule *self, id<ACModuleContext> context);

FOUNDATION_EXPORT ImDiyalogCoreModulesSecuritySecurityModule *new_ImDiyalogCoreModulesSecuritySecurityModule_initWithACModuleContext_(id<ACModuleContext> context) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogCoreModulesSecuritySecurityModule *create_ImDiyalogCoreModulesSecuritySecurityModule_initWithACModuleContext_(id<ACModuleContext> context);

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogCoreModulesSecuritySecurityModule)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreModulesSecuritySecurityModule")
