//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/modules/calls/peers/PeerCallActor.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreModulesCallsPeersPeerCallActor")
#ifdef RESTRICT_ImDiyalogCoreModulesCallsPeersPeerCallActor
#define INCLUDE_ALL_ImDiyalogCoreModulesCallsPeersPeerCallActor 0
#else
#define INCLUDE_ALL_ImDiyalogCoreModulesCallsPeersPeerCallActor 1
#endif
#undef RESTRICT_ImDiyalogCoreModulesCallsPeersPeerCallActor

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImDiyalogCoreModulesCallsPeersPeerCallActor_) && (INCLUDE_ALL_ImDiyalogCoreModulesCallsPeersPeerCallActor || defined(INCLUDE_ImDiyalogCoreModulesCallsPeersPeerCallActor))
#define ImDiyalogCoreModulesCallsPeersPeerCallActor_

#define RESTRICT_ImDiyalogCoreModulesModuleActor 1
#define INCLUDE_ACModuleActor 1
#include "../../../../../../im/diyalog/core/modules/ModuleActor.h"

@class ImDiyalogCoreModulesCallsPeersPeerNodeInt;
@class ImDiyalogCoreModulesCallsPeersPeerSettings;
@protocol ACModuleContext;
@protocol ImDiyalogCoreModulesCallsPeersPeerCallCallback;
@protocol JavaUtilList;

@interface ImDiyalogCoreModulesCallsPeersPeerCallActor : ACModuleActor

#pragma mark Public

- (instancetype)initWithImDiyalogCoreModulesCallsPeersPeerCallCallback:(id<ImDiyalogCoreModulesCallsPeersPeerCallCallback>)callback
                        withImDiyalogCoreModulesCallsPeersPeerSettings:(ImDiyalogCoreModulesCallsPeersPeerSettings *)selfSettings
                                                   withACModuleContext:(id<ACModuleContext>)context;

- (ImDiyalogCoreModulesCallsPeersPeerNodeInt *)createNewPeerWithLong:(jlong)deviceId;

- (void)disposePeerWithLong:(jlong)deviceId;

- (ImDiyalogCoreModulesCallsPeersPeerNodeInt *)getPeerWithLong:(jlong)deviceId;

- (void)onMasterAdvertisedWithJavaUtilList:(id<JavaUtilList>)iceServers;

- (void)onMuteChangedWithBoolean:(jboolean)isMuted;

- (void)onOwnStarted;

- (void)onReceiveWithId:(id)message;

- (void)postStop;

- (void)preStart;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogCoreModulesCallsPeersPeerCallActor)

FOUNDATION_EXPORT void ImDiyalogCoreModulesCallsPeersPeerCallActor_initWithImDiyalogCoreModulesCallsPeersPeerCallCallback_withImDiyalogCoreModulesCallsPeersPeerSettings_withACModuleContext_(ImDiyalogCoreModulesCallsPeersPeerCallActor *self, id<ImDiyalogCoreModulesCallsPeersPeerCallCallback> callback, ImDiyalogCoreModulesCallsPeersPeerSettings *selfSettings, id<ACModuleContext> context);

FOUNDATION_EXPORT ImDiyalogCoreModulesCallsPeersPeerCallActor *new_ImDiyalogCoreModulesCallsPeersPeerCallActor_initWithImDiyalogCoreModulesCallsPeersPeerCallCallback_withImDiyalogCoreModulesCallsPeersPeerSettings_withACModuleContext_(id<ImDiyalogCoreModulesCallsPeersPeerCallCallback> callback, ImDiyalogCoreModulesCallsPeersPeerSettings *selfSettings, id<ACModuleContext> context) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogCoreModulesCallsPeersPeerCallActor *create_ImDiyalogCoreModulesCallsPeersPeerCallActor_initWithImDiyalogCoreModulesCallsPeersPeerCallCallback_withImDiyalogCoreModulesCallsPeersPeerSettings_withACModuleContext_(id<ImDiyalogCoreModulesCallsPeersPeerCallCallback> callback, ImDiyalogCoreModulesCallsPeersPeerSettings *selfSettings, id<ACModuleContext> context);

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogCoreModulesCallsPeersPeerCallActor)

#endif

#if !defined (ImDiyalogCoreModulesCallsPeersPeerCallActor_MuteChanged_) && (INCLUDE_ALL_ImDiyalogCoreModulesCallsPeersPeerCallActor || defined(INCLUDE_ImDiyalogCoreModulesCallsPeersPeerCallActor_MuteChanged))
#define ImDiyalogCoreModulesCallsPeersPeerCallActor_MuteChanged_

@interface ImDiyalogCoreModulesCallsPeersPeerCallActor_MuteChanged : NSObject

#pragma mark Public

- (instancetype)initWithBoolean:(jboolean)isMuted;

- (jboolean)isMuted;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogCoreModulesCallsPeersPeerCallActor_MuteChanged)

FOUNDATION_EXPORT void ImDiyalogCoreModulesCallsPeersPeerCallActor_MuteChanged_initWithBoolean_(ImDiyalogCoreModulesCallsPeersPeerCallActor_MuteChanged *self, jboolean isMuted);

FOUNDATION_EXPORT ImDiyalogCoreModulesCallsPeersPeerCallActor_MuteChanged *new_ImDiyalogCoreModulesCallsPeersPeerCallActor_MuteChanged_initWithBoolean_(jboolean isMuted) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogCoreModulesCallsPeersPeerCallActor_MuteChanged *create_ImDiyalogCoreModulesCallsPeersPeerCallActor_MuteChanged_initWithBoolean_(jboolean isMuted);

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogCoreModulesCallsPeersPeerCallActor_MuteChanged)

#endif

#if !defined (ImDiyalogCoreModulesCallsPeersPeerCallActor_OwnStarted_) && (INCLUDE_ALL_ImDiyalogCoreModulesCallsPeersPeerCallActor || defined(INCLUDE_ImDiyalogCoreModulesCallsPeersPeerCallActor_OwnStarted))
#define ImDiyalogCoreModulesCallsPeersPeerCallActor_OwnStarted_

@interface ImDiyalogCoreModulesCallsPeersPeerCallActor_OwnStarted : NSObject

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogCoreModulesCallsPeersPeerCallActor_OwnStarted)

FOUNDATION_EXPORT void ImDiyalogCoreModulesCallsPeersPeerCallActor_OwnStarted_init(ImDiyalogCoreModulesCallsPeersPeerCallActor_OwnStarted *self);

FOUNDATION_EXPORT ImDiyalogCoreModulesCallsPeersPeerCallActor_OwnStarted *new_ImDiyalogCoreModulesCallsPeersPeerCallActor_OwnStarted_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogCoreModulesCallsPeersPeerCallActor_OwnStarted *create_ImDiyalogCoreModulesCallsPeersPeerCallActor_OwnStarted_init();

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogCoreModulesCallsPeersPeerCallActor_OwnStarted)

#endif

#if !defined (ImDiyalogCoreModulesCallsPeersPeerCallActor_MasterAdvertised_) && (INCLUDE_ALL_ImDiyalogCoreModulesCallsPeersPeerCallActor || defined(INCLUDE_ImDiyalogCoreModulesCallsPeersPeerCallActor_MasterAdvertised))
#define ImDiyalogCoreModulesCallsPeersPeerCallActor_MasterAdvertised_

@interface ImDiyalogCoreModulesCallsPeersPeerCallActor_MasterAdvertised : NSObject

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogCoreModulesCallsPeersPeerCallActor_MasterAdvertised)

FOUNDATION_EXPORT void ImDiyalogCoreModulesCallsPeersPeerCallActor_MasterAdvertised_init(ImDiyalogCoreModulesCallsPeersPeerCallActor_MasterAdvertised *self);

FOUNDATION_EXPORT ImDiyalogCoreModulesCallsPeersPeerCallActor_MasterAdvertised *new_ImDiyalogCoreModulesCallsPeersPeerCallActor_MasterAdvertised_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogCoreModulesCallsPeersPeerCallActor_MasterAdvertised *create_ImDiyalogCoreModulesCallsPeersPeerCallActor_MasterAdvertised_init();

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogCoreModulesCallsPeersPeerCallActor_MasterAdvertised)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreModulesCallsPeersPeerCallActor")
