//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/runtime/runtime-shared/src/main/java/im/diyalog/runtime/mvvm/ValueDoubleChangedListener.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogRuntimeMvvmValueDoubleChangedListener")
#ifdef RESTRICT_ImDiyalogRuntimeMvvmValueDoubleChangedListener
#define INCLUDE_ALL_ImDiyalogRuntimeMvvmValueDoubleChangedListener 0
#else
#define INCLUDE_ALL_ImDiyalogRuntimeMvvmValueDoubleChangedListener 1
#endif
#undef RESTRICT_ImDiyalogRuntimeMvvmValueDoubleChangedListener

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARValueDoubleChangedListener_) && (INCLUDE_ALL_ImDiyalogRuntimeMvvmValueDoubleChangedListener || defined(INCLUDE_ARValueDoubleChangedListener))
#define ARValueDoubleChangedListener_

@class ARValue;

@protocol ARValueDoubleChangedListener < NSObject, JavaObject >

- (void)onChanged:(id)val
        withModel:(ARValue *)valueModel
       withValue2:(id)val2
       withModel2:(ARValue *)valueModel2;

@end

J2OBJC_EMPTY_STATIC_INIT(ARValueDoubleChangedListener)

J2OBJC_TYPE_LITERAL_HEADER(ARValueDoubleChangedListener)

#define ImDiyalogRuntimeMvvmValueDoubleChangedListener ARValueDoubleChangedListener

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogRuntimeMvvmValueDoubleChangedListener")
