//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/runtime/runtime-shared/src/main/java/im/diyalog/runtime/storage/ListEngineItem.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogRuntimeStorageListEngineItem")
#ifdef RESTRICT_ImDiyalogRuntimeStorageListEngineItem
#define INCLUDE_ALL_ImDiyalogRuntimeStorageListEngineItem 0
#else
#define INCLUDE_ALL_ImDiyalogRuntimeStorageListEngineItem 1
#endif
#undef RESTRICT_ImDiyalogRuntimeStorageListEngineItem

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARListEngineItem_) && (INCLUDE_ALL_ImDiyalogRuntimeStorageListEngineItem || defined(INCLUDE_ARListEngineItem))
#define ARListEngineItem_

@protocol ARListEngineItem < NSObject, JavaObject >

- (jlong)getEngineId;

- (jlong)getEngineSort;

- (NSString *)getEngineSearch;

@end

J2OBJC_EMPTY_STATIC_INIT(ARListEngineItem)

J2OBJC_TYPE_LITERAL_HEADER(ARListEngineItem)

#define ImDiyalogRuntimeStorageListEngineItem ARListEngineItem

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogRuntimeStorageListEngineItem")
