//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/providers/NotificationProvider.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreProvidersNotificationProvider")
#ifdef RESTRICT_ImDiyalogCoreProvidersNotificationProvider
#define INCLUDE_ALL_ImDiyalogCoreProvidersNotificationProvider 0
#else
#define INCLUDE_ALL_ImDiyalogCoreProvidersNotificationProvider 1
#endif
#undef RESTRICT_ImDiyalogCoreProvidersNotificationProvider

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ACNotificationProvider_) && (INCLUDE_ALL_ImDiyalogCoreProvidersNotificationProvider || defined(INCLUDE_ACNotificationProvider))
#define ACNotificationProvider_

@class ACMessenger;
@protocol JavaUtilList;

/*!
 @brief Provider for notifications support
 */
@protocol ACNotificationProvider < NSObject, JavaObject >

/*!
 @brief Called when message arrive when user is in app (used for play in app sound).
 @param messenger Messenger object
 */
- (void)onMessageArriveInAppWithMessenger:(ACMessenger *)messenger;

/*!
 @brief On background notification
 @param messenger          Messenger object
 @param topNotifications   top 10 notifications
 @param messagesCount      total messages count
 @param conversationsCount total conversations count
 */
- (void)onNotificationWithMessenger:(ACMessenger *)messenger
               withTopNotifications:(id<JavaUtilList>)topNotifications
                  withMessagesCount:(jint)messagesCount
             withConversationsCount:(jint)conversationsCount;

/*!
 @brief On Notification panel update
 @param messenger          Messenger object
 @param topNotifications   top 10 notifications
 @param messagesCount      total messages count
 @param conversationsCount total conversations count
 */
- (void)onUpdateNotificationWithMessenger:(ACMessenger *)messenger
                     withTopNotifications:(id<JavaUtilList>)topNotifications
                        withMessagesCount:(jint)messagesCount
                   withConversationsCount:(jint)conversationsCount;

/*!
 @brief Hide all notifications
 */
- (void)hideAllNotifications;

@end

J2OBJC_EMPTY_STATIC_INIT(ACNotificationProvider)

J2OBJC_TYPE_LITERAL_HEADER(ACNotificationProvider)

#define ImDiyalogCoreProvidersNotificationProvider ACNotificationProvider

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreProvidersNotificationProvider")
