//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/runtime/runtime-shared/src/main/java/im/diyalog/runtime/crypto/primitives/streebog/Int512.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogRuntimeCryptoPrimitivesStreebogInt512")
#ifdef RESTRICT_ImDiyalogRuntimeCryptoPrimitivesStreebogInt512
#define INCLUDE_ALL_ImDiyalogRuntimeCryptoPrimitivesStreebogInt512 0
#else
#define INCLUDE_ALL_ImDiyalogRuntimeCryptoPrimitivesStreebogInt512 1
#endif
#undef RESTRICT_ImDiyalogRuntimeCryptoPrimitivesStreebogInt512

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImDiyalogRuntimeCryptoPrimitivesStreebogInt512_) && (INCLUDE_ALL_ImDiyalogRuntimeCryptoPrimitivesStreebogInt512 || defined(INCLUDE_ImDiyalogRuntimeCryptoPrimitivesStreebogInt512))
#define ImDiyalogRuntimeCryptoPrimitivesStreebogInt512_

@class IOSByteArray;

/*!
 @brief 512-bit variable
 */
@interface ImDiyalogRuntimeCryptoPrimitivesStreebogInt512 : NSObject

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithByteArray:(IOSByteArray *)value;

- (jbyte)getByteWithInt:(jint)index;

- (IOSByteArray *)getBytes;

- (jint)getWord16WithInt:(jint)index;

- (jlong)getWord64WithInt:(jint)index;

- (void)setByteWithInt:(jint)index
              withByte:(jbyte)v;

- (void)setBytesWithByteArray:(IOSByteArray *)value;

- (void)setWord16WithInt:(jint)index
                 withInt:(jint)val;

- (void)setWord64WithInt:(jint)index
                withLong:(jlong)val;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogRuntimeCryptoPrimitivesStreebogInt512)

FOUNDATION_EXPORT void ImDiyalogRuntimeCryptoPrimitivesStreebogInt512_initWithByteArray_(ImDiyalogRuntimeCryptoPrimitivesStreebogInt512 *self, IOSByteArray *value);

FOUNDATION_EXPORT ImDiyalogRuntimeCryptoPrimitivesStreebogInt512 *new_ImDiyalogRuntimeCryptoPrimitivesStreebogInt512_initWithByteArray_(IOSByteArray *value) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogRuntimeCryptoPrimitivesStreebogInt512 *create_ImDiyalogRuntimeCryptoPrimitivesStreebogInt512_initWithByteArray_(IOSByteArray *value);

FOUNDATION_EXPORT void ImDiyalogRuntimeCryptoPrimitivesStreebogInt512_init(ImDiyalogRuntimeCryptoPrimitivesStreebogInt512 *self);

FOUNDATION_EXPORT ImDiyalogRuntimeCryptoPrimitivesStreebogInt512 *new_ImDiyalogRuntimeCryptoPrimitivesStreebogInt512_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogRuntimeCryptoPrimitivesStreebogInt512 *create_ImDiyalogRuntimeCryptoPrimitivesStreebogInt512_init();

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogRuntimeCryptoPrimitivesStreebogInt512)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogRuntimeCryptoPrimitivesStreebogInt512")
