//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/runtime/runtime-shared/src/main/java/im/diyalog/runtime/crypto/primitives/streebog/StreebogDigest.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogRuntimeCryptoPrimitivesStreebogStreebogDigest")
#ifdef RESTRICT_ImDiyalogRuntimeCryptoPrimitivesStreebogStreebogDigest
#define INCLUDE_ALL_ImDiyalogRuntimeCryptoPrimitivesStreebogStreebogDigest 0
#else
#define INCLUDE_ALL_ImDiyalogRuntimeCryptoPrimitivesStreebogStreebogDigest 1
#endif
#undef RESTRICT_ImDiyalogRuntimeCryptoPrimitivesStreebogStreebogDigest

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImDiyalogRuntimeCryptoPrimitivesStreebogStreebogDigest_) && (INCLUDE_ALL_ImDiyalogRuntimeCryptoPrimitivesStreebogStreebogDigest || defined(INCLUDE_ImDiyalogRuntimeCryptoPrimitivesStreebogStreebogDigest))
#define ImDiyalogRuntimeCryptoPrimitivesStreebogStreebogDigest_

@class IOSByteArray;

@interface ImDiyalogRuntimeCryptoPrimitivesStreebogStreebogDigest : NSObject

#pragma mark Public

- (instancetype)initWithInt:(jint)hashLength;

- (void)doFinalWithByteArray:(IOSByteArray *)outArg
                     withInt:(jint)offset;

- (void)reset;

- (void)updateWithByteArray:(IOSByteArray *)inArg
                    withInt:(jint)offset
                    withInt:(jint)length;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogRuntimeCryptoPrimitivesStreebogStreebogDigest)

FOUNDATION_EXPORT void ImDiyalogRuntimeCryptoPrimitivesStreebogStreebogDigest_initWithInt_(ImDiyalogRuntimeCryptoPrimitivesStreebogStreebogDigest *self, jint hashLength);

FOUNDATION_EXPORT ImDiyalogRuntimeCryptoPrimitivesStreebogStreebogDigest *new_ImDiyalogRuntimeCryptoPrimitivesStreebogStreebogDigest_initWithInt_(jint hashLength) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogRuntimeCryptoPrimitivesStreebogStreebogDigest *create_ImDiyalogRuntimeCryptoPrimitivesStreebogStreebogDigest_initWithInt_(jint hashLength);

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogRuntimeCryptoPrimitivesStreebogStreebogDigest)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogRuntimeCryptoPrimitivesStreebogStreebogDigest")
