//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/runtime/runtime-shared/src/main/java/im/diyalog/runtime/crypto/primitives/streebog/Streebog256.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogRuntimeCryptoPrimitivesStreebogStreebog256")
#ifdef RESTRICT_ImDiyalogRuntimeCryptoPrimitivesStreebogStreebog256
#define INCLUDE_ALL_ImDiyalogRuntimeCryptoPrimitivesStreebogStreebog256 0
#else
#define INCLUDE_ALL_ImDiyalogRuntimeCryptoPrimitivesStreebogStreebog256 1
#endif
#undef RESTRICT_ImDiyalogRuntimeCryptoPrimitivesStreebogStreebog256

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImDiyalogRuntimeCryptoPrimitivesStreebogStreebog256_) && (INCLUDE_ALL_ImDiyalogRuntimeCryptoPrimitivesStreebogStreebog256 || defined(INCLUDE_ImDiyalogRuntimeCryptoPrimitivesStreebogStreebog256))
#define ImDiyalogRuntimeCryptoPrimitivesStreebogStreebog256_

#define RESTRICT_ImDiyalogRuntimeCryptoDigest 1
#define INCLUDE_ARDigest 1
#include "../../../../../../im/diyalog/runtime/crypto/Digest.h"

@class IOSByteArray;

@interface ImDiyalogRuntimeCryptoPrimitivesStreebogStreebog256 : NSObject < ARDigest >

#pragma mark Public

- (instancetype)init;

- (void)doFinal:(IOSByteArray *)dest
     withOffset:(jint)destOffset;

- (jint)getDigestSize;

- (void)reset;

- (void)update:(IOSByteArray *)src
    withOffset:(jint)offset
    withLength:(jint)length;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogRuntimeCryptoPrimitivesStreebogStreebog256)

FOUNDATION_EXPORT void ImDiyalogRuntimeCryptoPrimitivesStreebogStreebog256_init(ImDiyalogRuntimeCryptoPrimitivesStreebogStreebog256 *self);

FOUNDATION_EXPORT ImDiyalogRuntimeCryptoPrimitivesStreebogStreebog256 *new_ImDiyalogRuntimeCryptoPrimitivesStreebogStreebog256_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogRuntimeCryptoPrimitivesStreebogStreebog256 *create_ImDiyalogRuntimeCryptoPrimitivesStreebogStreebog256_init();

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogRuntimeCryptoPrimitivesStreebogStreebog256)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogRuntimeCryptoPrimitivesStreebogStreebog256")
