//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/api/rpc/RequestSendMessage.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcRequestSendMessage")
#ifdef RESTRICT_ImDiyalogCoreApiRpcRequestSendMessage
#define INCLUDE_ALL_ImDiyalogCoreApiRpcRequestSendMessage 0
#else
#define INCLUDE_ALL_ImDiyalogCoreApiRpcRequestSendMessage 1
#endif
#undef RESTRICT_ImDiyalogCoreApiRpcRequestSendMessage

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARRequestSendMessage_) && (INCLUDE_ALL_ImDiyalogCoreApiRpcRequestSendMessage || defined(INCLUDE_ARRequestSendMessage))
#define ARRequestSendMessage_

#define RESTRICT_ImDiyalogCoreNetworkParserRequest 1
#define INCLUDE_ACRequest 1
#include "../../../../../im/diyalog/core/network/parser/Request.h"

@class ARApiMessage;
@class ARApiOutPeer;
@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;
@class JavaLangInteger;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARRequestSendMessage : ACRequest

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithARApiOutPeer:(ARApiOutPeer * __nonnull)peer
                            withLong:(jlong)rid
                    withARApiMessage:(ARApiMessage * __nonnull)message
                 withJavaLangInteger:(JavaLangInteger * __nullable)isOnlyForUser;

+ (ARRequestSendMessage *)fromBytesWithByteArray:(IOSByteArray *)data;

- (jint)getHeaderKey;

- (JavaLangInteger * __nullable)getIsOnlyForUser;

- (ARApiMessage * __nonnull)getMessage;

- (ARApiOutPeer * __nonnull)getPeer;

- (jlong)getRid;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARRequestSendMessage)

inline jint ARRequestSendMessage_get_HEADER();
#define ARRequestSendMessage_HEADER 92
J2OBJC_STATIC_FIELD_CONSTANT(ARRequestSendMessage, HEADER, jint)

FOUNDATION_EXPORT ARRequestSendMessage *ARRequestSendMessage_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARRequestSendMessage_initWithARApiOutPeer_withLong_withARApiMessage_withJavaLangInteger_(ARRequestSendMessage *self, ARApiOutPeer *peer, jlong rid, ARApiMessage *message, JavaLangInteger *isOnlyForUser);

FOUNDATION_EXPORT ARRequestSendMessage *new_ARRequestSendMessage_initWithARApiOutPeer_withLong_withARApiMessage_withJavaLangInteger_(ARApiOutPeer *peer, jlong rid, ARApiMessage *message, JavaLangInteger *isOnlyForUser) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARRequestSendMessage *create_ARRequestSendMessage_initWithARApiOutPeer_withLong_withARApiMessage_withJavaLangInteger_(ARApiOutPeer *peer, jlong rid, ARApiMessage *message, JavaLangInteger *isOnlyForUser);

FOUNDATION_EXPORT void ARRequestSendMessage_init(ARRequestSendMessage *self);

FOUNDATION_EXPORT ARRequestSendMessage *new_ARRequestSendMessage_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARRequestSendMessage *create_ARRequestSendMessage_init();

J2OBJC_TYPE_LITERAL_HEADER(ARRequestSendMessage)

@compatibility_alias ImDiyalogCoreApiRpcRequestSendMessage ARRequestSendMessage;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcRequestSendMessage")
