//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/api/rpc/RequestTyping.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcRequestTyping")
#ifdef RESTRICT_ImDiyalogCoreApiRpcRequestTyping
#define INCLUDE_ALL_ImDiyalogCoreApiRpcRequestTyping 0
#else
#define INCLUDE_ALL_ImDiyalogCoreApiRpcRequestTyping 1
#endif
#undef RESTRICT_ImDiyalogCoreApiRpcRequestTyping

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARRequestTyping_) && (INCLUDE_ALL_ImDiyalogCoreApiRpcRequestTyping || defined(INCLUDE_ARRequestTyping))
#define ARRequestTyping_

#define RESTRICT_ImDiyalogCoreNetworkParserRequest 1
#define INCLUDE_ACRequest 1
#include "../../../../../im/diyalog/core/network/parser/Request.h"

@class ARApiOutPeer;
@class ARApiTypingType;
@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARRequestTyping : ACRequest

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithARApiOutPeer:(ARApiOutPeer * __nonnull)peer
                 withARApiTypingType:(ARApiTypingType * __nonnull)typingType;

+ (ARRequestTyping *)fromBytesWithByteArray:(IOSByteArray *)data;

- (jint)getHeaderKey;

- (ARApiOutPeer * __nonnull)getPeer;

- (ARApiTypingType * __nonnull)getTypingType;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARRequestTyping)

inline jint ARRequestTyping_get_HEADER();
#define ARRequestTyping_HEADER 27
J2OBJC_STATIC_FIELD_CONSTANT(ARRequestTyping, HEADER, jint)

FOUNDATION_EXPORT ARRequestTyping *ARRequestTyping_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARRequestTyping_initWithARApiOutPeer_withARApiTypingType_(ARRequestTyping *self, ARApiOutPeer *peer, ARApiTypingType *typingType);

FOUNDATION_EXPORT ARRequestTyping *new_ARRequestTyping_initWithARApiOutPeer_withARApiTypingType_(ARApiOutPeer *peer, ARApiTypingType *typingType) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARRequestTyping *create_ARRequestTyping_initWithARApiOutPeer_withARApiTypingType_(ARApiOutPeer *peer, ARApiTypingType *typingType);

FOUNDATION_EXPORT void ARRequestTyping_init(ARRequestTyping *self);

FOUNDATION_EXPORT ARRequestTyping *new_ARRequestTyping_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARRequestTyping *create_ARRequestTyping_init();

J2OBJC_TYPE_LITERAL_HEADER(ARRequestTyping)

@compatibility_alias ImDiyalogCoreApiRpcRequestTyping ARRequestTyping;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcRequestTyping")
