//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/api/rpc/ResponseLoadArchived.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcResponseLoadArchived")
#ifdef RESTRICT_ImDiyalogCoreApiRpcResponseLoadArchived
#define INCLUDE_ALL_ImDiyalogCoreApiRpcResponseLoadArchived 0
#else
#define INCLUDE_ALL_ImDiyalogCoreApiRpcResponseLoadArchived 1
#endif
#undef RESTRICT_ImDiyalogCoreApiRpcResponseLoadArchived

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARResponseLoadArchived_) && (INCLUDE_ALL_ImDiyalogCoreApiRpcResponseLoadArchived || defined(INCLUDE_ARResponseLoadArchived))
#define ARResponseLoadArchived_

#define RESTRICT_ImDiyalogCoreNetworkParserResponse 1
#define INCLUDE_ACResponse 1
#include "../../../../../im/diyalog/core/network/parser/Response.h"

@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;
@protocol JavaUtilList;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARResponseLoadArchived : ACResponse

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithJavaUtilList:(id<JavaUtilList> __nonnull)groups
                    withJavaUtilList:(id<JavaUtilList> __nonnull)users
                    withJavaUtilList:(id<JavaUtilList> __nonnull)dialogs
                       withByteArray:(IOSByteArray * __nullable)nextOffset;

+ (ARResponseLoadArchived *)fromBytesWithByteArray:(IOSByteArray *)data;

- (id<JavaUtilList> __nonnull)getDialogs;

- (id<JavaUtilList> __nonnull)getGroups;

- (jint)getHeaderKey;

- (IOSByteArray * __nullable)getNextOffset;

- (id<JavaUtilList> __nonnull)getUsers;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARResponseLoadArchived)

inline jint ARResponseLoadArchived_get_HEADER();
#define ARResponseLoadArchived_HEADER 2652
J2OBJC_STATIC_FIELD_CONSTANT(ARResponseLoadArchived, HEADER, jint)

FOUNDATION_EXPORT ARResponseLoadArchived *ARResponseLoadArchived_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARResponseLoadArchived_initWithJavaUtilList_withJavaUtilList_withJavaUtilList_withByteArray_(ARResponseLoadArchived *self, id<JavaUtilList> groups, id<JavaUtilList> users, id<JavaUtilList> dialogs, IOSByteArray *nextOffset);

FOUNDATION_EXPORT ARResponseLoadArchived *new_ARResponseLoadArchived_initWithJavaUtilList_withJavaUtilList_withJavaUtilList_withByteArray_(id<JavaUtilList> groups, id<JavaUtilList> users, id<JavaUtilList> dialogs, IOSByteArray *nextOffset) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARResponseLoadArchived *create_ARResponseLoadArchived_initWithJavaUtilList_withJavaUtilList_withJavaUtilList_withByteArray_(id<JavaUtilList> groups, id<JavaUtilList> users, id<JavaUtilList> dialogs, IOSByteArray *nextOffset);

FOUNDATION_EXPORT void ARResponseLoadArchived_init(ARResponseLoadArchived *self);

FOUNDATION_EXPORT ARResponseLoadArchived *new_ARResponseLoadArchived_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARResponseLoadArchived *create_ARResponseLoadArchived_init();

J2OBJC_TYPE_LITERAL_HEADER(ARResponseLoadArchived)

@compatibility_alias ImDiyalogCoreApiRpcResponseLoadArchived ARResponseLoadArchived;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcResponseLoadArchived")
