//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/api/rpc/ResponseVoid.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcResponseVoid")
#ifdef RESTRICT_ImDiyalogCoreApiRpcResponseVoid
#define INCLUDE_ALL_ImDiyalogCoreApiRpcResponseVoid 0
#else
#define INCLUDE_ALL_ImDiyalogCoreApiRpcResponseVoid 1
#endif
#undef RESTRICT_ImDiyalogCoreApiRpcResponseVoid

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARResponseVoid_) && (INCLUDE_ALL_ImDiyalogCoreApiRpcResponseVoid || defined(INCLUDE_ARResponseVoid))
#define ARResponseVoid_

#define RESTRICT_ImDiyalogCoreNetworkParserResponse 1
#define INCLUDE_ACResponse 1
#include "../../../../../im/diyalog/core/network/parser/Response.h"

@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

@interface ARResponseVoid : ACResponse

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

+ (ARResponseVoid *)fromBytesWithByteArray:(IOSByteArray *)data;

- (jint)getHeaderKey;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARResponseVoid)

inline jint ARResponseVoid_get_HEADER();
#define ARResponseVoid_HEADER 50
J2OBJC_STATIC_FIELD_CONSTANT(ARResponseVoid, HEADER, jint)

FOUNDATION_EXPORT ARResponseVoid *ARResponseVoid_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARResponseVoid_init(ARResponseVoid *self);

FOUNDATION_EXPORT ARResponseVoid *new_ARResponseVoid_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARResponseVoid *create_ARResponseVoid_init();

J2OBJC_TYPE_LITERAL_HEADER(ARResponseVoid)

@compatibility_alias ImDiyalogCoreApiRpcResponseVoid ARResponseVoid;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcResponseVoid")
