//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/api/rpc/ResponseDownloadSharedBlob.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcResponseDownloadSharedBlob")
#ifdef RESTRICT_ImDiyalogCoreApiRpcResponseDownloadSharedBlob
#define INCLUDE_ALL_ImDiyalogCoreApiRpcResponseDownloadSharedBlob 0
#else
#define INCLUDE_ALL_ImDiyalogCoreApiRpcResponseDownloadSharedBlob 1
#endif
#undef RESTRICT_ImDiyalogCoreApiRpcResponseDownloadSharedBlob

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARResponseDownloadSharedBlob_) && (INCLUDE_ALL_ImDiyalogCoreApiRpcResponseDownloadSharedBlob || defined(INCLUDE_ARResponseDownloadSharedBlob))
#define ARResponseDownloadSharedBlob_

#define RESTRICT_ImDiyalogCoreNetworkParserResponse 1
#define INCLUDE_ACResponse 1
#include "../../../../../im/diyalog/core/network/parser/Response.h"

@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARResponseDownloadSharedBlob : ACResponse

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithByteArray:(IOSByteArray * __nonnull)blob;

+ (ARResponseDownloadSharedBlob *)fromBytesWithByteArray:(IOSByteArray *)data;

- (IOSByteArray * __nonnull)getBlob;

- (jint)getHeaderKey;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARResponseDownloadSharedBlob)

inline jint ARResponseDownloadSharedBlob_get_HEADER();
#define ARResponseDownloadSharedBlob_HEADER 2663
J2OBJC_STATIC_FIELD_CONSTANT(ARResponseDownloadSharedBlob, HEADER, jint)

FOUNDATION_EXPORT ARResponseDownloadSharedBlob *ARResponseDownloadSharedBlob_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARResponseDownloadSharedBlob_initWithByteArray_(ARResponseDownloadSharedBlob *self, IOSByteArray *blob);

FOUNDATION_EXPORT ARResponseDownloadSharedBlob *new_ARResponseDownloadSharedBlob_initWithByteArray_(IOSByteArray *blob) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARResponseDownloadSharedBlob *create_ARResponseDownloadSharedBlob_initWithByteArray_(IOSByteArray *blob);

FOUNDATION_EXPORT void ARResponseDownloadSharedBlob_init(ARResponseDownloadSharedBlob *self);

FOUNDATION_EXPORT ARResponseDownloadSharedBlob *new_ARResponseDownloadSharedBlob_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARResponseDownloadSharedBlob *create_ARResponseDownloadSharedBlob_init();

J2OBJC_TYPE_LITERAL_HEADER(ARResponseDownloadSharedBlob)

@compatibility_alias ImDiyalogCoreApiRpcResponseDownloadSharedBlob ARResponseDownloadSharedBlob;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcResponseDownloadSharedBlob")
