//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/modules/usagetracker/UsageTrackerModule.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreModulesUsagetrackerUsageTrackerModule")
#ifdef RESTRICT_ImDiyalogCoreModulesUsagetrackerUsageTrackerModule
#define INCLUDE_ALL_ImDiyalogCoreModulesUsagetrackerUsageTrackerModule 0
#else
#define INCLUDE_ALL_ImDiyalogCoreModulesUsagetrackerUsageTrackerModule 1
#endif
#undef RESTRICT_ImDiyalogCoreModulesUsagetrackerUsageTrackerModule

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImDiyalogCoreModulesUsagetrackerUsageTrackerModule_) && (INCLUDE_ALL_ImDiyalogCoreModulesUsagetrackerUsageTrackerModule || defined(INCLUDE_ImDiyalogCoreModulesUsagetrackerUsageTrackerModule))
#define ImDiyalogCoreModulesUsagetrackerUsageTrackerModule_

#define RESTRICT_ImDiyalogCoreModulesAbsModule 1
#define INCLUDE_ACAbsModule 1
#include "../../../../../im/diyalog/core/modules/AbsModule.h"

@class ACUsageTrackerVM;
@protocol ACModuleContext;

@interface ImDiyalogCoreModulesUsagetrackerUsageTrackerModule : ACAbsModule

#pragma mark Public

- (instancetype)initWithACModuleContext:(id<ACModuleContext>)context;

- (ACUsageTrackerVM *)getUsageTracker;

- (void)onUsageEvent;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogCoreModulesUsagetrackerUsageTrackerModule)

FOUNDATION_EXPORT void ImDiyalogCoreModulesUsagetrackerUsageTrackerModule_initWithACModuleContext_(ImDiyalogCoreModulesUsagetrackerUsageTrackerModule *self, id<ACModuleContext> context);

FOUNDATION_EXPORT ImDiyalogCoreModulesUsagetrackerUsageTrackerModule *new_ImDiyalogCoreModulesUsagetrackerUsageTrackerModule_initWithACModuleContext_(id<ACModuleContext> context) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogCoreModulesUsagetrackerUsageTrackerModule *create_ImDiyalogCoreModulesUsagetrackerUsageTrackerModule_initWithACModuleContext_(id<ACModuleContext> context);

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogCoreModulesUsagetrackerUsageTrackerModule)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreModulesUsagetrackerUsageTrackerModule")
