//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/api/rpc/RequestEditUserLocalName.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcRequestEditUserLocalName")
#ifdef RESTRICT_ImDiyalogCoreApiRpcRequestEditUserLocalName
#define INCLUDE_ALL_ImDiyalogCoreApiRpcRequestEditUserLocalName 0
#else
#define INCLUDE_ALL_ImDiyalogCoreApiRpcRequestEditUserLocalName 1
#endif
#undef RESTRICT_ImDiyalogCoreApiRpcRequestEditUserLocalName

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARRequestEditUserLocalName_) && (INCLUDE_ALL_ImDiyalogCoreApiRpcRequestEditUserLocalName || defined(INCLUDE_ARRequestEditUserLocalName))
#define ARRequestEditUserLocalName_

#define RESTRICT_ImDiyalogCoreNetworkParserRequest 1
#define INCLUDE_ACRequest 1
#include "../../../../../im/diyalog/core/network/parser/Request.h"

@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARRequestEditUserLocalName : ACRequest

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithInt:(jint)uid
                   withLong:(jlong)accessHash
               withNSString:(NSString * __nonnull)name;

+ (ARRequestEditUserLocalName *)fromBytesWithByteArray:(IOSByteArray *)data;

- (jlong)getAccessHash;

- (jint)getHeaderKey;

- (NSString * __nonnull)getName;

- (jint)getUid;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARRequestEditUserLocalName)

inline jint ARRequestEditUserLocalName_get_HEADER();
#define ARRequestEditUserLocalName_HEADER 96
J2OBJC_STATIC_FIELD_CONSTANT(ARRequestEditUserLocalName, HEADER, jint)

FOUNDATION_EXPORT ARRequestEditUserLocalName *ARRequestEditUserLocalName_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARRequestEditUserLocalName_initWithInt_withLong_withNSString_(ARRequestEditUserLocalName *self, jint uid, jlong accessHash, NSString *name);

FOUNDATION_EXPORT ARRequestEditUserLocalName *new_ARRequestEditUserLocalName_initWithInt_withLong_withNSString_(jint uid, jlong accessHash, NSString *name) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARRequestEditUserLocalName *create_ARRequestEditUserLocalName_initWithInt_withLong_withNSString_(jint uid, jlong accessHash, NSString *name);

FOUNDATION_EXPORT void ARRequestEditUserLocalName_init(ARRequestEditUserLocalName *self);

FOUNDATION_EXPORT ARRequestEditUserLocalName *new_ARRequestEditUserLocalName_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARRequestEditUserLocalName *create_ARRequestEditUserLocalName_init();

J2OBJC_TYPE_LITERAL_HEADER(ARRequestEditUserLocalName)

@compatibility_alias ImDiyalogCoreApiRpcRequestEditUserLocalName ARRequestEditUserLocalName;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcRequestEditUserLocalName")
