//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/api/rpc/RequestEditGroupTopic.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcRequestEditGroupTopic")
#ifdef RESTRICT_ImDiyalogCoreApiRpcRequestEditGroupTopic
#define INCLUDE_ALL_ImDiyalogCoreApiRpcRequestEditGroupTopic 0
#else
#define INCLUDE_ALL_ImDiyalogCoreApiRpcRequestEditGroupTopic 1
#endif
#undef RESTRICT_ImDiyalogCoreApiRpcRequestEditGroupTopic

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARRequestEditGroupTopic_) && (INCLUDE_ALL_ImDiyalogCoreApiRpcRequestEditGroupTopic || defined(INCLUDE_ARRequestEditGroupTopic))
#define ARRequestEditGroupTopic_

#define RESTRICT_ImDiyalogCoreNetworkParserRequest 1
#define INCLUDE_ACRequest 1
#include "../../../../../im/diyalog/core/network/parser/Request.h"

@class ARApiGroupOutPeer;
@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARRequestEditGroupTopic : ACRequest

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithARApiGroupOutPeer:(ARApiGroupOutPeer * __nonnull)groupPeer
                                 withLong:(jlong)rid
                             withNSString:(NSString * __nullable)topic;

+ (ARRequestEditGroupTopic *)fromBytesWithByteArray:(IOSByteArray *)data;

- (ARApiGroupOutPeer * __nonnull)getGroupPeer;

- (jint)getHeaderKey;

- (jlong)getRid;

- (NSString * __nullable)getTopic;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARRequestEditGroupTopic)

inline jint ARRequestEditGroupTopic_get_HEADER();
#define ARRequestEditGroupTopic_HEADER 211
J2OBJC_STATIC_FIELD_CONSTANT(ARRequestEditGroupTopic, HEADER, jint)

FOUNDATION_EXPORT ARRequestEditGroupTopic *ARRequestEditGroupTopic_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARRequestEditGroupTopic_initWithARApiGroupOutPeer_withLong_withNSString_(ARRequestEditGroupTopic *self, ARApiGroupOutPeer *groupPeer, jlong rid, NSString *topic);

FOUNDATION_EXPORT ARRequestEditGroupTopic *new_ARRequestEditGroupTopic_initWithARApiGroupOutPeer_withLong_withNSString_(ARApiGroupOutPeer *groupPeer, jlong rid, NSString *topic) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARRequestEditGroupTopic *create_ARRequestEditGroupTopic_initWithARApiGroupOutPeer_withLong_withNSString_(ARApiGroupOutPeer *groupPeer, jlong rid, NSString *topic);

FOUNDATION_EXPORT void ARRequestEditGroupTopic_init(ARRequestEditGroupTopic *self);

FOUNDATION_EXPORT ARRequestEditGroupTopic *new_ARRequestEditGroupTopic_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARRequestEditGroupTopic *create_ARRequestEditGroupTopic_init();

J2OBJC_TYPE_LITERAL_HEADER(ARRequestEditGroupTopic)

@compatibility_alias ImDiyalogCoreApiRpcRequestEditGroupTopic ARRequestEditGroupTopic;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcRequestEditGroupTopic")
