//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/api/rpc/RequestGetGroupInviteUrl.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcRequestGetGroupInviteUrl")
#ifdef RESTRICT_ImDiyalogCoreApiRpcRequestGetGroupInviteUrl
#define INCLUDE_ALL_ImDiyalogCoreApiRpcRequestGetGroupInviteUrl 0
#else
#define INCLUDE_ALL_ImDiyalogCoreApiRpcRequestGetGroupInviteUrl 1
#endif
#undef RESTRICT_ImDiyalogCoreApiRpcRequestGetGroupInviteUrl

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARRequestGetGroupInviteUrl_) && (INCLUDE_ALL_ImDiyalogCoreApiRpcRequestGetGroupInviteUrl || defined(INCLUDE_ARRequestGetGroupInviteUrl))
#define ARRequestGetGroupInviteUrl_

#define RESTRICT_ImDiyalogCoreNetworkParserRequest 1
#define INCLUDE_ACRequest 1
#include "../../../../../im/diyalog/core/network/parser/Request.h"

@class ARApiGroupOutPeer;
@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARRequestGetGroupInviteUrl : ACRequest

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithARApiGroupOutPeer:(ARApiGroupOutPeer * __nonnull)groupPeer;

+ (ARRequestGetGroupInviteUrl *)fromBytesWithByteArray:(IOSByteArray *)data;

- (ARApiGroupOutPeer * __nonnull)getGroupPeer;

- (jint)getHeaderKey;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARRequestGetGroupInviteUrl)

inline jint ARRequestGetGroupInviteUrl_get_HEADER();
#define ARRequestGetGroupInviteUrl_HEADER 177
J2OBJC_STATIC_FIELD_CONSTANT(ARRequestGetGroupInviteUrl, HEADER, jint)

FOUNDATION_EXPORT ARRequestGetGroupInviteUrl *ARRequestGetGroupInviteUrl_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARRequestGetGroupInviteUrl_initWithARApiGroupOutPeer_(ARRequestGetGroupInviteUrl *self, ARApiGroupOutPeer *groupPeer);

FOUNDATION_EXPORT ARRequestGetGroupInviteUrl *new_ARRequestGetGroupInviteUrl_initWithARApiGroupOutPeer_(ARApiGroupOutPeer *groupPeer) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARRequestGetGroupInviteUrl *create_ARRequestGetGroupInviteUrl_initWithARApiGroupOutPeer_(ARApiGroupOutPeer *groupPeer);

FOUNDATION_EXPORT void ARRequestGetGroupInviteUrl_init(ARRequestGetGroupInviteUrl *self);

FOUNDATION_EXPORT ARRequestGetGroupInviteUrl *new_ARRequestGetGroupInviteUrl_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARRequestGetGroupInviteUrl *create_ARRequestGetGroupInviteUrl_init();

J2OBJC_TYPE_LITERAL_HEADER(ARRequestGetGroupInviteUrl)

@compatibility_alias ImDiyalogCoreApiRpcRequestGetGroupInviteUrl ARRequestGetGroupInviteUrl;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcRequestGetGroupInviteUrl")
