//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/api/rpc/RequestSendInvite.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcRequestSendInvite")
#ifdef RESTRICT_ImDiyalogCoreApiRpcRequestSendInvite
#define INCLUDE_ALL_ImDiyalogCoreApiRpcRequestSendInvite 0
#else
#define INCLUDE_ALL_ImDiyalogCoreApiRpcRequestSendInvite 1
#endif
#undef RESTRICT_ImDiyalogCoreApiRpcRequestSendInvite

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARRequestSendInvite_) && (INCLUDE_ALL_ImDiyalogCoreApiRpcRequestSendInvite || defined(INCLUDE_ARRequestSendInvite))
#define ARRequestSendInvite_

#define RESTRICT_ImDiyalogCoreNetworkParserRequest 1
#define INCLUDE_ACRequest 1
#include "../../../../../im/diyalog/core/network/parser/Request.h"

@class ARApiOutTeam;
@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARRequestSendInvite : ACRequest

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString * __nonnull)email
                    withNSString:(NSString * __nullable)name
                withARApiOutTeam:(ARApiOutTeam * __nullable)destTeam;

+ (ARRequestSendInvite *)fromBytesWithByteArray:(IOSByteArray *)data;

- (ARApiOutTeam * __nullable)getDestTeam;

- (NSString * __nonnull)getEmail;

- (jint)getHeaderKey;

- (NSString * __nullable)getName;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARRequestSendInvite)

inline jint ARRequestSendInvite_get_HEADER();
#define ARRequestSendInvite_HEADER 2565
J2OBJC_STATIC_FIELD_CONSTANT(ARRequestSendInvite, HEADER, jint)

FOUNDATION_EXPORT ARRequestSendInvite *ARRequestSendInvite_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARRequestSendInvite_initWithNSString_withNSString_withARApiOutTeam_(ARRequestSendInvite *self, NSString *email, NSString *name, ARApiOutTeam *destTeam);

FOUNDATION_EXPORT ARRequestSendInvite *new_ARRequestSendInvite_initWithNSString_withNSString_withARApiOutTeam_(NSString *email, NSString *name, ARApiOutTeam *destTeam) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARRequestSendInvite *create_ARRequestSendInvite_initWithNSString_withNSString_withARApiOutTeam_(NSString *email, NSString *name, ARApiOutTeam *destTeam);

FOUNDATION_EXPORT void ARRequestSendInvite_init(ARRequestSendInvite *self);

FOUNDATION_EXPORT ARRequestSendInvite *new_ARRequestSendInvite_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARRequestSendInvite *create_ARRequestSendInvite_init();

J2OBJC_TYPE_LITERAL_HEADER(ARRequestSendInvite)

@compatibility_alias ImDiyalogCoreApiRpcRequestSendInvite ARRequestSendInvite;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcRequestSendInvite")
