//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/api/rpc/RequestDeleteChat.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcRequestDeleteChat")
#ifdef RESTRICT_ImDiyalogCoreApiRpcRequestDeleteChat
#define INCLUDE_ALL_ImDiyalogCoreApiRpcRequestDeleteChat 0
#else
#define INCLUDE_ALL_ImDiyalogCoreApiRpcRequestDeleteChat 1
#endif
#undef RESTRICT_ImDiyalogCoreApiRpcRequestDeleteChat

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARRequestDeleteChat_) && (INCLUDE_ALL_ImDiyalogCoreApiRpcRequestDeleteChat || defined(INCLUDE_ARRequestDeleteChat))
#define ARRequestDeleteChat_

#define RESTRICT_ImDiyalogCoreNetworkParserRequest 1
#define INCLUDE_ACRequest 1
#include "../../../../../im/diyalog/core/network/parser/Request.h"

@class ARApiOutPeer;
@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARRequestDeleteChat : ACRequest

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithARApiOutPeer:(ARApiOutPeer * __nonnull)peer;

+ (ARRequestDeleteChat *)fromBytesWithByteArray:(IOSByteArray *)data;

- (jint)getHeaderKey;

- (ARApiOutPeer * __nonnull)getPeer;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARRequestDeleteChat)

inline jint ARRequestDeleteChat_get_HEADER();
#define ARRequestDeleteChat_HEADER 100
J2OBJC_STATIC_FIELD_CONSTANT(ARRequestDeleteChat, HEADER, jint)

FOUNDATION_EXPORT ARRequestDeleteChat *ARRequestDeleteChat_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARRequestDeleteChat_initWithARApiOutPeer_(ARRequestDeleteChat *self, ARApiOutPeer *peer);

FOUNDATION_EXPORT ARRequestDeleteChat *new_ARRequestDeleteChat_initWithARApiOutPeer_(ARApiOutPeer *peer) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARRequestDeleteChat *create_ARRequestDeleteChat_initWithARApiOutPeer_(ARApiOutPeer *peer);

FOUNDATION_EXPORT void ARRequestDeleteChat_init(ARRequestDeleteChat *self);

FOUNDATION_EXPORT ARRequestDeleteChat *new_ARRequestDeleteChat_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARRequestDeleteChat *create_ARRequestDeleteChat_init();

J2OBJC_TYPE_LITERAL_HEADER(ARRequestDeleteChat)

@compatibility_alias ImDiyalogCoreApiRpcRequestDeleteChat ARRequestDeleteChat;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcRequestDeleteChat")
