//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/api/rpc/RequestSignOut.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcRequestSignOut")
#ifdef RESTRICT_ImDiyalogCoreApiRpcRequestSignOut
#define INCLUDE_ALL_ImDiyalogCoreApiRpcRequestSignOut 0
#else
#define INCLUDE_ALL_ImDiyalogCoreApiRpcRequestSignOut 1
#endif
#undef RESTRICT_ImDiyalogCoreApiRpcRequestSignOut

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARRequestSignOut_) && (INCLUDE_ALL_ImDiyalogCoreApiRpcRequestSignOut || defined(INCLUDE_ARRequestSignOut))
#define ARRequestSignOut_

#define RESTRICT_ImDiyalogCoreNetworkParserRequest 1
#define INCLUDE_ACRequest 1
#include "../../../../../im/diyalog/core/network/parser/Request.h"

@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

@interface ARRequestSignOut : ACRequest

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

+ (ARRequestSignOut *)fromBytesWithByteArray:(IOSByteArray *)data;

- (jint)getHeaderKey;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARRequestSignOut)

inline jint ARRequestSignOut_get_HEADER();
#define ARRequestSignOut_HEADER 84
J2OBJC_STATIC_FIELD_CONSTANT(ARRequestSignOut, HEADER, jint)

FOUNDATION_EXPORT ARRequestSignOut *ARRequestSignOut_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARRequestSignOut_init(ARRequestSignOut *self);

FOUNDATION_EXPORT ARRequestSignOut *new_ARRequestSignOut_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARRequestSignOut *create_ARRequestSignOut_init();

J2OBJC_TYPE_LITERAL_HEADER(ARRequestSignOut)

@compatibility_alias ImDiyalogCoreApiRpcRequestSignOut ARRequestSignOut;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcRequestSignOut")
