//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/api/rpc/RequestTerminateSession.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcRequestTerminateSession")
#ifdef RESTRICT_ImDiyalogCoreApiRpcRequestTerminateSession
#define INCLUDE_ALL_ImDiyalogCoreApiRpcRequestTerminateSession 0
#else
#define INCLUDE_ALL_ImDiyalogCoreApiRpcRequestTerminateSession 1
#endif
#undef RESTRICT_ImDiyalogCoreApiRpcRequestTerminateSession

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARRequestTerminateSession_) && (INCLUDE_ALL_ImDiyalogCoreApiRpcRequestTerminateSession || defined(INCLUDE_ARRequestTerminateSession))
#define ARRequestTerminateSession_

#define RESTRICT_ImDiyalogCoreNetworkParserRequest 1
#define INCLUDE_ACRequest 1
#include "../../../../../im/diyalog/core/network/parser/Request.h"

@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

@interface ARRequestTerminateSession : ACRequest

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithInt:(jint)id_;

+ (ARRequestTerminateSession *)fromBytesWithByteArray:(IOSByteArray *)data;

- (jint)getHeaderKey;

- (jint)getId;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARRequestTerminateSession)

inline jint ARRequestTerminateSession_get_HEADER();
#define ARRequestTerminateSession_HEADER 82
J2OBJC_STATIC_FIELD_CONSTANT(ARRequestTerminateSession, HEADER, jint)

FOUNDATION_EXPORT ARRequestTerminateSession *ARRequestTerminateSession_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARRequestTerminateSession_initWithInt_(ARRequestTerminateSession *self, jint id_);

FOUNDATION_EXPORT ARRequestTerminateSession *new_ARRequestTerminateSession_initWithInt_(jint id_) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARRequestTerminateSession *create_ARRequestTerminateSession_initWithInt_(jint id_);

FOUNDATION_EXPORT void ARRequestTerminateSession_init(ARRequestTerminateSession *self);

FOUNDATION_EXPORT ARRequestTerminateSession *new_ARRequestTerminateSession_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARRequestTerminateSession *create_ARRequestTerminateSession_init();

J2OBJC_TYPE_LITERAL_HEADER(ARRequestTerminateSession)

@compatibility_alias ImDiyalogCoreApiRpcRequestTerminateSession ARRequestTerminateSession;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcRequestTerminateSession")
