//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/api/rpc/RequestUpdateMessage.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcRequestUpdateMessage")
#ifdef RESTRICT_ImDiyalogCoreApiRpcRequestUpdateMessage
#define INCLUDE_ALL_ImDiyalogCoreApiRpcRequestUpdateMessage 0
#else
#define INCLUDE_ALL_ImDiyalogCoreApiRpcRequestUpdateMessage 1
#endif
#undef RESTRICT_ImDiyalogCoreApiRpcRequestUpdateMessage

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARRequestUpdateMessage_) && (INCLUDE_ALL_ImDiyalogCoreApiRpcRequestUpdateMessage || defined(INCLUDE_ARRequestUpdateMessage))
#define ARRequestUpdateMessage_

#define RESTRICT_ImDiyalogCoreNetworkParserRequest 1
#define INCLUDE_ACRequest 1
#include "../../../../../im/diyalog/core/network/parser/Request.h"

@class ARApiMessage;
@class ARApiOutPeer;
@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARRequestUpdateMessage : ACRequest

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithARApiOutPeer:(ARApiOutPeer * __nonnull)peer
                            withLong:(jlong)rid
                    withARApiMessage:(ARApiMessage * __nonnull)updatedMessage;

+ (ARRequestUpdateMessage *)fromBytesWithByteArray:(IOSByteArray *)data;

- (jint)getHeaderKey;

- (ARApiOutPeer * __nonnull)getPeer;

- (jlong)getRid;

- (ARApiMessage * __nonnull)getUpdatedMessage;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARRequestUpdateMessage)

inline jint ARRequestUpdateMessage_get_HEADER();
#define ARRequestUpdateMessage_HEADER 2658
J2OBJC_STATIC_FIELD_CONSTANT(ARRequestUpdateMessage, HEADER, jint)

FOUNDATION_EXPORT ARRequestUpdateMessage *ARRequestUpdateMessage_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARRequestUpdateMessage_initWithARApiOutPeer_withLong_withARApiMessage_(ARRequestUpdateMessage *self, ARApiOutPeer *peer, jlong rid, ARApiMessage *updatedMessage);

FOUNDATION_EXPORT ARRequestUpdateMessage *new_ARRequestUpdateMessage_initWithARApiOutPeer_withLong_withARApiMessage_(ARApiOutPeer *peer, jlong rid, ARApiMessage *updatedMessage) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARRequestUpdateMessage *create_ARRequestUpdateMessage_initWithARApiOutPeer_withLong_withARApiMessage_(ARApiOutPeer *peer, jlong rid, ARApiMessage *updatedMessage);

FOUNDATION_EXPORT void ARRequestUpdateMessage_init(ARRequestUpdateMessage *self);

FOUNDATION_EXPORT ARRequestUpdateMessage *new_ARRequestUpdateMessage_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARRequestUpdateMessage *create_ARRequestUpdateMessage_init();

J2OBJC_TYPE_LITERAL_HEADER(ARRequestUpdateMessage)

@compatibility_alias ImDiyalogCoreApiRpcRequestUpdateMessage ARRequestUpdateMessage;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcRequestUpdateMessage")
