//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/api/rpc/RequestSendCodeByPhoneCall.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcRequestSendCodeByPhoneCall")
#ifdef RESTRICT_ImDiyalogCoreApiRpcRequestSendCodeByPhoneCall
#define INCLUDE_ALL_ImDiyalogCoreApiRpcRequestSendCodeByPhoneCall 0
#else
#define INCLUDE_ALL_ImDiyalogCoreApiRpcRequestSendCodeByPhoneCall 1
#endif
#undef RESTRICT_ImDiyalogCoreApiRpcRequestSendCodeByPhoneCall

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARRequestSendCodeByPhoneCall_) && (INCLUDE_ALL_ImDiyalogCoreApiRpcRequestSendCodeByPhoneCall || defined(INCLUDE_ARRequestSendCodeByPhoneCall))
#define ARRequestSendCodeByPhoneCall_

#define RESTRICT_ImDiyalogCoreNetworkParserRequest 1
#define INCLUDE_ACRequest 1
#include "../../../../../im/diyalog/core/network/parser/Request.h"

@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARRequestSendCodeByPhoneCall : ACRequest

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString * __nonnull)transactionHash;

+ (ARRequestSendCodeByPhoneCall *)fromBytesWithByteArray:(IOSByteArray *)data;

- (jint)getHeaderKey;

- (NSString * __nonnull)getTransactionHash;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARRequestSendCodeByPhoneCall)

inline jint ARRequestSendCodeByPhoneCall_get_HEADER();
#define ARRequestSendCodeByPhoneCall_HEADER 197
J2OBJC_STATIC_FIELD_CONSTANT(ARRequestSendCodeByPhoneCall, HEADER, jint)

FOUNDATION_EXPORT ARRequestSendCodeByPhoneCall *ARRequestSendCodeByPhoneCall_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARRequestSendCodeByPhoneCall_initWithNSString_(ARRequestSendCodeByPhoneCall *self, NSString *transactionHash);

FOUNDATION_EXPORT ARRequestSendCodeByPhoneCall *new_ARRequestSendCodeByPhoneCall_initWithNSString_(NSString *transactionHash) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARRequestSendCodeByPhoneCall *create_ARRequestSendCodeByPhoneCall_initWithNSString_(NSString *transactionHash);

FOUNDATION_EXPORT void ARRequestSendCodeByPhoneCall_init(ARRequestSendCodeByPhoneCall *self);

FOUNDATION_EXPORT ARRequestSendCodeByPhoneCall *new_ARRequestSendCodeByPhoneCall_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARRequestSendCodeByPhoneCall *create_ARRequestSendCodeByPhoneCall_init();

J2OBJC_TYPE_LITERAL_HEADER(ARRequestSendCodeByPhoneCall)

@compatibility_alias ImDiyalogCoreApiRpcRequestSendCodeByPhoneCall ARRequestSendCodeByPhoneCall;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcRequestSendCodeByPhoneCall")
