//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/api/rpc/ResponseGetOAuth2Params.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcResponseGetOAuth2Params")
#ifdef RESTRICT_ImDiyalogCoreApiRpcResponseGetOAuth2Params
#define INCLUDE_ALL_ImDiyalogCoreApiRpcResponseGetOAuth2Params 0
#else
#define INCLUDE_ALL_ImDiyalogCoreApiRpcResponseGetOAuth2Params 1
#endif
#undef RESTRICT_ImDiyalogCoreApiRpcResponseGetOAuth2Params

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARResponseGetOAuth2Params_) && (INCLUDE_ALL_ImDiyalogCoreApiRpcResponseGetOAuth2Params || defined(INCLUDE_ARResponseGetOAuth2Params))
#define ARResponseGetOAuth2Params_

#define RESTRICT_ImDiyalogCoreNetworkParserResponse 1
#define INCLUDE_ACResponse 1
#include "../../../../../im/diyalog/core/network/parser/Response.h"

@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARResponseGetOAuth2Params : ACResponse

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString * __nonnull)authUrl;

+ (ARResponseGetOAuth2Params *)fromBytesWithByteArray:(IOSByteArray *)data;

- (NSString * __nonnull)getAuthUrl;

- (jint)getHeaderKey;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARResponseGetOAuth2Params)

inline jint ARResponseGetOAuth2Params_get_HEADER();
#define ARResponseGetOAuth2Params_HEADER 195
J2OBJC_STATIC_FIELD_CONSTANT(ARResponseGetOAuth2Params, HEADER, jint)

FOUNDATION_EXPORT ARResponseGetOAuth2Params *ARResponseGetOAuth2Params_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARResponseGetOAuth2Params_initWithNSString_(ARResponseGetOAuth2Params *self, NSString *authUrl);

FOUNDATION_EXPORT ARResponseGetOAuth2Params *new_ARResponseGetOAuth2Params_initWithNSString_(NSString *authUrl) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARResponseGetOAuth2Params *create_ARResponseGetOAuth2Params_initWithNSString_(NSString *authUrl);

FOUNDATION_EXPORT void ARResponseGetOAuth2Params_init(ARResponseGetOAuth2Params *self);

FOUNDATION_EXPORT ARResponseGetOAuth2Params *new_ARResponseGetOAuth2Params_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARResponseGetOAuth2Params *create_ARResponseGetOAuth2Params_init();

J2OBJC_TYPE_LITERAL_HEADER(ARResponseGetOAuth2Params)

@compatibility_alias ImDiyalogCoreApiRpcResponseGetOAuth2Params ARResponseGetOAuth2Params;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcResponseGetOAuth2Params")
