//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/api/rpc/ResponseMakeUserAdmin.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcResponseMakeUserAdmin")
#ifdef RESTRICT_ImDiyalogCoreApiRpcResponseMakeUserAdmin
#define INCLUDE_ALL_ImDiyalogCoreApiRpcResponseMakeUserAdmin 0
#else
#define INCLUDE_ALL_ImDiyalogCoreApiRpcResponseMakeUserAdmin 1
#endif
#undef RESTRICT_ImDiyalogCoreApiRpcResponseMakeUserAdmin

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARResponseMakeUserAdmin_) && (INCLUDE_ALL_ImDiyalogCoreApiRpcResponseMakeUserAdmin || defined(INCLUDE_ARResponseMakeUserAdmin))
#define ARResponseMakeUserAdmin_

#define RESTRICT_ImDiyalogCoreNetworkParserResponse 1
#define INCLUDE_ACResponse 1
#include "../../../../../im/diyalog/core/network/parser/Response.h"

@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;
@protocol JavaUtilList;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARResponseMakeUserAdmin : ACResponse

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithJavaUtilList:(id<JavaUtilList> __nonnull)members
                             withInt:(jint)seq
                       withByteArray:(IOSByteArray * __nonnull)state;

+ (ARResponseMakeUserAdmin *)fromBytesWithByteArray:(IOSByteArray *)data;

- (jint)getHeaderKey;

- (id<JavaUtilList> __nonnull)getMembers;

- (jint)getSeq;

- (IOSByteArray * __nonnull)getState;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARResponseMakeUserAdmin)

inline jint ARResponseMakeUserAdmin_get_HEADER();
#define ARResponseMakeUserAdmin_HEADER 215
J2OBJC_STATIC_FIELD_CONSTANT(ARResponseMakeUserAdmin, HEADER, jint)

FOUNDATION_EXPORT ARResponseMakeUserAdmin *ARResponseMakeUserAdmin_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARResponseMakeUserAdmin_initWithJavaUtilList_withInt_withByteArray_(ARResponseMakeUserAdmin *self, id<JavaUtilList> members, jint seq, IOSByteArray *state);

FOUNDATION_EXPORT ARResponseMakeUserAdmin *new_ARResponseMakeUserAdmin_initWithJavaUtilList_withInt_withByteArray_(id<JavaUtilList> members, jint seq, IOSByteArray *state) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARResponseMakeUserAdmin *create_ARResponseMakeUserAdmin_initWithJavaUtilList_withInt_withByteArray_(id<JavaUtilList> members, jint seq, IOSByteArray *state);

FOUNDATION_EXPORT void ARResponseMakeUserAdmin_init(ARResponseMakeUserAdmin *self);

FOUNDATION_EXPORT ARResponseMakeUserAdmin *new_ARResponseMakeUserAdmin_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARResponseMakeUserAdmin *create_ARResponseMakeUserAdmin_init();

J2OBJC_TYPE_LITERAL_HEADER(ARResponseMakeUserAdmin)

@compatibility_alias ImDiyalogCoreApiRpcResponseMakeUserAdmin ARResponseMakeUserAdmin;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcResponseMakeUserAdmin")
