//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/api/rpc/ResponsePeerSearch.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcResponsePeerSearch")
#ifdef RESTRICT_ImDiyalogCoreApiRpcResponsePeerSearch
#define INCLUDE_ALL_ImDiyalogCoreApiRpcResponsePeerSearch 0
#else
#define INCLUDE_ALL_ImDiyalogCoreApiRpcResponsePeerSearch 1
#endif
#undef RESTRICT_ImDiyalogCoreApiRpcResponsePeerSearch

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARResponsePeerSearch_) && (INCLUDE_ALL_ImDiyalogCoreApiRpcResponsePeerSearch || defined(INCLUDE_ARResponsePeerSearch))
#define ARResponsePeerSearch_

#define RESTRICT_ImDiyalogCoreNetworkParserResponse 1
#define INCLUDE_ACResponse 1
#include "../../../../../im/diyalog/core/network/parser/Response.h"

@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;
@protocol JavaUtilList;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARResponsePeerSearch : ACResponse

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithJavaUtilList:(id<JavaUtilList> __nonnull)searchResults
                    withJavaUtilList:(id<JavaUtilList> __nonnull)users
                    withJavaUtilList:(id<JavaUtilList> __nonnull)groups;

+ (ARResponsePeerSearch *)fromBytesWithByteArray:(IOSByteArray *)data;

- (id<JavaUtilList> __nonnull)getGroups;

- (jint)getHeaderKey;

- (id<JavaUtilList> __nonnull)getSearchResults;

- (id<JavaUtilList> __nonnull)getUsers;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARResponsePeerSearch)

inline jint ARResponsePeerSearch_get_HEADER();
#define ARResponsePeerSearch_HEADER 234
J2OBJC_STATIC_FIELD_CONSTANT(ARResponsePeerSearch, HEADER, jint)

FOUNDATION_EXPORT ARResponsePeerSearch *ARResponsePeerSearch_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARResponsePeerSearch_initWithJavaUtilList_withJavaUtilList_withJavaUtilList_(ARResponsePeerSearch *self, id<JavaUtilList> searchResults, id<JavaUtilList> users, id<JavaUtilList> groups);

FOUNDATION_EXPORT ARResponsePeerSearch *new_ARResponsePeerSearch_initWithJavaUtilList_withJavaUtilList_withJavaUtilList_(id<JavaUtilList> searchResults, id<JavaUtilList> users, id<JavaUtilList> groups) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARResponsePeerSearch *create_ARResponsePeerSearch_initWithJavaUtilList_withJavaUtilList_withJavaUtilList_(id<JavaUtilList> searchResults, id<JavaUtilList> users, id<JavaUtilList> groups);

FOUNDATION_EXPORT void ARResponsePeerSearch_init(ARResponsePeerSearch *self);

FOUNDATION_EXPORT ARResponsePeerSearch *new_ARResponsePeerSearch_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARResponsePeerSearch *create_ARResponsePeerSearch_init();

J2OBJC_TYPE_LITERAL_HEADER(ARResponsePeerSearch)

@compatibility_alias ImDiyalogCoreApiRpcResponsePeerSearch ARResponsePeerSearch;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcResponsePeerSearch")
