//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/api/rpc/ResponseBool.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcResponseBool")
#ifdef RESTRICT_ImDiyalogCoreApiRpcResponseBool
#define INCLUDE_ALL_ImDiyalogCoreApiRpcResponseBool 0
#else
#define INCLUDE_ALL_ImDiyalogCoreApiRpcResponseBool 1
#endif
#undef RESTRICT_ImDiyalogCoreApiRpcResponseBool

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARResponseBool_) && (INCLUDE_ALL_ImDiyalogCoreApiRpcResponseBool || defined(INCLUDE_ARResponseBool))
#define ARResponseBool_

#define RESTRICT_ImDiyalogCoreNetworkParserResponse 1
#define INCLUDE_ACResponse 1
#include "../../../../../im/diyalog/core/network/parser/Response.h"

@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

@interface ARResponseBool : ACResponse

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithBoolean:(jboolean)value;

+ (ARResponseBool *)fromBytesWithByteArray:(IOSByteArray *)data;

- (jint)getHeaderKey;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

- (jboolean)value;

@end

J2OBJC_EMPTY_STATIC_INIT(ARResponseBool)

inline jint ARResponseBool_get_HEADER();
#define ARResponseBool_HEADER 209
J2OBJC_STATIC_FIELD_CONSTANT(ARResponseBool, HEADER, jint)

FOUNDATION_EXPORT ARResponseBool *ARResponseBool_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARResponseBool_initWithBoolean_(ARResponseBool *self, jboolean value);

FOUNDATION_EXPORT ARResponseBool *new_ARResponseBool_initWithBoolean_(jboolean value) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARResponseBool *create_ARResponseBool_initWithBoolean_(jboolean value);

FOUNDATION_EXPORT void ARResponseBool_init(ARResponseBool *self);

FOUNDATION_EXPORT ARResponseBool *new_ARResponseBool_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARResponseBool *create_ARResponseBool_init();

J2OBJC_TYPE_LITERAL_HEADER(ARResponseBool)

@compatibility_alias ImDiyalogCoreApiRpcResponseBool ARResponseBool;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreApiRpcResponseBool")
