//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/runtime/runtime-shared/src/main/java/im/diyalog/runtime/crypto/ratchet/RatchetRootChainKey.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogRuntimeCryptoRatchetRatchetRootChainKey")
#ifdef RESTRICT_ImDiyalogRuntimeCryptoRatchetRatchetRootChainKey
#define INCLUDE_ALL_ImDiyalogRuntimeCryptoRatchetRatchetRootChainKey 0
#else
#define INCLUDE_ALL_ImDiyalogRuntimeCryptoRatchetRatchetRootChainKey 1
#endif
#undef RESTRICT_ImDiyalogRuntimeCryptoRatchetRatchetRootChainKey

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImDiyalogRuntimeCryptoRatchetRatchetRootChainKey_) && (INCLUDE_ALL_ImDiyalogRuntimeCryptoRatchetRatchetRootChainKey || defined(INCLUDE_ImDiyalogRuntimeCryptoRatchetRatchetRootChainKey))
#define ImDiyalogRuntimeCryptoRatchetRatchetRootChainKey_

@class IOSByteArray;
@class ImDiyalogRuntimeCryptoRatchetRatchetPrivateKey;
@class ImDiyalogRuntimeCryptoRatchetRatchetPublicKey;

@interface ImDiyalogRuntimeCryptoRatchetRatchetRootChainKey : NSObject

#pragma mark Public

- (instancetype)init;

+ (IOSByteArray *)makeRootChainKeyWithImDiyalogRuntimeCryptoRatchetRatchetPrivateKey:(ImDiyalogRuntimeCryptoRatchetRatchetPrivateKey *)ownEphermal
                                   withImDiyalogRuntimeCryptoRatchetRatchetPublicKey:(ImDiyalogRuntimeCryptoRatchetRatchetPublicKey *)theirEphermal
                                                                       withByteArray:(IOSByteArray *)masterSecret;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogRuntimeCryptoRatchetRatchetRootChainKey)

FOUNDATION_EXPORT IOSByteArray *ImDiyalogRuntimeCryptoRatchetRatchetRootChainKey_makeRootChainKeyWithImDiyalogRuntimeCryptoRatchetRatchetPrivateKey_withImDiyalogRuntimeCryptoRatchetRatchetPublicKey_withByteArray_(ImDiyalogRuntimeCryptoRatchetRatchetPrivateKey *ownEphermal, ImDiyalogRuntimeCryptoRatchetRatchetPublicKey *theirEphermal, IOSByteArray *masterSecret);

FOUNDATION_EXPORT void ImDiyalogRuntimeCryptoRatchetRatchetRootChainKey_init(ImDiyalogRuntimeCryptoRatchetRatchetRootChainKey *self);

FOUNDATION_EXPORT ImDiyalogRuntimeCryptoRatchetRatchetRootChainKey *new_ImDiyalogRuntimeCryptoRatchetRatchetRootChainKey_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogRuntimeCryptoRatchetRatchetRootChainKey *create_ImDiyalogRuntimeCryptoRatchetRatchetRootChainKey_init();

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogRuntimeCryptoRatchetRatchetRootChainKey)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogRuntimeCryptoRatchetRatchetRootChainKey")
