//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/api/updates/UpdateSynedSetUpdated.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreApiUpdatesUpdateSynedSetUpdated")
#ifdef RESTRICT_ImDiyalogCoreApiUpdatesUpdateSynedSetUpdated
#define INCLUDE_ALL_ImDiyalogCoreApiUpdatesUpdateSynedSetUpdated 0
#else
#define INCLUDE_ALL_ImDiyalogCoreApiUpdatesUpdateSynedSetUpdated 1
#endif
#undef RESTRICT_ImDiyalogCoreApiUpdatesUpdateSynedSetUpdated

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARUpdateSynedSetUpdated_) && (INCLUDE_ALL_ImDiyalogCoreApiUpdatesUpdateSynedSetUpdated || defined(INCLUDE_ARUpdateSynedSetUpdated))
#define ARUpdateSynedSetUpdated_

#define RESTRICT_ImDiyalogCoreNetworkParserUpdate 1
#define INCLUDE_ACUpdate 1
#include "../../../../../im/diyalog/core/network/parser/Update.h"

@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;
@class JavaLangBoolean;
@protocol JavaUtilList;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARUpdateSynedSetUpdated : ACUpdate

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString * __nonnull)setName
                withJavaUtilList:(id<JavaUtilList> __nonnull)syncedValues
             withJavaLangBoolean:(JavaLangBoolean * __nullable)isStrong;

+ (ARUpdateSynedSetUpdated *)fromBytesWithByteArray:(IOSByteArray *)data;

- (jint)getHeaderKey;

- (NSString * __nonnull)getSetName;

- (id<JavaUtilList> __nonnull)getSyncedValues;

- (JavaLangBoolean * __nullable)isStrong;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARUpdateSynedSetUpdated)

inline jint ARUpdateSynedSetUpdated_get_HEADER();
#define ARUpdateSynedSetUpdated_HEADER 72
J2OBJC_STATIC_FIELD_CONSTANT(ARUpdateSynedSetUpdated, HEADER, jint)

FOUNDATION_EXPORT ARUpdateSynedSetUpdated *ARUpdateSynedSetUpdated_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARUpdateSynedSetUpdated_initWithNSString_withJavaUtilList_withJavaLangBoolean_(ARUpdateSynedSetUpdated *self, NSString *setName, id<JavaUtilList> syncedValues, JavaLangBoolean *isStrong);

FOUNDATION_EXPORT ARUpdateSynedSetUpdated *new_ARUpdateSynedSetUpdated_initWithNSString_withJavaUtilList_withJavaLangBoolean_(NSString *setName, id<JavaUtilList> syncedValues, JavaLangBoolean *isStrong) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARUpdateSynedSetUpdated *create_ARUpdateSynedSetUpdated_initWithNSString_withJavaUtilList_withJavaLangBoolean_(NSString *setName, id<JavaUtilList> syncedValues, JavaLangBoolean *isStrong);

FOUNDATION_EXPORT void ARUpdateSynedSetUpdated_init(ARUpdateSynedSetUpdated *self);

FOUNDATION_EXPORT ARUpdateSynedSetUpdated *new_ARUpdateSynedSetUpdated_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARUpdateSynedSetUpdated *create_ARUpdateSynedSetUpdated_init();

J2OBJC_TYPE_LITERAL_HEADER(ARUpdateSynedSetUpdated)

@compatibility_alias ImDiyalogCoreApiUpdatesUpdateSynedSetUpdated ARUpdateSynedSetUpdated;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreApiUpdatesUpdateSynedSetUpdated")
