//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/api/updates/UpdateCallHandled.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreApiUpdatesUpdateCallHandled")
#ifdef RESTRICT_ImDiyalogCoreApiUpdatesUpdateCallHandled
#define INCLUDE_ALL_ImDiyalogCoreApiUpdatesUpdateCallHandled 0
#else
#define INCLUDE_ALL_ImDiyalogCoreApiUpdatesUpdateCallHandled 1
#endif
#undef RESTRICT_ImDiyalogCoreApiUpdatesUpdateCallHandled

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARUpdateCallHandled_) && (INCLUDE_ALL_ImDiyalogCoreApiUpdatesUpdateCallHandled || defined(INCLUDE_ARUpdateCallHandled))
#define ARUpdateCallHandled_

#define RESTRICT_ImDiyalogCoreNetworkParserUpdate 1
#define INCLUDE_ACUpdate 1
#include "../../../../../im/diyalog/core/network/parser/Update.h"

@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;
@class JavaLangInteger;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARUpdateCallHandled : ACUpdate

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithLong:(jlong)callId
         withJavaLangInteger:(JavaLangInteger * __nullable)attemptIndex;

+ (ARUpdateCallHandled *)fromBytesWithByteArray:(IOSByteArray *)data;

- (JavaLangInteger * __nullable)getAttemptIndex;

- (jlong)getCallId;

- (jint)getHeaderKey;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARUpdateCallHandled)

inline jint ARUpdateCallHandled_get_HEADER();
#define ARUpdateCallHandled_HEADER 53
J2OBJC_STATIC_FIELD_CONSTANT(ARUpdateCallHandled, HEADER, jint)

FOUNDATION_EXPORT ARUpdateCallHandled *ARUpdateCallHandled_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARUpdateCallHandled_initWithLong_withJavaLangInteger_(ARUpdateCallHandled *self, jlong callId, JavaLangInteger *attemptIndex);

FOUNDATION_EXPORT ARUpdateCallHandled *new_ARUpdateCallHandled_initWithLong_withJavaLangInteger_(jlong callId, JavaLangInteger *attemptIndex) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARUpdateCallHandled *create_ARUpdateCallHandled_initWithLong_withJavaLangInteger_(jlong callId, JavaLangInteger *attemptIndex);

FOUNDATION_EXPORT void ARUpdateCallHandled_init(ARUpdateCallHandled *self);

FOUNDATION_EXPORT ARUpdateCallHandled *new_ARUpdateCallHandled_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARUpdateCallHandled *create_ARUpdateCallHandled_init();

J2OBJC_TYPE_LITERAL_HEADER(ARUpdateCallHandled)

@compatibility_alias ImDiyalogCoreApiUpdatesUpdateCallHandled ARUpdateCallHandled;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreApiUpdatesUpdateCallHandled")
