//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/modules/settings/SettingsModule.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreModulesSettingsSettingsModule")
#ifdef RESTRICT_ImDiyalogCoreModulesSettingsSettingsModule
#define INCLUDE_ALL_ImDiyalogCoreModulesSettingsSettingsModule 0
#else
#define INCLUDE_ALL_ImDiyalogCoreModulesSettingsSettingsModule 1
#endif
#undef RESTRICT_ImDiyalogCoreModulesSettingsSettingsModule

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImDiyalogCoreModulesSettingsSettingsModule_) && (INCLUDE_ALL_ImDiyalogCoreModulesSettingsSettingsModule || defined(INCLUDE_ImDiyalogCoreModulesSettingsSettingsModule))
#define ImDiyalogCoreModulesSettingsSettingsModule_

#define RESTRICT_ImDiyalogCoreModulesAbsModule 1
#define INCLUDE_ACAbsModule 1
#include "../../../../../im/diyalog/core/modules/AbsModule.h"

@class ACPeer;
@protocol ACModuleContext;

@interface ImDiyalogCoreModulesSettingsSettingsModule : ACAbsModule

#pragma mark Public

- (instancetype)initWithACModuleContext:(id<ACModuleContext>)context;

- (void)changeConversationTonesEnabledWithBoolean:(jboolean)val;

- (void)changeGroupNotificationsEnabledWithBoolean:(jboolean)val;

- (void)changeGroupNotificationsOnlyMentionsEnabledWithBoolean:(jboolean)val;

- (void)changeInAppEnabledWithBoolean:(jboolean)val;

- (void)changeInAppSoundEnabledWithBoolean:(jboolean)val;

- (void)changeInAppVibrationEnabledWithBoolean:(jboolean)val;

- (void)changeMarkdownWithBoolean:(jboolean)val;

- (void)changeNotificationsEnabledWithBoolean:(jboolean)val;

- (void)changeNotificationsEnabledWithACPeer:(ACPeer *)peer
                                 withBoolean:(jboolean)val;

- (void)changeNotificationSoundWithACPeer:(ACPeer *)peer
                             withNSString:(NSString *)sound;

- (void)changeNotificationSoundWithNSString:(NSString *)sound;

- (void)changeNotificationSoundEnabledWithBoolean:(jboolean)val;

- (void)changeNotificationVibrationEnabledWithBoolean:(jboolean)val;

- (void)changeOutOfOfficeWithBoolean:(jboolean)val;

- (void)changeSelectedWallpapperWithNSString:(NSString *)uri;

- (void)changeSendByEnterWithBoolean:(jboolean)val;

- (void)changeShowNotificationTextEnabledWithBoolean:(jboolean)val;

- (void)changeTextSizeWithInt:(jint)textSize;

- (jboolean)getBooleanValueWithNSString:(NSString *)key;

- (jboolean)getBooleanValueWithNSString:(NSString *)key
                            withBoolean:(jboolean)defaultVal;

- (NSString *)getNotificationSound;

- (NSString *)getNotificationSoundWithACPeer:(ACPeer *)peer;

- (NSString *)getPrivacy;

- (NSString *)getSelectedWallpapper;

- (NSString *)getStringValueWithNSString:(NSString *)key;

- (NSString *)getStringValueWithNSString:(NSString *)key
                            withNSString:(NSString *)defaultVal;

- (jint)getTextSize;

- (jboolean)isConversationTonesEnabled;

- (jboolean)isGroupNotificationsEnabled;

- (jboolean)isGroupNotificationsOnlyMentionsEnabled;

- (jboolean)isInAppEnabled;

- (jboolean)isInAppSoundEnabled;

- (jboolean)isInAppVibrationEnabled;

- (jboolean)isMarkdownEnabled;

- (jboolean)isNotificationsEnabled;

- (jboolean)isNotificationsEnabledWithACPeer:(ACPeer *)peer;

- (jboolean)isNotificationSoundEnabled;

- (jboolean)isOutOfOfficeEnabled;

- (jboolean)isRenameHintShown;

- (jboolean)isSendByEnterEnabled;

- (jboolean)isShowNotificationsText;

- (jboolean)isVibrationEnabled;

- (void)onUpdatedSettingWithNSString:(NSString *)key
                        withNSString:(NSString *)value;

- (void)resetModule;

- (void)run;

- (void)setBooleanValueWithNSString:(NSString *)key
                        withBoolean:(jboolean)val;

- (void)setPrivacyWithNSString:(NSString *)privacy;

- (void)setStringValueWithNSString:(NSString *)key
                      withNSString:(NSString *)val;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogCoreModulesSettingsSettingsModule)

FOUNDATION_EXPORT void ImDiyalogCoreModulesSettingsSettingsModule_initWithACModuleContext_(ImDiyalogCoreModulesSettingsSettingsModule *self, id<ACModuleContext> context);

FOUNDATION_EXPORT ImDiyalogCoreModulesSettingsSettingsModule *new_ImDiyalogCoreModulesSettingsSettingsModule_initWithACModuleContext_(id<ACModuleContext> context) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogCoreModulesSettingsSettingsModule *create_ImDiyalogCoreModulesSettingsSettingsModule_initWithACModuleContext_(id<ACModuleContext> context);

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogCoreModulesSettingsSettingsModule)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreModulesSettingsSettingsModule")
