//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/runtime/runtime-shared/src/main/java/im/diyalog/runtime/crypto/primitives/curve25519/fe_0.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogRuntimeCryptoPrimitivesCurve25519Fe_0")
#ifdef RESTRICT_ImDiyalogRuntimeCryptoPrimitivesCurve25519Fe_0
#define INCLUDE_ALL_ImDiyalogRuntimeCryptoPrimitivesCurve25519Fe_0 0
#else
#define INCLUDE_ALL_ImDiyalogRuntimeCryptoPrimitivesCurve25519Fe_0 1
#endif
#undef RESTRICT_ImDiyalogRuntimeCryptoPrimitivesCurve25519Fe_0

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImDiyalogRuntimeCryptoPrimitivesCurve25519fe_0_) && (INCLUDE_ALL_ImDiyalogRuntimeCryptoPrimitivesCurve25519Fe_0 || defined(INCLUDE_ImDiyalogRuntimeCryptoPrimitivesCurve25519fe_0))
#define ImDiyalogRuntimeCryptoPrimitivesCurve25519fe_0_

@class IOSIntArray;

@interface ImDiyalogRuntimeCryptoPrimitivesCurve25519fe_0 : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)fe_0WithIntArray:(IOSIntArray *)h;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogRuntimeCryptoPrimitivesCurve25519fe_0)

FOUNDATION_EXPORT void ImDiyalogRuntimeCryptoPrimitivesCurve25519fe_0_fe_0WithIntArray_(IOSIntArray *h);

FOUNDATION_EXPORT void ImDiyalogRuntimeCryptoPrimitivesCurve25519fe_0_init(ImDiyalogRuntimeCryptoPrimitivesCurve25519fe_0 *self);

FOUNDATION_EXPORT ImDiyalogRuntimeCryptoPrimitivesCurve25519fe_0 *new_ImDiyalogRuntimeCryptoPrimitivesCurve25519fe_0_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogRuntimeCryptoPrimitivesCurve25519fe_0 *create_ImDiyalogRuntimeCryptoPrimitivesCurve25519fe_0_init();

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogRuntimeCryptoPrimitivesCurve25519fe_0)

@compatibility_alias ImDiyalogRuntimeCryptoPrimitivesCurve25519Fe_0 ImDiyalogRuntimeCryptoPrimitivesCurve25519fe_0;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogRuntimeCryptoPrimitivesCurve25519Fe_0")
