//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/runtime/runtime-shared/src/main/java/im/diyalog/runtime/crypto/primitives/curve25519/scalarmult.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogRuntimeCryptoPrimitivesCurve25519Scalarmult")
#ifdef RESTRICT_ImDiyalogRuntimeCryptoPrimitivesCurve25519Scalarmult
#define INCLUDE_ALL_ImDiyalogRuntimeCryptoPrimitivesCurve25519Scalarmult 0
#else
#define INCLUDE_ALL_ImDiyalogRuntimeCryptoPrimitivesCurve25519Scalarmult 1
#endif
#undef RESTRICT_ImDiyalogRuntimeCryptoPrimitivesCurve25519Scalarmult

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImDiyalogRuntimeCryptoPrimitivesCurve25519scalarmult_) && (INCLUDE_ALL_ImDiyalogRuntimeCryptoPrimitivesCurve25519Scalarmult || defined(INCLUDE_ImDiyalogRuntimeCryptoPrimitivesCurve25519scalarmult))
#define ImDiyalogRuntimeCryptoPrimitivesCurve25519scalarmult_

@class IOSByteArray;

@interface ImDiyalogRuntimeCryptoPrimitivesCurve25519scalarmult : NSObject

#pragma mark Public

- (instancetype)init;

+ (jint)crypto_scalarmultWithByteArray:(IOSByteArray *)q
                         withByteArray:(IOSByteArray *)n
                         withByteArray:(IOSByteArray *)p;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogRuntimeCryptoPrimitivesCurve25519scalarmult)

FOUNDATION_EXPORT jint ImDiyalogRuntimeCryptoPrimitivesCurve25519scalarmult_crypto_scalarmultWithByteArray_withByteArray_withByteArray_(IOSByteArray *q, IOSByteArray *n, IOSByteArray *p);

FOUNDATION_EXPORT void ImDiyalogRuntimeCryptoPrimitivesCurve25519scalarmult_init(ImDiyalogRuntimeCryptoPrimitivesCurve25519scalarmult *self);

FOUNDATION_EXPORT ImDiyalogRuntimeCryptoPrimitivesCurve25519scalarmult *new_ImDiyalogRuntimeCryptoPrimitivesCurve25519scalarmult_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogRuntimeCryptoPrimitivesCurve25519scalarmult *create_ImDiyalogRuntimeCryptoPrimitivesCurve25519scalarmult_init();

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogRuntimeCryptoPrimitivesCurve25519scalarmult)

@compatibility_alias ImDiyalogRuntimeCryptoPrimitivesCurve25519Scalarmult ImDiyalogRuntimeCryptoPrimitivesCurve25519scalarmult;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogRuntimeCryptoPrimitivesCurve25519Scalarmult")
