//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/runtime/runtime-shared/src/main/java/im/diyalog/runtime/markdown/MDSpan.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogRuntimeMarkdownMDSpan")
#ifdef RESTRICT_ImDiyalogRuntimeMarkdownMDSpan
#define INCLUDE_ALL_ImDiyalogRuntimeMarkdownMDSpan 0
#else
#define INCLUDE_ALL_ImDiyalogRuntimeMarkdownMDSpan 1
#endif
#undef RESTRICT_ImDiyalogRuntimeMarkdownMDSpan

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARMDSpan_) && (INCLUDE_ALL_ImDiyalogRuntimeMarkdownMDSpan || defined(INCLUDE_ARMDSpan))
#define ARMDSpan_

#define RESTRICT_ImDiyalogRuntimeMarkdownMDText 1
#define INCLUDE_ARMDText 1
#include "../../../../im/diyalog/runtime/markdown/MDText.h"

@class IOSObjectArray;

@interface ARMDSpan : ARMDText

+ (jint)TYPE_BOLD;

+ (jint)TYPE_ITALIC;

+ (jint)TYPE_URL;

#pragma mark Public

- (instancetype)initWithInt:(jint)spanType
          withARMDTextArray:(IOSObjectArray *)child;

- (IOSObjectArray *)getChild;

- (jint)getSpanType;

- (NSString *)toMarkdown;

@end

J2OBJC_EMPTY_STATIC_INIT(ARMDSpan)

inline jint ARMDSpan_get_TYPE_BOLD();
#define ARMDSpan_TYPE_BOLD 0
J2OBJC_STATIC_FIELD_CONSTANT(ARMDSpan, TYPE_BOLD, jint)

inline jint ARMDSpan_get_TYPE_ITALIC();
#define ARMDSpan_TYPE_ITALIC 1
J2OBJC_STATIC_FIELD_CONSTANT(ARMDSpan, TYPE_ITALIC, jint)

inline jint ARMDSpan_get_TYPE_URL();
#define ARMDSpan_TYPE_URL 2
J2OBJC_STATIC_FIELD_CONSTANT(ARMDSpan, TYPE_URL, jint)

FOUNDATION_EXPORT void ARMDSpan_initWithInt_withARMDTextArray_(ARMDSpan *self, jint spanType, IOSObjectArray *child);

FOUNDATION_EXPORT ARMDSpan *new_ARMDSpan_initWithInt_withARMDTextArray_(jint spanType, IOSObjectArray *child) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARMDSpan *create_ARMDSpan_initWithInt_withARMDTextArray_(jint spanType, IOSObjectArray *child);

J2OBJC_TYPE_LITERAL_HEADER(ARMDSpan)

@compatibility_alias ImDiyalogRuntimeMarkdownMDSpan ARMDSpan;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogRuntimeMarkdownMDSpan")
