//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/runtime/runtime-shared/src/main/java/im/diyalog/runtime/bser/DataOutput.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogRuntimeBserDataOutput")
#ifdef RESTRICT_ImDiyalogRuntimeBserDataOutput
#define INCLUDE_ALL_ImDiyalogRuntimeBserDataOutput 0
#else
#define INCLUDE_ALL_ImDiyalogRuntimeBserDataOutput 1
#endif
#undef RESTRICT_ImDiyalogRuntimeBserDataOutput

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARDataOutput_) && (INCLUDE_ALL_ImDiyalogRuntimeBserDataOutput || defined(INCLUDE_ARDataOutput))
#define ARDataOutput_

@class IOSByteArray;
@class IOSLongArray;

@interface ARDataOutput : NSObject

#pragma mark Public

- (instancetype)init;

+ (jint)growSizeWithInt:(jint)currentSize;

- (IOSByteArray *)toByteArray;

- (void)writeASN1LengthWithInt:(jint)length;

- (void)writeByteWithByte:(jbyte)v;

- (void)writeByteWithInt:(jint)v;

- (void)writeBytesWithByteArray:(IOSByteArray *)v;

- (void)writeBytesWithByteArray:(IOSByteArray *)v
                        withInt:(jint)ofs
                        withInt:(jint)len;

- (void)writeIntWithInt:(jint)v;

- (void)writeLongWithLong:(jlong)v;

- (void)writeProtoBoolWithBoolean:(jboolean)v;

- (void)writeProtoBytesWithByteArray:(IOSByteArray *)v
                             withInt:(jint)ofs
                             withInt:(jint)len;

- (void)writeProtoLongsWithLongArray:(IOSLongArray *)values;

- (void)writeProtoStringWithNSString:(NSString *)value;

- (void)writeVarIntWithLong:(jlong)v;

@end

J2OBJC_EMPTY_STATIC_INIT(ARDataOutput)

FOUNDATION_EXPORT void ARDataOutput_init(ARDataOutput *self);

FOUNDATION_EXPORT ARDataOutput *new_ARDataOutput_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARDataOutput *create_ARDataOutput_init();

FOUNDATION_EXPORT jint ARDataOutput_growSizeWithInt_(jint currentSize);

J2OBJC_TYPE_LITERAL_HEADER(ARDataOutput)

@compatibility_alias ImDiyalogRuntimeBserDataOutput ARDataOutput;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogRuntimeBserDataOutput")
