//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/runtime/runtime-cocoa/src/main/java/im/diyalog/runtime/cocoa/CocoaNetworkProxyProvider.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogRuntimeCocoaCocoaNetworkProxyProvider")
#ifdef RESTRICT_ImDiyalogRuntimeCocoaCocoaNetworkProxyProvider
#define INCLUDE_ALL_ImDiyalogRuntimeCocoaCocoaNetworkProxyProvider 0
#else
#define INCLUDE_ALL_ImDiyalogRuntimeCocoaCocoaNetworkProxyProvider 1
#endif
#undef RESTRICT_ImDiyalogRuntimeCocoaCocoaNetworkProxyProvider

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARCocoaNetworkProxyProvider_) && (INCLUDE_ALL_ImDiyalogRuntimeCocoaCocoaNetworkProxyProvider || defined(INCLUDE_ARCocoaNetworkProxyProvider))
#define ARCocoaNetworkProxyProvider_

#define RESTRICT_ImDiyalogRuntimeNetworkRuntime 1
#define INCLUDE_ARNetworkRuntime 1
#include "../../../../im/diyalog/runtime/NetworkRuntime.h"

@class ARConnectionEndpoint;
@protocol ARConnectionCallback;
@protocol ARCreateConnectionCallback;

@interface ARCocoaNetworkProxyProvider : NSObject < ARNetworkRuntime >

#pragma mark Public

- (instancetype)init;

- (void)createConnectionWithId:(jint)connectionId
                 withMTVersion:(jint)mtprotoVersion
                  withApiMajor:(jint)apiMajorVersion
                  withApiMinor:(jint)apiMinorVersion
                  withEndpoint:(ARConnectionEndpoint *)endpoint
                  withCallback:(id<ARConnectionCallback>)callback
            withCreateCallback:(id<ARCreateConnectionCallback>)createCallback;

+ (void)setNetworkRuntime:(id<ARNetworkRuntime>)networkRuntime;

@end

J2OBJC_EMPTY_STATIC_INIT(ARCocoaNetworkProxyProvider)

FOUNDATION_EXPORT void ARCocoaNetworkProxyProvider_setNetworkRuntime_(id<ARNetworkRuntime> networkRuntime);

FOUNDATION_EXPORT void ARCocoaNetworkProxyProvider_init(ARCocoaNetworkProxyProvider *self);

FOUNDATION_EXPORT ARCocoaNetworkProxyProvider *new_ARCocoaNetworkProxyProvider_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARCocoaNetworkProxyProvider *create_ARCocoaNetworkProxyProvider_init();

J2OBJC_TYPE_LITERAL_HEADER(ARCocoaNetworkProxyProvider)

@compatibility_alias ImDiyalogRuntimeCocoaCocoaNetworkProxyProvider ARCocoaNetworkProxyProvider;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogRuntimeCocoaCocoaNetworkProxyProvider")
