//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/modules/messaging/actors/entity/PendingMessagesStorage.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreModulesMessagingActorsEntityPendingMessagesStorage")
#ifdef RESTRICT_ImDiyalogCoreModulesMessagingActorsEntityPendingMessagesStorage
#define INCLUDE_ALL_ImDiyalogCoreModulesMessagingActorsEntityPendingMessagesStorage 0
#else
#define INCLUDE_ALL_ImDiyalogCoreModulesMessagingActorsEntityPendingMessagesStorage 1
#endif
#undef RESTRICT_ImDiyalogCoreModulesMessagingActorsEntityPendingMessagesStorage

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImDiyalogCoreModulesMessagingActorsEntityPendingMessagesStorage_) && (INCLUDE_ALL_ImDiyalogCoreModulesMessagingActorsEntityPendingMessagesStorage || defined(INCLUDE_ImDiyalogCoreModulesMessagingActorsEntityPendingMessagesStorage))
#define ImDiyalogCoreModulesMessagingActorsEntityPendingMessagesStorage_

#define RESTRICT_ImDiyalogRuntimeBserBserObject 1
#define INCLUDE_ARBserObject 1
#include "../../../../../../../im/diyalog/runtime/bser/BserObject.h"

@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;
@class JavaUtilArrayList;

@interface ImDiyalogCoreModulesMessagingActorsEntityPendingMessagesStorage : ARBserObject

#pragma mark Public

- (instancetype)init;

+ (ImDiyalogCoreModulesMessagingActorsEntityPendingMessagesStorage *)fromBytesWithByteArray:(IOSByteArray *)data;

- (JavaUtilArrayList *)getPendingMessages;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogCoreModulesMessagingActorsEntityPendingMessagesStorage)

FOUNDATION_EXPORT ImDiyalogCoreModulesMessagingActorsEntityPendingMessagesStorage *ImDiyalogCoreModulesMessagingActorsEntityPendingMessagesStorage_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ImDiyalogCoreModulesMessagingActorsEntityPendingMessagesStorage_init(ImDiyalogCoreModulesMessagingActorsEntityPendingMessagesStorage *self);

FOUNDATION_EXPORT ImDiyalogCoreModulesMessagingActorsEntityPendingMessagesStorage *new_ImDiyalogCoreModulesMessagingActorsEntityPendingMessagesStorage_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogCoreModulesMessagingActorsEntityPendingMessagesStorage *create_ImDiyalogCoreModulesMessagingActorsEntityPendingMessagesStorage_init();

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogCoreModulesMessagingActorsEntityPendingMessagesStorage)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreModulesMessagingActorsEntityPendingMessagesStorage")
