//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/network/mtp/entity/rpc/RpcInternalError.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreNetworkMtpEntityRpcRpcInternalError")
#ifdef RESTRICT_ImDiyalogCoreNetworkMtpEntityRpcRpcInternalError
#define INCLUDE_ALL_ImDiyalogCoreNetworkMtpEntityRpcRpcInternalError 0
#else
#define INCLUDE_ALL_ImDiyalogCoreNetworkMtpEntityRpcRpcInternalError 1
#endif
#undef RESTRICT_ImDiyalogCoreNetworkMtpEntityRpcRpcInternalError

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ACRpcInternalError_) && (INCLUDE_ALL_ImDiyalogCoreNetworkMtpEntityRpcRpcInternalError || defined(INCLUDE_ACRpcInternalError))
#define ACRpcInternalError_

#define RESTRICT_ImDiyalogCoreNetworkMtpEntityProtoStruct 1
#define INCLUDE_ACProtoStruct 1
#include "../../../../../../../im/diyalog/core/network/mtp/entity/ProtoStruct.h"

@class ARDataInput;
@class ARDataOutput;

@interface ACRpcInternalError : ACProtoStruct

+ (jbyte)HEADER;

#pragma mark Public

- (instancetype)initWithBoolean:(jboolean)canTryAgain
                        withInt:(jint)tryAgainDelay;

- (instancetype)initWithARDataInput:(ARDataInput *)stream;

- (jint)getTryAgainDelay;

- (jboolean)isCanTryAgain;

#pragma mark Protected

- (jbyte)getHeader;

- (void)readBodyWithARDataInput:(ARDataInput *)bs;

- (void)writeBodyWithARDataOutput:(ARDataOutput *)bs;

@end

J2OBJC_EMPTY_STATIC_INIT(ACRpcInternalError)

inline jbyte ACRpcInternalError_get_HEADER();
#define ACRpcInternalError_HEADER 4
J2OBJC_STATIC_FIELD_CONSTANT(ACRpcInternalError, HEADER, jbyte)

FOUNDATION_EXPORT void ACRpcInternalError_initWithARDataInput_(ACRpcInternalError *self, ARDataInput *stream);

FOUNDATION_EXPORT ACRpcInternalError *new_ACRpcInternalError_initWithARDataInput_(ARDataInput *stream) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACRpcInternalError *create_ACRpcInternalError_initWithARDataInput_(ARDataInput *stream);

FOUNDATION_EXPORT void ACRpcInternalError_initWithBoolean_withInt_(ACRpcInternalError *self, jboolean canTryAgain, jint tryAgainDelay);

FOUNDATION_EXPORT ACRpcInternalError *new_ACRpcInternalError_initWithBoolean_withInt_(jboolean canTryAgain, jint tryAgainDelay) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACRpcInternalError *create_ACRpcInternalError_initWithBoolean_withInt_(jboolean canTryAgain, jint tryAgainDelay);

J2OBJC_TYPE_LITERAL_HEADER(ACRpcInternalError)

@compatibility_alias ImDiyalogCoreNetworkMtpEntityRpcRpcInternalError ACRpcInternalError;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreNetworkMtpEntityRpcRpcInternalError")
