//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/modules/calls/peers/PeerCallCallback.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreModulesCallsPeersPeerCallCallback")
#ifdef RESTRICT_ImDiyalogCoreModulesCallsPeersPeerCallCallback
#define INCLUDE_ALL_ImDiyalogCoreModulesCallsPeersPeerCallCallback 0
#else
#define INCLUDE_ALL_ImDiyalogCoreModulesCallsPeersPeerCallCallback 1
#endif
#undef RESTRICT_ImDiyalogCoreModulesCallsPeersPeerCallCallback

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImDiyalogCoreModulesCallsPeersPeerCallCallback_) && (INCLUDE_ALL_ImDiyalogCoreModulesCallsPeersPeerCallCallback || defined(INCLUDE_ImDiyalogCoreModulesCallsPeersPeerCallCallback))
#define ImDiyalogCoreModulesCallsPeersPeerCallCallback_

@class ImDiyalogCoreModulesCallsPeersPeerState;
@protocol ARWebRTCMediaStream;

@protocol ImDiyalogCoreModulesCallsPeersPeerCallCallback < NSObject, JavaObject >

- (void)onOfferWithLong:(jlong)deviceId
               withLong:(jlong)sessionId
           withNSString:(NSString *)sdp;

- (void)onAnswerWithLong:(jlong)deviceId
                withLong:(jlong)sessionId
            withNSString:(NSString *)sdp;

- (void)onCandidateWithLong:(jlong)deviceId
                    withInt:(jint)mdpIndex
               withNSString:(NSString *)id_
               withNSString:(NSString *)sdp;

- (void)onNegotiationSuccessfulWithLong:(jlong)deviceId
                               withLong:(jlong)sessionId;

- (void)onPeerStateChangedWithLong:(jlong)deviceId
withImDiyalogCoreModulesCallsPeersPeerState:(ImDiyalogCoreModulesCallsPeersPeerState *)state;

- (void)onStreamAddedWithLong:(jlong)deviceId
      withARWebRTCMediaStream:(id<ARWebRTCMediaStream>)stream;

- (void)onStreamRemovedWithLong:(jlong)deviceId
        withARWebRTCMediaStream:(id<ARWebRTCMediaStream>)stream;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogCoreModulesCallsPeersPeerCallCallback)

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogCoreModulesCallsPeersPeerCallCallback)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreModulesCallsPeersPeerCallCallback")
