//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/entity/PhoneBookContact.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreEntityPhoneBookContact")
#ifdef RESTRICT_ImDiyalogCoreEntityPhoneBookContact
#define INCLUDE_ALL_ImDiyalogCoreEntityPhoneBookContact 0
#else
#define INCLUDE_ALL_ImDiyalogCoreEntityPhoneBookContact 1
#endif
#undef RESTRICT_ImDiyalogCoreEntityPhoneBookContact

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ACPhoneBookContact_) && (INCLUDE_ALL_ImDiyalogCoreEntityPhoneBookContact || defined(INCLUDE_ACPhoneBookContact))
#define ACPhoneBookContact_

@class JavaUtilArrayList;

@interface ACPhoneBookContact : NSObject
@property (readonly, nonatomic, getter=getContactId) jlong contactId;
@property (readonly, copy, nonatomic, getter=getName) NSString *name;
@property (readonly, nonatomic, getter=getPhones) JavaUtilArrayList *phones;
@property (readonly, nonatomic, getter=getEmails) JavaUtilArrayList *emails;

#pragma mark Public

- (instancetype)initWithLong:(jlong)contactId
                withNSString:(NSString *)name
       withJavaUtilArrayList:(JavaUtilArrayList *)phones
       withJavaUtilArrayList:(JavaUtilArrayList *)emails;

- (jlong)getContactId;

- (JavaUtilArrayList *)getEmails;

- (NSString *)getName;

- (JavaUtilArrayList *)getPhones;

@end

J2OBJC_EMPTY_STATIC_INIT(ACPhoneBookContact)

FOUNDATION_EXPORT void ACPhoneBookContact_initWithLong_withNSString_withJavaUtilArrayList_withJavaUtilArrayList_(ACPhoneBookContact *self, jlong contactId, NSString *name, JavaUtilArrayList *phones, JavaUtilArrayList *emails);

FOUNDATION_EXPORT ACPhoneBookContact *new_ACPhoneBookContact_initWithLong_withNSString_withJavaUtilArrayList_withJavaUtilArrayList_(jlong contactId, NSString *name, JavaUtilArrayList *phones, JavaUtilArrayList *emails) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACPhoneBookContact *create_ACPhoneBookContact_initWithLong_withNSString_withJavaUtilArrayList_withJavaUtilArrayList_(jlong contactId, NSString *name, JavaUtilArrayList *phones, JavaUtilArrayList *emails);

J2OBJC_TYPE_LITERAL_HEADER(ACPhoneBookContact)

@compatibility_alias ImDiyalogCoreEntityPhoneBookContact ACPhoneBookContact;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreEntityPhoneBookContact")
