//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/entity/UserType.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreEntityUserType")
#ifdef RESTRICT_ImDiyalogCoreEntityUserType
#define INCLUDE_ALL_ImDiyalogCoreEntityUserType 0
#else
#define INCLUDE_ALL_ImDiyalogCoreEntityUserType 1
#endif
#undef RESTRICT_ImDiyalogCoreEntityUserType

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ACUserType_) && (INCLUDE_ALL_ImDiyalogCoreEntityUserType || defined(INCLUDE_ACUserType))
#define ACUserType_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
@import j2objc;

@class ARApiUserType;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

typedef NS_ENUM(NSUInteger, ACUserType_Enum) {
  ACUserType_Enum_PERSONAL = 0,
  ACUserType_Enum_BUSINESS = 1,
  ACUserType_Enum_ENTERPRISE = 2,
  ACUserType_Enum_DOMAINUSER = 3,
  ACUserType_Enum_DOMAINCUSTOMER = 4,
  ACUserType_Enum_BOT = 5,
  ACUserType_Enum_ANOUNYMOUS = 6,
  ACUserType_Enum_UNKNOWN = 7,
};

@interface ACUserType : JavaLangEnum < NSCopying >

+ (ACUserType *)PERSONAL;

+ (ACUserType *)BUSINESS;

+ (ACUserType *)ENTERPRISE;

+ (ACUserType *)DOMAINUSER;

+ (ACUserType *)DOMAINCUSTOMER;

+ (ACUserType *)BOT;

+ (ACUserType *)ANOUNYMOUS;

+ (ACUserType *)UNKNOWN;

#pragma mark Public

+ (ACUserType * __nonnull)fromValueWithInt:(jint)value;

- (jint)getValue;

- (ARApiUserType *)toApi;

#pragma mark Package-Private

+ (IOSObjectArray *)values;

+ (ACUserType *)valueOfWithNSString:(NSString *)name;

- (id)copyWithZone:(NSZone *)zone;
- (ACUserType_Enum)toNSEnum;

@end

J2OBJC_STATIC_INIT(ACUserType)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT ACUserType *ACUserType_values_[];

inline ACUserType *ACUserType_get_PERSONAL();
J2OBJC_ENUM_CONSTANT(ACUserType, PERSONAL)

inline ACUserType *ACUserType_get_BUSINESS();
J2OBJC_ENUM_CONSTANT(ACUserType, BUSINESS)

inline ACUserType *ACUserType_get_ENTERPRISE();
J2OBJC_ENUM_CONSTANT(ACUserType, ENTERPRISE)

inline ACUserType *ACUserType_get_DOMAINUSER();
J2OBJC_ENUM_CONSTANT(ACUserType, DOMAINUSER)

inline ACUserType *ACUserType_get_DOMAINCUSTOMER();
J2OBJC_ENUM_CONSTANT(ACUserType, DOMAINCUSTOMER)

inline ACUserType *ACUserType_get_BOT();
J2OBJC_ENUM_CONSTANT(ACUserType, BOT)

inline ACUserType *ACUserType_get_ANOUNYMOUS();
J2OBJC_ENUM_CONSTANT(ACUserType, ANOUNYMOUS)

inline ACUserType *ACUserType_get_UNKNOWN();
J2OBJC_ENUM_CONSTANT(ACUserType, UNKNOWN)

FOUNDATION_EXPORT ACUserType *ACUserType_fromValueWithInt_(jint value);

FOUNDATION_EXPORT IOSObjectArray *ACUserType_values();

FOUNDATION_EXPORT ACUserType *ACUserType_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT ACUserType *ACUserType_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(ACUserType)

@compatibility_alias ImDiyalogCoreEntityUserType ACUserType;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreEntityUserType")
