//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/runtime/runtime-shared/src/main/java/im/diyalog/runtime/mvvm/ValueConverter.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogRuntimeMvvmValueConverter")
#ifdef RESTRICT_ImDiyalogRuntimeMvvmValueConverter
#define INCLUDE_ALL_ImDiyalogRuntimeMvvmValueConverter 0
#else
#define INCLUDE_ALL_ImDiyalogRuntimeMvvmValueConverter 1
#endif
#undef RESTRICT_ImDiyalogRuntimeMvvmValueConverter

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARValueConverter_) && (INCLUDE_ALL_ImDiyalogRuntimeMvvmValueConverter || defined(INCLUDE_ARValueConverter))
#define ARValueConverter_

@protocol ARValueConverter < NSObject, JavaObject >

- (id)convertWithId:(id)src;

@end

J2OBJC_EMPTY_STATIC_INIT(ARValueConverter)

J2OBJC_TYPE_LITERAL_HEADER(ARValueConverter)

#define ImDiyalogRuntimeMvvmValueConverter ARValueConverter

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogRuntimeMvvmValueConverter")
