//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/network/mtp/entity/rpc/Push.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreNetworkMtpEntityRpcPush")
#ifdef RESTRICT_ImDiyalogCoreNetworkMtpEntityRpcPush
#define INCLUDE_ALL_ImDiyalogCoreNetworkMtpEntityRpcPush 0
#else
#define INCLUDE_ALL_ImDiyalogCoreNetworkMtpEntityRpcPush 1
#endif
#undef RESTRICT_ImDiyalogCoreNetworkMtpEntityRpcPush

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ACPush_) && (INCLUDE_ALL_ImDiyalogCoreNetworkMtpEntityRpcPush || defined(INCLUDE_ACPush))
#define ACPush_

#define RESTRICT_ImDiyalogCoreNetworkMtpEntityProtoStruct 1
#define INCLUDE_ACProtoStruct 1
#include "../../../../../../../im/diyalog/core/network/mtp/entity/ProtoStruct.h"

@class ARDataInput;
@class ARDataOutput;
@class IOSByteArray;

@interface ACPush : ACProtoStruct {
 @public
  jint updateType_;
  IOSByteArray *body_;
}

#pragma mark Public

- (instancetype)initWithARDataInput:(ARDataInput *)stream;

- (instancetype)initWithInt:(jint)updateType
              withByteArray:(IOSByteArray *)body;

- (jbyte)getHeader;

- (NSString *)description;

#pragma mark Protected

- (void)readBodyWithARDataInput:(ARDataInput *)bs;

- (void)writeBodyWithARDataOutput:(ARDataOutput *)bs;

@end

J2OBJC_EMPTY_STATIC_INIT(ACPush)

J2OBJC_FIELD_SETTER(ACPush, body_, IOSByteArray *)

FOUNDATION_EXPORT void ACPush_initWithARDataInput_(ACPush *self, ARDataInput *stream);

FOUNDATION_EXPORT ACPush *new_ACPush_initWithARDataInput_(ARDataInput *stream) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACPush *create_ACPush_initWithARDataInput_(ARDataInput *stream);

FOUNDATION_EXPORT void ACPush_initWithInt_withByteArray_(ACPush *self, jint updateType, IOSByteArray *body);

FOUNDATION_EXPORT ACPush *new_ACPush_initWithInt_withByteArray_(jint updateType, IOSByteArray *body) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACPush *create_ACPush_initWithInt_withByteArray_(jint updateType, IOSByteArray *body);

J2OBJC_TYPE_LITERAL_HEADER(ACPush)

@compatibility_alias ImDiyalogCoreNetworkMtpEntityRpcPush ACPush;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreNetworkMtpEntityRpcPush")
