//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/network/Endpoints.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreNetworkEndpoints")
#ifdef RESTRICT_ImDiyalogCoreNetworkEndpoints
#define INCLUDE_ALL_ImDiyalogCoreNetworkEndpoints 0
#else
#define INCLUDE_ALL_ImDiyalogCoreNetworkEndpoints 1
#endif
#undef RESTRICT_ImDiyalogCoreNetworkEndpoints

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ACEndpoints_) && (INCLUDE_ALL_ImDiyalogCoreNetworkEndpoints || defined(INCLUDE_ACEndpoints))
#define ACEndpoints_

@class ARConnectionEndpoint;
@class IOSObjectArray;

@interface ACEndpoints : NSObject

#pragma mark Public

- (instancetype)initWithARConnectionEndpointArray:(IOSObjectArray *)endpoints
                            withACTrustedKeyArray:(IOSObjectArray *)trustedKeys;

- (ARConnectionEndpoint *)fetchEndpointWithBoolean:(jboolean)preferEncrypted;

- (IOSObjectArray *)getTrustedKeys;

@end

J2OBJC_EMPTY_STATIC_INIT(ACEndpoints)

FOUNDATION_EXPORT void ACEndpoints_initWithARConnectionEndpointArray_withACTrustedKeyArray_(ACEndpoints *self, IOSObjectArray *endpoints, IOSObjectArray *trustedKeys);

FOUNDATION_EXPORT ACEndpoints *new_ACEndpoints_initWithARConnectionEndpointArray_withACTrustedKeyArray_(IOSObjectArray *endpoints, IOSObjectArray *trustedKeys) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACEndpoints *create_ACEndpoints_initWithARConnectionEndpointArray_withACTrustedKeyArray_(IOSObjectArray *endpoints, IOSObjectArray *trustedKeys);

J2OBJC_TYPE_LITERAL_HEADER(ACEndpoints)

@compatibility_alias ImDiyalogCoreNetworkEndpoints ACEndpoints;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreNetworkEndpoints")
