//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/modules/sequence/internal/CombinedDifference.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreModulesSequenceInternalCombinedDifference")
#ifdef RESTRICT_ImDiyalogCoreModulesSequenceInternalCombinedDifference
#define INCLUDE_ALL_ImDiyalogCoreModulesSequenceInternalCombinedDifference 0
#else
#define INCLUDE_ALL_ImDiyalogCoreModulesSequenceInternalCombinedDifference 1
#endif
#undef RESTRICT_ImDiyalogCoreModulesSequenceInternalCombinedDifference

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImDiyalogCoreModulesSequenceInternalCombinedDifference_) && (INCLUDE_ALL_ImDiyalogCoreModulesSequenceInternalCombinedDifference || defined(INCLUDE_ImDiyalogCoreModulesSequenceInternalCombinedDifference))
#define ImDiyalogCoreModulesSequenceInternalCombinedDifference_

@class ACPeer;
@class ARApiAppCounters;
@class ARUpdateMessage;
@class JavaUtilHashMap;
@protocol JavaUtilList;

@interface ImDiyalogCoreModulesSequenceInternalCombinedDifference : NSObject

#pragma mark Public

- (instancetype)init;

- (ARApiAppCounters *)getCounters;

- (JavaUtilHashMap *)getMessages;

- (id<JavaUtilList>)getOtherUpdates;

- (JavaUtilHashMap *)getRead;

- (JavaUtilHashMap *)getReadByMe;

- (JavaUtilHashMap *)getReceived;

- (void)putMessageWithARUpdateMessage:(ARUpdateMessage *)message;

- (void)putReadWithACPeer:(ACPeer *)peer
                 withLong:(jlong)date;

- (void)putReadByMeWithACPeer:(ACPeer *)peer
                     withLong:(jlong)date;

- (void)putReceivedWithACPeer:(ACPeer *)peer
                     withLong:(jlong)date;

- (void)setCountersWithARApiAppCounters:(ARApiAppCounters *)counters;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogCoreModulesSequenceInternalCombinedDifference)

FOUNDATION_EXPORT void ImDiyalogCoreModulesSequenceInternalCombinedDifference_init(ImDiyalogCoreModulesSequenceInternalCombinedDifference *self);

FOUNDATION_EXPORT ImDiyalogCoreModulesSequenceInternalCombinedDifference *new_ImDiyalogCoreModulesSequenceInternalCombinedDifference_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogCoreModulesSequenceInternalCombinedDifference *create_ImDiyalogCoreModulesSequenceInternalCombinedDifference_init();

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogCoreModulesSequenceInternalCombinedDifference)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreModulesSequenceInternalCombinedDifference")
