//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/api/ApiColorUnsupported.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreApiApiColorUnsupported")
#ifdef RESTRICT_ImDiyalogCoreApiApiColorUnsupported
#define INCLUDE_ALL_ImDiyalogCoreApiApiColorUnsupported 0
#else
#define INCLUDE_ALL_ImDiyalogCoreApiApiColorUnsupported 1
#endif
#undef RESTRICT_ImDiyalogCoreApiApiColorUnsupported

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARApiColorUnsupported_) && (INCLUDE_ALL_ImDiyalogCoreApiApiColorUnsupported || defined(INCLUDE_ARApiColorUnsupported))
#define ARApiColorUnsupported_

#define RESTRICT_ImDiyalogCoreApiApiColor 1
#define INCLUDE_ARApiColor 1
#include "../../../../im/diyalog/core/api/ApiColor.h"

@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

@interface ARApiColorUnsupported : ARApiColor

#pragma mark Public

- (instancetype)initWithInt:(jint)key
              withByteArray:(IOSByteArray *)content;

- (jint)getHeader;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

@end

J2OBJC_EMPTY_STATIC_INIT(ARApiColorUnsupported)

FOUNDATION_EXPORT void ARApiColorUnsupported_initWithInt_withByteArray_(ARApiColorUnsupported *self, jint key, IOSByteArray *content);

FOUNDATION_EXPORT ARApiColorUnsupported *new_ARApiColorUnsupported_initWithInt_withByteArray_(jint key, IOSByteArray *content) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARApiColorUnsupported *create_ARApiColorUnsupported_initWithInt_withByteArray_(jint key, IOSByteArray *content);

J2OBJC_TYPE_LITERAL_HEADER(ARApiColorUnsupported)

@compatibility_alias ImDiyalogCoreApiApiColorUnsupported ARApiColorUnsupported;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreApiApiColorUnsupported")
