//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/api/ApiDomainPhone.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreApiApiDomainPhone")
#ifdef RESTRICT_ImDiyalogCoreApiApiDomainPhone
#define INCLUDE_ALL_ImDiyalogCoreApiApiDomainPhone 0
#else
#define INCLUDE_ALL_ImDiyalogCoreApiApiDomainPhone 1
#endif
#undef RESTRICT_ImDiyalogCoreApiApiDomainPhone

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARApiDomainPhone_) && (INCLUDE_ALL_ImDiyalogCoreApiApiDomainPhone || defined(INCLUDE_ARApiDomainPhone))
#define ARApiDomainPhone_

#define RESTRICT_ImDiyalogRuntimeBserBserObject 1
#define INCLUDE_ARBserObject 1
#include "../../../../im/diyalog/runtime/bser/BserObject.h"

@class ARBserValues;
@class ARBserWriter;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARApiDomainPhone : ARBserObject

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithLong:(jlong)phone
                withNSString:(NSString * __nullable)title;

- (jlong)getPhone;

- (NSString * __nullable)getTitle;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARApiDomainPhone)

FOUNDATION_EXPORT void ARApiDomainPhone_initWithLong_withNSString_(ARApiDomainPhone *self, jlong phone, NSString *title);

FOUNDATION_EXPORT ARApiDomainPhone *new_ARApiDomainPhone_initWithLong_withNSString_(jlong phone, NSString *title) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARApiDomainPhone *create_ARApiDomainPhone_initWithLong_withNSString_(jlong phone, NSString *title);

FOUNDATION_EXPORT void ARApiDomainPhone_init(ARApiDomainPhone *self);

FOUNDATION_EXPORT ARApiDomainPhone *new_ARApiDomainPhone_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARApiDomainPhone *create_ARApiDomainPhone_init();

J2OBJC_TYPE_LITERAL_HEADER(ARApiDomainPhone)

@compatibility_alias ImDiyalogCoreApiApiDomainPhone ARApiDomainPhone;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreApiApiDomainPhone")
