//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/api/ApiMessageSearchResult.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreApiApiMessageSearchResult")
#ifdef RESTRICT_ImDiyalogCoreApiApiMessageSearchResult
#define INCLUDE_ALL_ImDiyalogCoreApiApiMessageSearchResult 0
#else
#define INCLUDE_ALL_ImDiyalogCoreApiApiMessageSearchResult 1
#endif
#undef RESTRICT_ImDiyalogCoreApiApiMessageSearchResult

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARApiMessageSearchResult_) && (INCLUDE_ALL_ImDiyalogCoreApiApiMessageSearchResult || defined(INCLUDE_ARApiMessageSearchResult))
#define ARApiMessageSearchResult_

#define RESTRICT_ImDiyalogRuntimeBserBserObject 1
#define INCLUDE_ARBserObject 1
#include "../../../../im/diyalog/runtime/bser/BserObject.h"

@class ARApiMessage;
@class ARApiPeer;
@class ARBserValues;
@class ARBserWriter;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARApiMessageSearchResult : ARBserObject

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithARApiPeer:(ARApiPeer * __nonnull)peer
                         withLong:(jlong)rid
                         withLong:(jlong)date
                          withInt:(jint)senderId
                 withARApiMessage:(ARApiMessage * __nonnull)content;

- (ARApiMessage * __nonnull)getContent;

- (jlong)getDate;

- (ARApiPeer * __nonnull)getPeer;

- (jlong)getRid;

- (jint)getSenderId;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARApiMessageSearchResult)

FOUNDATION_EXPORT void ARApiMessageSearchResult_initWithARApiPeer_withLong_withLong_withInt_withARApiMessage_(ARApiMessageSearchResult *self, ARApiPeer *peer, jlong rid, jlong date, jint senderId, ARApiMessage *content);

FOUNDATION_EXPORT ARApiMessageSearchResult *new_ARApiMessageSearchResult_initWithARApiPeer_withLong_withLong_withInt_withARApiMessage_(ARApiPeer *peer, jlong rid, jlong date, jint senderId, ARApiMessage *content) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARApiMessageSearchResult *create_ARApiMessageSearchResult_initWithARApiPeer_withLong_withLong_withInt_withARApiMessage_(ARApiPeer *peer, jlong rid, jlong date, jint senderId, ARApiMessage *content);

FOUNDATION_EXPORT void ARApiMessageSearchResult_init(ARApiMessageSearchResult *self);

FOUNDATION_EXPORT ARApiMessageSearchResult *new_ARApiMessageSearchResult_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARApiMessageSearchResult *create_ARApiMessageSearchResult_init();

J2OBJC_TYPE_LITERAL_HEADER(ARApiMessageSearchResult)

@compatibility_alias ImDiyalogCoreApiApiMessageSearchResult ARApiMessageSearchResult;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreApiApiMessageSearchResult")
