//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/api/ApiOffer.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreApiApiOffer")
#ifdef RESTRICT_ImDiyalogCoreApiApiOffer
#define INCLUDE_ALL_ImDiyalogCoreApiApiOffer 0
#else
#define INCLUDE_ALL_ImDiyalogCoreApiApiOffer 1
#endif
#undef RESTRICT_ImDiyalogCoreApiApiOffer

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARApiOffer_) && (INCLUDE_ALL_ImDiyalogCoreApiApiOffer || defined(INCLUDE_ARApiOffer))
#define ARApiOffer_

#define RESTRICT_ImDiyalogCoreApiApiWebRTCSignaling 1
#define INCLUDE_ARApiWebRTCSignaling 1
#include "../../../../im/diyalog/core/api/ApiWebRTCSignaling.h"

@class ARApiPeerSettings;
@class ARBserValues;
@class ARBserWriter;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARApiOffer : ARApiWebRTCSignaling

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithLong:(jlong)sessionId
                withNSString:(NSString * __nonnull)sdp
       withARApiPeerSettings:(ARApiPeerSettings * __nullable)ownPeerSettings;

- (jint)getHeader;

- (ARApiPeerSettings * __nullable)getOwnPeerSettings;

- (NSString * __nonnull)getSdp;

- (jlong)getSessionId;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARApiOffer)

FOUNDATION_EXPORT void ARApiOffer_initWithLong_withNSString_withARApiPeerSettings_(ARApiOffer *self, jlong sessionId, NSString *sdp, ARApiPeerSettings *ownPeerSettings);

FOUNDATION_EXPORT ARApiOffer *new_ARApiOffer_initWithLong_withNSString_withARApiPeerSettings_(jlong sessionId, NSString *sdp, ARApiPeerSettings *ownPeerSettings) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARApiOffer *create_ARApiOffer_initWithLong_withNSString_withARApiPeerSettings_(jlong sessionId, NSString *sdp, ARApiPeerSettings *ownPeerSettings);

FOUNDATION_EXPORT void ARApiOffer_init(ARApiOffer *self);

FOUNDATION_EXPORT ARApiOffer *new_ARApiOffer_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARApiOffer *create_ARApiOffer_init();

J2OBJC_TYPE_LITERAL_HEADER(ARApiOffer)

@compatibility_alias ImDiyalogCoreApiApiOffer ARApiOffer;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreApiApiOffer")
