//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/modules/messaging/actors/CursorReaderActor.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreModulesMessagingActorsCursorReaderActor")
#ifdef RESTRICT_ImDiyalogCoreModulesMessagingActorsCursorReaderActor
#define INCLUDE_ALL_ImDiyalogCoreModulesMessagingActorsCursorReaderActor 0
#else
#define INCLUDE_ALL_ImDiyalogCoreModulesMessagingActorsCursorReaderActor 1
#endif
#undef RESTRICT_ImDiyalogCoreModulesMessagingActorsCursorReaderActor

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImDiyalogCoreModulesMessagingActorsCursorReaderActor_) && (INCLUDE_ALL_ImDiyalogCoreModulesMessagingActorsCursorReaderActor || defined(INCLUDE_ImDiyalogCoreModulesMessagingActorsCursorReaderActor))
#define ImDiyalogCoreModulesMessagingActorsCursorReaderActor_

#define RESTRICT_ImDiyalogCoreModulesMessagingActorsCursorActor 1
#define INCLUDE_ImDiyalogCoreModulesMessagingActorsCursorActor 1
#include "../../../../../../im/diyalog/core/modules/messaging/actors/CursorActor.h"

@class ACPeer;
@protocol ACModuleContext;

@interface ImDiyalogCoreModulesMessagingActorsCursorReaderActor : ImDiyalogCoreModulesMessagingActorsCursorActor

#pragma mark Public

- (instancetype)initWithACModuleContext:(id<ACModuleContext>)context;

- (void)onReceiveWithId:(id)message;

#pragma mark Protected

- (void)performWithACPeer:(ACPeer *)peer
                 withLong:(jlong)date;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogCoreModulesMessagingActorsCursorReaderActor)

FOUNDATION_EXPORT void ImDiyalogCoreModulesMessagingActorsCursorReaderActor_initWithACModuleContext_(ImDiyalogCoreModulesMessagingActorsCursorReaderActor *self, id<ACModuleContext> context);

FOUNDATION_EXPORT ImDiyalogCoreModulesMessagingActorsCursorReaderActor *new_ImDiyalogCoreModulesMessagingActorsCursorReaderActor_initWithACModuleContext_(id<ACModuleContext> context) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogCoreModulesMessagingActorsCursorReaderActor *create_ImDiyalogCoreModulesMessagingActorsCursorReaderActor_initWithACModuleContext_(id<ACModuleContext> context);

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogCoreModulesMessagingActorsCursorReaderActor)

#endif

#if !defined (ImDiyalogCoreModulesMessagingActorsCursorReaderActor_MarkRead_) && (INCLUDE_ALL_ImDiyalogCoreModulesMessagingActorsCursorReaderActor || defined(INCLUDE_ImDiyalogCoreModulesMessagingActorsCursorReaderActor_MarkRead))
#define ImDiyalogCoreModulesMessagingActorsCursorReaderActor_MarkRead_

@class ACPeer;

@interface ImDiyalogCoreModulesMessagingActorsCursorReaderActor_MarkRead : NSObject

#pragma mark Public

- (instancetype)initWithACPeer:(ACPeer *)peer
                      withLong:(jlong)date;

- (jlong)getDate;

- (ACPeer *)getPeer;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogCoreModulesMessagingActorsCursorReaderActor_MarkRead)

FOUNDATION_EXPORT void ImDiyalogCoreModulesMessagingActorsCursorReaderActor_MarkRead_initWithACPeer_withLong_(ImDiyalogCoreModulesMessagingActorsCursorReaderActor_MarkRead *self, ACPeer *peer, jlong date);

FOUNDATION_EXPORT ImDiyalogCoreModulesMessagingActorsCursorReaderActor_MarkRead *new_ImDiyalogCoreModulesMessagingActorsCursorReaderActor_MarkRead_initWithACPeer_withLong_(ACPeer *peer, jlong date) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogCoreModulesMessagingActorsCursorReaderActor_MarkRead *create_ImDiyalogCoreModulesMessagingActorsCursorReaderActor_MarkRead_initWithACPeer_withLong_(ACPeer *peer, jlong date);

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogCoreModulesMessagingActorsCursorReaderActor_MarkRead)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreModulesMessagingActorsCursorReaderActor")
