//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/runtime/runtime-cocoa/src/main/java/im/diyalog/runtime/cocoa/CocoaRandomProvider.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogRuntimeCocoaCocoaRandomProvider")
#ifdef RESTRICT_ImDiyalogRuntimeCocoaCocoaRandomProvider
#define INCLUDE_ALL_ImDiyalogRuntimeCocoaCocoaRandomProvider 0
#else
#define INCLUDE_ALL_ImDiyalogRuntimeCocoaCocoaRandomProvider 1
#endif
#undef RESTRICT_ImDiyalogRuntimeCocoaCocoaRandomProvider

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARCocoaRandomProvider_) && (INCLUDE_ALL_ImDiyalogRuntimeCocoaCocoaRandomProvider || defined(INCLUDE_ARCocoaRandomProvider))
#define ARCocoaRandomProvider_

#define RESTRICT_ImDiyalogRuntimeGenericGenericRandomProvider 1
#define INCLUDE_ARGenericRandomProvider 1
#include "../../../../im/diyalog/runtime/generic/GenericRandomProvider.h"

@interface ARCocoaRandomProvider : ARGenericRandomProvider

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ARCocoaRandomProvider)

FOUNDATION_EXPORT void ARCocoaRandomProvider_init(ARCocoaRandomProvider *self);

FOUNDATION_EXPORT ARCocoaRandomProvider *new_ARCocoaRandomProvider_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARCocoaRandomProvider *create_ARCocoaRandomProvider_init();

J2OBJC_TYPE_LITERAL_HEADER(ARCocoaRandomProvider)

@compatibility_alias ImDiyalogRuntimeCocoaCocoaRandomProvider ARCocoaRandomProvider;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogRuntimeCocoaCocoaRandomProvider")
