//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/runtime/runtime-shared/src/main/java/im/diyalog/runtime/StorageRuntime.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogRuntimeStorageRuntime")
#ifdef RESTRICT_ImDiyalogRuntimeStorageRuntime
#define INCLUDE_ALL_ImDiyalogRuntimeStorageRuntime 0
#else
#define INCLUDE_ALL_ImDiyalogRuntimeStorageRuntime 1
#endif
#undef RESTRICT_ImDiyalogRuntimeStorageRuntime

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARStorageRuntime_) && (INCLUDE_ALL_ImDiyalogRuntimeStorageRuntime || defined(INCLUDE_ARStorageRuntime))
#define ARStorageRuntime_

@protocol ARIndexStorage;
@protocol ARKeyValueStorage;
@protocol ARListStorage;
@protocol ARPreferencesStorage;

/*!
 @brief Provider for data storage.
 Provider is separated to two parts: Storage and Engines.
 Storage are simple interfaces for storing untyped data in some persistent offline storage.
 Engines are interfaces for working with storage that contains various implementations for different
 platforms and provide clever caching and multithread support. Engines are also has methods for getting
 data for UI.
 */
@protocol ARStorageRuntime < NSObject, JavaObject >

/*!
 @brief Creating main preferences storage.
 Called only once.
 @return the PreferencesStorage
 */
- (id<ARPreferencesStorage>)createPreferencesStorage;

/*!
 @brief Creating index storage.
 Called only once for each index.
 @param name name of index engine
 @return the IndexStorage
 */
- (id<ARIndexStorage>)createIndexWithName:(NSString *)name;

/*!
 @brief Creating key value storage.
 Called only once for each storage.
 Preferred lazy initialization in implementation of KeyValueStorage.
 @param name name of storage
 @return the KeyValueStorage
 */
- (id<ARKeyValueStorage>)createKeyValueWithName:(NSString *)name;

/*!
 @brief Creating list storage.
 Called only once for each storage.
 Preferred lazy initialization in implementation of ListStorage.
 @param name name of list storage
 @return the ListStorage
 */
- (id<ARListStorage>)createListWithName:(NSString *)name;

/*!
 @brief Reset storage
 */
- (void)resetStorage;

@end

J2OBJC_EMPTY_STATIC_INIT(ARStorageRuntime)

J2OBJC_TYPE_LITERAL_HEADER(ARStorageRuntime)

#define ImDiyalogRuntimeStorageRuntime ARStorageRuntime

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogRuntimeStorageRuntime")
