//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/runtime/runtime-cocoa/src/main/java/im/diyalog/runtime/WebRTCRuntimeProvider.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogRuntimeWebRTCRuntimeProvider")
#ifdef RESTRICT_ImDiyalogRuntimeWebRTCRuntimeProvider
#define INCLUDE_ALL_ImDiyalogRuntimeWebRTCRuntimeProvider 0
#else
#define INCLUDE_ALL_ImDiyalogRuntimeWebRTCRuntimeProvider 1
#endif
#undef RESTRICT_ImDiyalogRuntimeWebRTCRuntimeProvider

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARWebRTCRuntimeProvider_) && (INCLUDE_ALL_ImDiyalogRuntimeWebRTCRuntimeProvider || defined(INCLUDE_ARWebRTCRuntimeProvider))
#define ARWebRTCRuntimeProvider_

#define RESTRICT_ImDiyalogRuntimeCocoaCocoaWebRTCProxyProvider 1
#define INCLUDE_ARCocoaWebRTCProxyProvider 1
#include "../../../im/diyalog/runtime/cocoa/CocoaWebRTCProxyProvider.h"

@interface ARWebRTCRuntimeProvider : ARCocoaWebRTCProxyProvider

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ARWebRTCRuntimeProvider)

FOUNDATION_EXPORT void ARWebRTCRuntimeProvider_init(ARWebRTCRuntimeProvider *self);

FOUNDATION_EXPORT ARWebRTCRuntimeProvider *new_ARWebRTCRuntimeProvider_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARWebRTCRuntimeProvider *create_ARWebRTCRuntimeProvider_init();

J2OBJC_TYPE_LITERAL_HEADER(ARWebRTCRuntimeProvider)

@compatibility_alias ImDiyalogRuntimeWebRTCRuntimeProvider ARWebRTCRuntimeProvider;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogRuntimeWebRTCRuntimeProvider")
