//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/entity/content/PhotoContent.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreEntityContentPhotoContent")
#ifdef RESTRICT_ImDiyalogCoreEntityContentPhotoContent
#define INCLUDE_ALL_ImDiyalogCoreEntityContentPhotoContent 0
#else
#define INCLUDE_ALL_ImDiyalogCoreEntityContentPhotoContent 1
#endif
#undef RESTRICT_ImDiyalogCoreEntityContentPhotoContent

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ACPhotoContent_) && (INCLUDE_ALL_ImDiyalogCoreEntityContentPhotoContent || defined(INCLUDE_ACPhotoContent))
#define ACPhotoContent_

#define RESTRICT_ImDiyalogCoreEntityContentDocumentContent 1
#define INCLUDE_ACDocumentContent 1
#include "../../../../../im/diyalog/core/entity/content/DocumentContent.h"

@class ACContentLocalContainer;
@class ACContentRemoteContainer;
@class ACFastThumb;
@class ACFileReference;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ACPhotoContent : ACDocumentContent

#pragma mark Public

- (instancetype)initWithACContentLocalContainer:(ACContentLocalContainer *)contentLocalContainer;

- (instancetype)initWithACContentRemoteContainer:(ACContentRemoteContainer *)contentRemoteContainer;

+ (ACPhotoContent * __nonnull)createLocalPhotoWithNSString:(NSString * __nonnull)descriptor
                                              withNSString:(NSString * __nonnull)fileName
                                                   withInt:(jint)fileSize
                                                   withInt:(jint)w
                                                   withInt:(jint)h
                                           withACFastThumb:(ACFastThumb * __nullable)fastThumb;

+ (ACPhotoContent * __nonnull)createRemotePhotoWithACFileReference:(ACFileReference * __nonnull)reference
                                                           withInt:(jint)w
                                                           withInt:(jint)h
                                                   withACFastThumb:(ACFastThumb * __nullable)fastThumb;

- (jint)getH;

- (jint)getW;

@end

J2OBJC_EMPTY_STATIC_INIT(ACPhotoContent)

FOUNDATION_EXPORT ACPhotoContent *ACPhotoContent_createLocalPhotoWithNSString_withNSString_withInt_withInt_withInt_withACFastThumb_(NSString *descriptor, NSString *fileName, jint fileSize, jint w, jint h, ACFastThumb *fastThumb);

FOUNDATION_EXPORT ACPhotoContent *ACPhotoContent_createRemotePhotoWithACFileReference_withInt_withInt_withACFastThumb_(ACFileReference *reference, jint w, jint h, ACFastThumb *fastThumb);

FOUNDATION_EXPORT void ACPhotoContent_initWithACContentLocalContainer_(ACPhotoContent *self, ACContentLocalContainer *contentLocalContainer);

FOUNDATION_EXPORT ACPhotoContent *new_ACPhotoContent_initWithACContentLocalContainer_(ACContentLocalContainer *contentLocalContainer) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACPhotoContent *create_ACPhotoContent_initWithACContentLocalContainer_(ACContentLocalContainer *contentLocalContainer);

FOUNDATION_EXPORT void ACPhotoContent_initWithACContentRemoteContainer_(ACPhotoContent *self, ACContentRemoteContainer *contentRemoteContainer);

FOUNDATION_EXPORT ACPhotoContent *new_ACPhotoContent_initWithACContentRemoteContainer_(ACContentRemoteContainer *contentRemoteContainer) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACPhotoContent *create_ACPhotoContent_initWithACContentRemoteContainer_(ACContentRemoteContainer *contentRemoteContainer);

J2OBJC_TYPE_LITERAL_HEADER(ACPhotoContent)

@compatibility_alias ImDiyalogCoreEntityContentPhotoContent ACPhotoContent;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreEntityContentPhotoContent")
