//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/entity/content/QuickReplyContent.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreEntityContentQuickReplyContent")
#ifdef RESTRICT_ImDiyalogCoreEntityContentQuickReplyContent
#define INCLUDE_ALL_ImDiyalogCoreEntityContentQuickReplyContent 0
#else
#define INCLUDE_ALL_ImDiyalogCoreEntityContentQuickReplyContent 1
#endif
#undef RESTRICT_ImDiyalogCoreEntityContentQuickReplyContent

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ACQuickReplyContent_) && (INCLUDE_ALL_ImDiyalogCoreEntityContentQuickReplyContent || defined(INCLUDE_ACQuickReplyContent))
#define ACQuickReplyContent_

#define RESTRICT_ImDiyalogCoreEntityContentAbsContent 1
#define INCLUDE_ACAbsContent 1
#include "../../../../../im/diyalog/core/entity/content/AbsContent.h"

@class ACContentRemoteContainer;
@class JavaLangBoolean;
@class JavaUtilArrayList;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ACQuickReplyContent : ACAbsContent

#pragma mark Public

- (instancetype)initWithACContentRemoteContainer:(ACContentRemoteContainer *)contentContainer;

+ (ACQuickReplyContent * __nonnull)createWithNSString:(NSString *)text
                                withJavaUtilArrayList:(JavaUtilArrayList * __nullable)quickReplies
                                  withJavaLangBoolean:(JavaLangBoolean *)speak;

- (JavaUtilArrayList * __nullable)getQuickReplies;

- (NSString *)getRawMessage;

- (JavaLangBoolean *)getSpeak;

- (NSString *)getText;

@end

J2OBJC_EMPTY_STATIC_INIT(ACQuickReplyContent)

FOUNDATION_EXPORT ACQuickReplyContent *ACQuickReplyContent_createWithNSString_withJavaUtilArrayList_withJavaLangBoolean_(NSString *text, JavaUtilArrayList *quickReplies, JavaLangBoolean *speak);

FOUNDATION_EXPORT void ACQuickReplyContent_initWithACContentRemoteContainer_(ACQuickReplyContent *self, ACContentRemoteContainer *contentContainer);

FOUNDATION_EXPORT ACQuickReplyContent *new_ACQuickReplyContent_initWithACContentRemoteContainer_(ACContentRemoteContainer *contentContainer) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACQuickReplyContent *create_ACQuickReplyContent_initWithACContentRemoteContainer_(ACContentRemoteContainer *contentContainer);

J2OBJC_TYPE_LITERAL_HEADER(ACQuickReplyContent)

@compatibility_alias ImDiyalogCoreEntityContentQuickReplyContent ACQuickReplyContent;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreEntityContentQuickReplyContent")
