//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/entity/content/VoiceContent.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreEntityContentVoiceContent")
#ifdef RESTRICT_ImDiyalogCoreEntityContentVoiceContent
#define INCLUDE_ALL_ImDiyalogCoreEntityContentVoiceContent 0
#else
#define INCLUDE_ALL_ImDiyalogCoreEntityContentVoiceContent 1
#endif
#undef RESTRICT_ImDiyalogCoreEntityContentVoiceContent

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ACVoiceContent_) && (INCLUDE_ALL_ImDiyalogCoreEntityContentVoiceContent || defined(INCLUDE_ACVoiceContent))
#define ACVoiceContent_

#define RESTRICT_ImDiyalogCoreEntityContentDocumentContent 1
#define INCLUDE_ACDocumentContent 1
#include "../../../../../im/diyalog/core/entity/content/DocumentContent.h"

@class ACContentLocalContainer;
@class ACContentRemoteContainer;
@class ACFileReference;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ACVoiceContent : ACDocumentContent

#pragma mark Public

- (instancetype)initWithACContentLocalContainer:(ACContentLocalContainer *)contentLocalContainer;

- (instancetype)initWithACContentRemoteContainer:(ACContentRemoteContainer *)contentRemoteContainer;

+ (ACVoiceContent * __nonnull)createLocalAudioWithNSString:(NSString * __nonnull)descriptor
                                              withNSString:(NSString * __nonnull)fileName
                                                   withInt:(jint)fileSize
                                                   withInt:(jint)duration;

+ (ACVoiceContent * __nonnull)createRemoteAudioWithACFileReference:(ACFileReference * __nonnull)reference
                                                           withInt:(jint)duration;

- (jint)getDuration;

@end

J2OBJC_EMPTY_STATIC_INIT(ACVoiceContent)

FOUNDATION_EXPORT ACVoiceContent *ACVoiceContent_createLocalAudioWithNSString_withNSString_withInt_withInt_(NSString *descriptor, NSString *fileName, jint fileSize, jint duration);

FOUNDATION_EXPORT ACVoiceContent *ACVoiceContent_createRemoteAudioWithACFileReference_withInt_(ACFileReference *reference, jint duration);

FOUNDATION_EXPORT void ACVoiceContent_initWithACContentLocalContainer_(ACVoiceContent *self, ACContentLocalContainer *contentLocalContainer);

FOUNDATION_EXPORT ACVoiceContent *new_ACVoiceContent_initWithACContentLocalContainer_(ACContentLocalContainer *contentLocalContainer) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACVoiceContent *create_ACVoiceContent_initWithACContentLocalContainer_(ACContentLocalContainer *contentLocalContainer);

FOUNDATION_EXPORT void ACVoiceContent_initWithACContentRemoteContainer_(ACVoiceContent *self, ACContentRemoteContainer *contentRemoteContainer);

FOUNDATION_EXPORT ACVoiceContent *new_ACVoiceContent_initWithACContentRemoteContainer_(ACContentRemoteContainer *contentRemoteContainer) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACVoiceContent *create_ACVoiceContent_initWithACContentRemoteContainer_(ACContentRemoteContainer *contentRemoteContainer);

J2OBJC_TYPE_LITERAL_HEADER(ACVoiceContent)

@compatibility_alias ImDiyalogCoreEntityContentVoiceContent ACVoiceContent;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreEntityContentVoiceContent")
