//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/modules/notifications/entity/PendingStorage.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreModulesNotificationsEntityPendingStorage")
#ifdef RESTRICT_ImDiyalogCoreModulesNotificationsEntityPendingStorage
#define INCLUDE_ALL_ImDiyalogCoreModulesNotificationsEntityPendingStorage 0
#else
#define INCLUDE_ALL_ImDiyalogCoreModulesNotificationsEntityPendingStorage 1
#endif
#undef RESTRICT_ImDiyalogCoreModulesNotificationsEntityPendingStorage

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImDiyalogCoreModulesNotificationsEntityPendingStorage_) && (INCLUDE_ALL_ImDiyalogCoreModulesNotificationsEntityPendingStorage || defined(INCLUDE_ImDiyalogCoreModulesNotificationsEntityPendingStorage))
#define ImDiyalogCoreModulesNotificationsEntityPendingStorage_

#define RESTRICT_ImDiyalogRuntimeBserBserObject 1
#define INCLUDE_ARBserObject 1
#include "../../../../../../im/diyalog/runtime/bser/BserObject.h"

@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;
@protocol JavaUtilList;

@interface ImDiyalogCoreModulesNotificationsEntityPendingStorage : ARBserObject

#pragma mark Public

- (instancetype)init;

+ (ImDiyalogCoreModulesNotificationsEntityPendingStorage *)fromBytesWithByteArray:(IOSByteArray *)data;

- (id<JavaUtilList>)getNotifications;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogCoreModulesNotificationsEntityPendingStorage)

FOUNDATION_EXPORT ImDiyalogCoreModulesNotificationsEntityPendingStorage *ImDiyalogCoreModulesNotificationsEntityPendingStorage_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ImDiyalogCoreModulesNotificationsEntityPendingStorage_init(ImDiyalogCoreModulesNotificationsEntityPendingStorage *self);

FOUNDATION_EXPORT ImDiyalogCoreModulesNotificationsEntityPendingStorage *new_ImDiyalogCoreModulesNotificationsEntityPendingStorage_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogCoreModulesNotificationsEntityPendingStorage *create_ImDiyalogCoreModulesNotificationsEntityPendingStorage_init();

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogCoreModulesNotificationsEntityPendingStorage)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreModulesNotificationsEntityPendingStorage")
