//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/network/parser/ApiParserConfig.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreNetworkParserApiParserConfig")
#ifdef RESTRICT_ImDiyalogCoreNetworkParserApiParserConfig
#define INCLUDE_ALL_ImDiyalogCoreNetworkParserApiParserConfig 0
#else
#define INCLUDE_ALL_ImDiyalogCoreNetworkParserApiParserConfig 1
#endif
#undef RESTRICT_ImDiyalogCoreNetworkParserApiParserConfig

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ACApiParserConfig_) && (INCLUDE_ALL_ImDiyalogCoreNetworkParserApiParserConfig || defined(INCLUDE_ACApiParserConfig))
#define ACApiParserConfig_

@class ACParsingExtension;
@class ACRpcScope;
@class IOSByteArray;

@interface ACApiParserConfig : NSObject

#pragma mark Public

- (instancetype)init;

- (void)addExtensionWithACParsingExtension:(ACParsingExtension *)extension;

- (ACRpcScope *)parseRpcWithInt:(jint)header
                  withByteArray:(IOSByteArray *)content;

@end

J2OBJC_EMPTY_STATIC_INIT(ACApiParserConfig)

FOUNDATION_EXPORT void ACApiParserConfig_init(ACApiParserConfig *self);

FOUNDATION_EXPORT ACApiParserConfig *new_ACApiParserConfig_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACApiParserConfig *create_ACApiParserConfig_init();

J2OBJC_TYPE_LITERAL_HEADER(ACApiParserConfig)

@compatibility_alias ImDiyalogCoreNetworkParserApiParserConfig ACApiParserConfig;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreNetworkParserApiParserConfig")
