//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/runtime/runtime-shared/src/main/java/im/diyalog/runtime/threading/ThreadLocalCompat.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogRuntimeThreadingThreadLocalCompat")
#ifdef RESTRICT_ImDiyalogRuntimeThreadingThreadLocalCompat
#define INCLUDE_ALL_ImDiyalogRuntimeThreadingThreadLocalCompat 0
#else
#define INCLUDE_ALL_ImDiyalogRuntimeThreadingThreadLocalCompat 1
#endif
#undef RESTRICT_ImDiyalogRuntimeThreadingThreadLocalCompat

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARThreadLocalCompat_) && (INCLUDE_ALL_ImDiyalogRuntimeThreadingThreadLocalCompat || defined(INCLUDE_ARThreadLocalCompat))
#define ARThreadLocalCompat_

/*!
 @brief Abstract ThreadLocal implementation
 */
@interface ARThreadLocalCompat : NSObject

#pragma mark Public

- (instancetype)init;

/*!
 @brief Return value for current Thread
 @return value
 */
- (id)get;

/*!
 @brief Remove value for current Thread
 */
- (void)remove;

/*!
 @brief Set value for current Thread
 @param v new value
 */
- (void)setWithId:(id)v;

@end

J2OBJC_EMPTY_STATIC_INIT(ARThreadLocalCompat)

FOUNDATION_EXPORT void ARThreadLocalCompat_init(ARThreadLocalCompat *self);

J2OBJC_TYPE_LITERAL_HEADER(ARThreadLocalCompat)

@compatibility_alias ImDiyalogRuntimeThreadingThreadLocalCompat ARThreadLocalCompat;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogRuntimeThreadingThreadLocalCompat")
