//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/modules/file/UploadManager.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreModulesFileUploadManager")
#ifdef RESTRICT_ImDiyalogCoreModulesFileUploadManager
#define INCLUDE_ALL_ImDiyalogCoreModulesFileUploadManager 0
#else
#define INCLUDE_ALL_ImDiyalogCoreModulesFileUploadManager 1
#endif
#undef RESTRICT_ImDiyalogCoreModulesFileUploadManager

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImDiyalogCoreModulesFileUploadManager_) && (INCLUDE_ALL_ImDiyalogCoreModulesFileUploadManager || defined(INCLUDE_ImDiyalogCoreModulesFileUploadManager))
#define ImDiyalogCoreModulesFileUploadManager_

#define RESTRICT_ImDiyalogCoreModulesModuleActor 1
#define INCLUDE_ACModuleActor 1
#include "../../../../../im/diyalog/core/modules/ModuleActor.h"

@class ACFileReference;
@class ARActorRef;
@protocol ACModuleContext;
@protocol ACUploadFileCallback;
@protocol ARFileSystemReference;

@interface ImDiyalogCoreModulesFileUploadManager : ACModuleActor

#pragma mark Public

- (instancetype)initWithACModuleContext:(id<ACModuleContext>)context;

- (void)bindUploadWithLong:(jlong)rid
  withACUploadFileCallback:(id<ACUploadFileCallback>)callback;

- (void)onReceiveWithId:(id)message;

- (void)onUploadTaskCompleteWithLong:(jlong)rid
                 withACFileReference:(ACFileReference *)fileReference
           withARFileSystemReference:(id<ARFileSystemReference>)reference;

- (void)onUploadTaskErrorWithLong:(jlong)rid;

- (void)onUploadTaskProgressWithLong:(jlong)rid
                           withFloat:(jfloat)progress;

- (void)pauseUploadWithLong:(jlong)rid;

- (void)requestStateWithLong:(jlong)rid
    withACUploadFileCallback:(id<ACUploadFileCallback>)callback;

- (void)resumeUploadWithLong:(jlong)rid;

- (void)startUploadWithLong:(jlong)rid
               withNSString:(NSString *)descriptor
               withNSString:(NSString *)fileName
             withARActorRef:(ARActorRef *)requestActor;

- (void)stopUploadWithLong:(jlong)rid;

- (void)unbindUploadWithLong:(jlong)rid
    withACUploadFileCallback:(id<ACUploadFileCallback>)callback;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogCoreModulesFileUploadManager)

FOUNDATION_EXPORT void ImDiyalogCoreModulesFileUploadManager_initWithACModuleContext_(ImDiyalogCoreModulesFileUploadManager *self, id<ACModuleContext> context);

FOUNDATION_EXPORT ImDiyalogCoreModulesFileUploadManager *new_ImDiyalogCoreModulesFileUploadManager_initWithACModuleContext_(id<ACModuleContext> context) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogCoreModulesFileUploadManager *create_ImDiyalogCoreModulesFileUploadManager_initWithACModuleContext_(id<ACModuleContext> context);

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogCoreModulesFileUploadManager)

#endif

#if !defined (ImDiyalogCoreModulesFileUploadManager_StartUpload_) && (INCLUDE_ALL_ImDiyalogCoreModulesFileUploadManager || defined(INCLUDE_ImDiyalogCoreModulesFileUploadManager_StartUpload))
#define ImDiyalogCoreModulesFileUploadManager_StartUpload_

@interface ImDiyalogCoreModulesFileUploadManager_StartUpload : NSObject

#pragma mark Public

- (instancetype)initWithLong:(jlong)rid
                withNSString:(NSString *)fileDescriptor
                withNSString:(NSString *)fileName;

- (NSString *)getFileDescriptor;

- (NSString *)getFileName;

- (jlong)getRid;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogCoreModulesFileUploadManager_StartUpload)

FOUNDATION_EXPORT void ImDiyalogCoreModulesFileUploadManager_StartUpload_initWithLong_withNSString_withNSString_(ImDiyalogCoreModulesFileUploadManager_StartUpload *self, jlong rid, NSString *fileDescriptor, NSString *fileName);

FOUNDATION_EXPORT ImDiyalogCoreModulesFileUploadManager_StartUpload *new_ImDiyalogCoreModulesFileUploadManager_StartUpload_initWithLong_withNSString_withNSString_(jlong rid, NSString *fileDescriptor, NSString *fileName) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogCoreModulesFileUploadManager_StartUpload *create_ImDiyalogCoreModulesFileUploadManager_StartUpload_initWithLong_withNSString_withNSString_(jlong rid, NSString *fileDescriptor, NSString *fileName);

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogCoreModulesFileUploadManager_StartUpload)

#endif

#if !defined (ImDiyalogCoreModulesFileUploadManager_BindUpload_) && (INCLUDE_ALL_ImDiyalogCoreModulesFileUploadManager || defined(INCLUDE_ImDiyalogCoreModulesFileUploadManager_BindUpload))
#define ImDiyalogCoreModulesFileUploadManager_BindUpload_

@protocol ACUploadFileCallback;

@interface ImDiyalogCoreModulesFileUploadManager_BindUpload : NSObject

#pragma mark Public

- (instancetype)initWithLong:(jlong)rid
    withACUploadFileCallback:(id<ACUploadFileCallback>)callback;

- (id<ACUploadFileCallback>)getCallback;

- (jlong)getRid;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogCoreModulesFileUploadManager_BindUpload)

FOUNDATION_EXPORT void ImDiyalogCoreModulesFileUploadManager_BindUpload_initWithLong_withACUploadFileCallback_(ImDiyalogCoreModulesFileUploadManager_BindUpload *self, jlong rid, id<ACUploadFileCallback> callback);

FOUNDATION_EXPORT ImDiyalogCoreModulesFileUploadManager_BindUpload *new_ImDiyalogCoreModulesFileUploadManager_BindUpload_initWithLong_withACUploadFileCallback_(jlong rid, id<ACUploadFileCallback> callback) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogCoreModulesFileUploadManager_BindUpload *create_ImDiyalogCoreModulesFileUploadManager_BindUpload_initWithLong_withACUploadFileCallback_(jlong rid, id<ACUploadFileCallback> callback);

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogCoreModulesFileUploadManager_BindUpload)

#endif

#if !defined (ImDiyalogCoreModulesFileUploadManager_UnbindUpload_) && (INCLUDE_ALL_ImDiyalogCoreModulesFileUploadManager || defined(INCLUDE_ImDiyalogCoreModulesFileUploadManager_UnbindUpload))
#define ImDiyalogCoreModulesFileUploadManager_UnbindUpload_

@protocol ACUploadFileCallback;

@interface ImDiyalogCoreModulesFileUploadManager_UnbindUpload : NSObject

#pragma mark Public

- (instancetype)initWithLong:(jlong)rid
    withACUploadFileCallback:(id<ACUploadFileCallback>)callback;

- (id<ACUploadFileCallback>)getCallback;

- (jlong)getRid;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogCoreModulesFileUploadManager_UnbindUpload)

FOUNDATION_EXPORT void ImDiyalogCoreModulesFileUploadManager_UnbindUpload_initWithLong_withACUploadFileCallback_(ImDiyalogCoreModulesFileUploadManager_UnbindUpload *self, jlong rid, id<ACUploadFileCallback> callback);

FOUNDATION_EXPORT ImDiyalogCoreModulesFileUploadManager_UnbindUpload *new_ImDiyalogCoreModulesFileUploadManager_UnbindUpload_initWithLong_withACUploadFileCallback_(jlong rid, id<ACUploadFileCallback> callback) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogCoreModulesFileUploadManager_UnbindUpload *create_ImDiyalogCoreModulesFileUploadManager_UnbindUpload_initWithLong_withACUploadFileCallback_(jlong rid, id<ACUploadFileCallback> callback);

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogCoreModulesFileUploadManager_UnbindUpload)

#endif

#if !defined (ImDiyalogCoreModulesFileUploadManager_StopUpload_) && (INCLUDE_ALL_ImDiyalogCoreModulesFileUploadManager || defined(INCLUDE_ImDiyalogCoreModulesFileUploadManager_StopUpload))
#define ImDiyalogCoreModulesFileUploadManager_StopUpload_

@interface ImDiyalogCoreModulesFileUploadManager_StopUpload : NSObject

#pragma mark Public

- (instancetype)initWithLong:(jlong)rid;

- (jlong)getRid;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogCoreModulesFileUploadManager_StopUpload)

FOUNDATION_EXPORT void ImDiyalogCoreModulesFileUploadManager_StopUpload_initWithLong_(ImDiyalogCoreModulesFileUploadManager_StopUpload *self, jlong rid);

FOUNDATION_EXPORT ImDiyalogCoreModulesFileUploadManager_StopUpload *new_ImDiyalogCoreModulesFileUploadManager_StopUpload_initWithLong_(jlong rid) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogCoreModulesFileUploadManager_StopUpload *create_ImDiyalogCoreModulesFileUploadManager_StopUpload_initWithLong_(jlong rid);

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogCoreModulesFileUploadManager_StopUpload)

#endif

#if !defined (ImDiyalogCoreModulesFileUploadManager_UploadTaskError_) && (INCLUDE_ALL_ImDiyalogCoreModulesFileUploadManager || defined(INCLUDE_ImDiyalogCoreModulesFileUploadManager_UploadTaskError))
#define ImDiyalogCoreModulesFileUploadManager_UploadTaskError_

@interface ImDiyalogCoreModulesFileUploadManager_UploadTaskError : NSObject

#pragma mark Public

- (instancetype)initWithLong:(jlong)rid;

- (jlong)getRid;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogCoreModulesFileUploadManager_UploadTaskError)

FOUNDATION_EXPORT void ImDiyalogCoreModulesFileUploadManager_UploadTaskError_initWithLong_(ImDiyalogCoreModulesFileUploadManager_UploadTaskError *self, jlong rid);

FOUNDATION_EXPORT ImDiyalogCoreModulesFileUploadManager_UploadTaskError *new_ImDiyalogCoreModulesFileUploadManager_UploadTaskError_initWithLong_(jlong rid) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogCoreModulesFileUploadManager_UploadTaskError *create_ImDiyalogCoreModulesFileUploadManager_UploadTaskError_initWithLong_(jlong rid);

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogCoreModulesFileUploadManager_UploadTaskError)

#endif

#if !defined (ImDiyalogCoreModulesFileUploadManager_UploadTaskProgress_) && (INCLUDE_ALL_ImDiyalogCoreModulesFileUploadManager || defined(INCLUDE_ImDiyalogCoreModulesFileUploadManager_UploadTaskProgress))
#define ImDiyalogCoreModulesFileUploadManager_UploadTaskProgress_

@interface ImDiyalogCoreModulesFileUploadManager_UploadTaskProgress : NSObject

#pragma mark Public

- (instancetype)initWithLong:(jlong)rid
                   withFloat:(jfloat)progress;

- (jfloat)getProgress;

- (jlong)getRid;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogCoreModulesFileUploadManager_UploadTaskProgress)

FOUNDATION_EXPORT void ImDiyalogCoreModulesFileUploadManager_UploadTaskProgress_initWithLong_withFloat_(ImDiyalogCoreModulesFileUploadManager_UploadTaskProgress *self, jlong rid, jfloat progress);

FOUNDATION_EXPORT ImDiyalogCoreModulesFileUploadManager_UploadTaskProgress *new_ImDiyalogCoreModulesFileUploadManager_UploadTaskProgress_initWithLong_withFloat_(jlong rid, jfloat progress) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogCoreModulesFileUploadManager_UploadTaskProgress *create_ImDiyalogCoreModulesFileUploadManager_UploadTaskProgress_initWithLong_withFloat_(jlong rid, jfloat progress);

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogCoreModulesFileUploadManager_UploadTaskProgress)

#endif

#if !defined (ImDiyalogCoreModulesFileUploadManager_UploadTaskComplete_) && (INCLUDE_ALL_ImDiyalogCoreModulesFileUploadManager || defined(INCLUDE_ImDiyalogCoreModulesFileUploadManager_UploadTaskComplete))
#define ImDiyalogCoreModulesFileUploadManager_UploadTaskComplete_

@class ACFileReference;
@protocol ARFileSystemReference;

@interface ImDiyalogCoreModulesFileUploadManager_UploadTaskComplete : NSObject

#pragma mark Public

- (instancetype)initWithLong:(jlong)rid
         withACFileReference:(ACFileReference *)location
   withARFileSystemReference:(id<ARFileSystemReference>)reference;

- (ACFileReference *)getLocation;

- (id<ARFileSystemReference>)getReference;

- (jlong)getRid;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogCoreModulesFileUploadManager_UploadTaskComplete)

FOUNDATION_EXPORT void ImDiyalogCoreModulesFileUploadManager_UploadTaskComplete_initWithLong_withACFileReference_withARFileSystemReference_(ImDiyalogCoreModulesFileUploadManager_UploadTaskComplete *self, jlong rid, ACFileReference *location, id<ARFileSystemReference> reference);

FOUNDATION_EXPORT ImDiyalogCoreModulesFileUploadManager_UploadTaskComplete *new_ImDiyalogCoreModulesFileUploadManager_UploadTaskComplete_initWithLong_withACFileReference_withARFileSystemReference_(jlong rid, ACFileReference *location, id<ARFileSystemReference> reference) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogCoreModulesFileUploadManager_UploadTaskComplete *create_ImDiyalogCoreModulesFileUploadManager_UploadTaskComplete_initWithLong_withACFileReference_withARFileSystemReference_(jlong rid, ACFileReference *location, id<ARFileSystemReference> reference);

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogCoreModulesFileUploadManager_UploadTaskComplete)

#endif

#if !defined (ImDiyalogCoreModulesFileUploadManager_UploadCompleted_) && (INCLUDE_ALL_ImDiyalogCoreModulesFileUploadManager || defined(INCLUDE_ImDiyalogCoreModulesFileUploadManager_UploadCompleted))
#define ImDiyalogCoreModulesFileUploadManager_UploadCompleted_

@class ACFileReference;

@interface ImDiyalogCoreModulesFileUploadManager_UploadCompleted : NSObject

#pragma mark Public

- (instancetype)initWithLong:(jlong)rid
         withACFileReference:(ACFileReference *)fileReference;

- (ACFileReference *)getFileReference;

- (jlong)getRid;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogCoreModulesFileUploadManager_UploadCompleted)

FOUNDATION_EXPORT void ImDiyalogCoreModulesFileUploadManager_UploadCompleted_initWithLong_withACFileReference_(ImDiyalogCoreModulesFileUploadManager_UploadCompleted *self, jlong rid, ACFileReference *fileReference);

FOUNDATION_EXPORT ImDiyalogCoreModulesFileUploadManager_UploadCompleted *new_ImDiyalogCoreModulesFileUploadManager_UploadCompleted_initWithLong_withACFileReference_(jlong rid, ACFileReference *fileReference) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogCoreModulesFileUploadManager_UploadCompleted *create_ImDiyalogCoreModulesFileUploadManager_UploadCompleted_initWithLong_withACFileReference_(jlong rid, ACFileReference *fileReference);

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogCoreModulesFileUploadManager_UploadCompleted)

#endif

#if !defined (ImDiyalogCoreModulesFileUploadManager_UploadError_) && (INCLUDE_ALL_ImDiyalogCoreModulesFileUploadManager || defined(INCLUDE_ImDiyalogCoreModulesFileUploadManager_UploadError))
#define ImDiyalogCoreModulesFileUploadManager_UploadError_

@interface ImDiyalogCoreModulesFileUploadManager_UploadError : NSObject

#pragma mark Public

- (instancetype)initWithLong:(jlong)rid;

- (jlong)getRid;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogCoreModulesFileUploadManager_UploadError)

FOUNDATION_EXPORT void ImDiyalogCoreModulesFileUploadManager_UploadError_initWithLong_(ImDiyalogCoreModulesFileUploadManager_UploadError *self, jlong rid);

FOUNDATION_EXPORT ImDiyalogCoreModulesFileUploadManager_UploadError *new_ImDiyalogCoreModulesFileUploadManager_UploadError_initWithLong_(jlong rid) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogCoreModulesFileUploadManager_UploadError *create_ImDiyalogCoreModulesFileUploadManager_UploadError_initWithLong_(jlong rid);

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogCoreModulesFileUploadManager_UploadError)

#endif

#if !defined (ImDiyalogCoreModulesFileUploadManager_RequestState_) && (INCLUDE_ALL_ImDiyalogCoreModulesFileUploadManager || defined(INCLUDE_ImDiyalogCoreModulesFileUploadManager_RequestState))
#define ImDiyalogCoreModulesFileUploadManager_RequestState_

@protocol ACUploadFileCallback;

@interface ImDiyalogCoreModulesFileUploadManager_RequestState : NSObject

#pragma mark Public

- (instancetype)initWithLong:(jlong)rid
    withACUploadFileCallback:(id<ACUploadFileCallback>)callback;

- (id<ACUploadFileCallback>)getCallback;

- (jlong)getRid;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogCoreModulesFileUploadManager_RequestState)

FOUNDATION_EXPORT void ImDiyalogCoreModulesFileUploadManager_RequestState_initWithLong_withACUploadFileCallback_(ImDiyalogCoreModulesFileUploadManager_RequestState *self, jlong rid, id<ACUploadFileCallback> callback);

FOUNDATION_EXPORT ImDiyalogCoreModulesFileUploadManager_RequestState *new_ImDiyalogCoreModulesFileUploadManager_RequestState_initWithLong_withACUploadFileCallback_(jlong rid, id<ACUploadFileCallback> callback) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogCoreModulesFileUploadManager_RequestState *create_ImDiyalogCoreModulesFileUploadManager_RequestState_initWithLong_withACUploadFileCallback_(jlong rid, id<ACUploadFileCallback> callback);

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogCoreModulesFileUploadManager_RequestState)

#endif

#if !defined (ImDiyalogCoreModulesFileUploadManager_PauseUpload_) && (INCLUDE_ALL_ImDiyalogCoreModulesFileUploadManager || defined(INCLUDE_ImDiyalogCoreModulesFileUploadManager_PauseUpload))
#define ImDiyalogCoreModulesFileUploadManager_PauseUpload_

@interface ImDiyalogCoreModulesFileUploadManager_PauseUpload : NSObject

#pragma mark Public

- (instancetype)initWithLong:(jlong)rid;

- (jlong)getRid;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogCoreModulesFileUploadManager_PauseUpload)

FOUNDATION_EXPORT void ImDiyalogCoreModulesFileUploadManager_PauseUpload_initWithLong_(ImDiyalogCoreModulesFileUploadManager_PauseUpload *self, jlong rid);

FOUNDATION_EXPORT ImDiyalogCoreModulesFileUploadManager_PauseUpload *new_ImDiyalogCoreModulesFileUploadManager_PauseUpload_initWithLong_(jlong rid) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogCoreModulesFileUploadManager_PauseUpload *create_ImDiyalogCoreModulesFileUploadManager_PauseUpload_initWithLong_(jlong rid);

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogCoreModulesFileUploadManager_PauseUpload)

#endif

#if !defined (ImDiyalogCoreModulesFileUploadManager_ResumeUpload_) && (INCLUDE_ALL_ImDiyalogCoreModulesFileUploadManager || defined(INCLUDE_ImDiyalogCoreModulesFileUploadManager_ResumeUpload))
#define ImDiyalogCoreModulesFileUploadManager_ResumeUpload_

@interface ImDiyalogCoreModulesFileUploadManager_ResumeUpload : NSObject

#pragma mark Public

- (instancetype)initWithLong:(jlong)rid;

- (jlong)getRid;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogCoreModulesFileUploadManager_ResumeUpload)

FOUNDATION_EXPORT void ImDiyalogCoreModulesFileUploadManager_ResumeUpload_initWithLong_(ImDiyalogCoreModulesFileUploadManager_ResumeUpload *self, jlong rid);

FOUNDATION_EXPORT ImDiyalogCoreModulesFileUploadManager_ResumeUpload *new_ImDiyalogCoreModulesFileUploadManager_ResumeUpload_initWithLong_(jlong rid) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogCoreModulesFileUploadManager_ResumeUpload *create_ImDiyalogCoreModulesFileUploadManager_ResumeUpload_initWithLong_(jlong rid);

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogCoreModulesFileUploadManager_ResumeUpload)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreModulesFileUploadManager")
