//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/network/mtp/entity/ProtoSerializer.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreNetworkMtpEntityProtoSerializer")
#ifdef RESTRICT_ImDiyalogCoreNetworkMtpEntityProtoSerializer
#define INCLUDE_ALL_ImDiyalogCoreNetworkMtpEntityProtoSerializer 0
#else
#define INCLUDE_ALL_ImDiyalogCoreNetworkMtpEntityProtoSerializer 1
#endif
#undef RESTRICT_ImDiyalogCoreNetworkMtpEntityProtoSerializer

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ACProtoSerializer_) && (INCLUDE_ALL_ImDiyalogCoreNetworkMtpEntityProtoSerializer || defined(INCLUDE_ACProtoSerializer))
#define ACProtoSerializer_

@class ACProtoStruct;
@class ACPush;
@class ARDataInput;
@class IOSByteArray;

@interface ACProtoSerializer : NSObject

#pragma mark Public

- (instancetype)init;

+ (ACProtoStruct *)readMessagePayloadWithByteArray:(IOSByteArray *)bs;

+ (ACProtoStruct *)readMessagePayloadWithARDataInput:(ARDataInput *)bs;

+ (ACProtoStruct *)readRpcRequestPayloadWithARDataInput:(ARDataInput *)bs;

+ (ACProtoStruct *)readRpcResponsePayloadWithByteArray:(IOSByteArray *)data;

+ (ACPush *)readUpdateWithByteArray:(IOSByteArray *)bs;

+ (ACPush *)readUpdateWithARDataInput:(ARDataInput *)bs;

@end

J2OBJC_EMPTY_STATIC_INIT(ACProtoSerializer)

FOUNDATION_EXPORT ACProtoStruct *ACProtoSerializer_readMessagePayloadWithByteArray_(IOSByteArray *bs);

FOUNDATION_EXPORT ACProtoStruct *ACProtoSerializer_readMessagePayloadWithARDataInput_(ARDataInput *bs);

FOUNDATION_EXPORT ACProtoStruct *ACProtoSerializer_readRpcResponsePayloadWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT ACProtoStruct *ACProtoSerializer_readRpcRequestPayloadWithARDataInput_(ARDataInput *bs);

FOUNDATION_EXPORT ACPush *ACProtoSerializer_readUpdateWithByteArray_(IOSByteArray *bs);

FOUNDATION_EXPORT ACPush *ACProtoSerializer_readUpdateWithARDataInput_(ARDataInput *bs);

FOUNDATION_EXPORT void ACProtoSerializer_init(ACProtoSerializer *self);

FOUNDATION_EXPORT ACProtoSerializer *new_ACProtoSerializer_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACProtoSerializer *create_ACProtoSerializer_init();

J2OBJC_TYPE_LITERAL_HEADER(ACProtoSerializer)

@compatibility_alias ImDiyalogCoreNetworkMtpEntityProtoSerializer ACProtoSerializer;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreNetworkMtpEntityProtoSerializer")
