//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/runtime/runtime-shared/src/main/java/im/diyalog/runtime/actors/dispatch/queue/QueueFetchResult.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogRuntimeActorsDispatchQueueQueueFetchResult")
#ifdef RESTRICT_ImDiyalogRuntimeActorsDispatchQueueQueueFetchResult
#define INCLUDE_ALL_ImDiyalogRuntimeActorsDispatchQueueQueueFetchResult 0
#else
#define INCLUDE_ALL_ImDiyalogRuntimeActorsDispatchQueueQueueFetchResult 1
#endif
#undef RESTRICT_ImDiyalogRuntimeActorsDispatchQueueQueueFetchResult

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImDiyalogRuntimeActorsDispatchQueueQueueFetchResult_) && (INCLUDE_ALL_ImDiyalogRuntimeActorsDispatchQueueQueueFetchResult || defined(INCLUDE_ImDiyalogRuntimeActorsDispatchQueueQueueFetchResult))
#define ImDiyalogRuntimeActorsDispatchQueueQueueFetchResult_

@interface ImDiyalogRuntimeActorsDispatchQueueQueueFetchResult : NSObject

#pragma mark Public

- (instancetype)initWithInt:(jint)id_
                     withId:(id)val;

- (jint)getId;

- (id)getVal;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogRuntimeActorsDispatchQueueQueueFetchResult)

FOUNDATION_EXPORT void ImDiyalogRuntimeActorsDispatchQueueQueueFetchResult_initWithInt_withId_(ImDiyalogRuntimeActorsDispatchQueueQueueFetchResult *self, jint id_, id val);

FOUNDATION_EXPORT ImDiyalogRuntimeActorsDispatchQueueQueueFetchResult *new_ImDiyalogRuntimeActorsDispatchQueueQueueFetchResult_initWithInt_withId_(jint id_, id val) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogRuntimeActorsDispatchQueueQueueFetchResult *create_ImDiyalogRuntimeActorsDispatchQueueQueueFetchResult_initWithInt_withId_(jint id_, id val);

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogRuntimeActorsDispatchQueueQueueFetchResult)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogRuntimeActorsDispatchQueueQueueFetchResult")
