//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/runtime/runtime-shared/src/main/java/im/diyalog/runtime/promise/PromiseDispatcher.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogRuntimePromisePromiseDispatcher")
#ifdef RESTRICT_ImDiyalogRuntimePromisePromiseDispatcher
#define INCLUDE_ALL_ImDiyalogRuntimePromisePromiseDispatcher 0
#else
#define INCLUDE_ALL_ImDiyalogRuntimePromisePromiseDispatcher 1
#endif
#undef RESTRICT_ImDiyalogRuntimePromisePromiseDispatcher

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARPromiseDispatcher_) && (INCLUDE_ALL_ImDiyalogRuntimePromisePromiseDispatcher || defined(INCLUDE_ARPromiseDispatcher))
#define ARPromiseDispatcher_

@class ARPromise;
@protocol JavaLangRunnable;

@interface ARPromiseDispatcher : NSObject

#pragma mark Public

- (instancetype)init;

- (void)dispatchWithARPromise:(ARPromise *)promise
         withJavaLangRunnable:(id<JavaLangRunnable>)runnable;

@end

J2OBJC_EMPTY_STATIC_INIT(ARPromiseDispatcher)

FOUNDATION_EXPORT void ARPromiseDispatcher_init(ARPromiseDispatcher *self);

J2OBJC_TYPE_LITERAL_HEADER(ARPromiseDispatcher)

@compatibility_alias ImDiyalogRuntimePromisePromiseDispatcher ARPromiseDispatcher;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogRuntimePromisePromiseDispatcher")
