//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/runtime/runtime-shared/src/main/java/im/diyalog/runtime/crypto/primitives/curve25519/ge_p3.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogRuntimeCryptoPrimitivesCurve25519Ge_p3")
#ifdef RESTRICT_ImDiyalogRuntimeCryptoPrimitivesCurve25519Ge_p3
#define INCLUDE_ALL_ImDiyalogRuntimeCryptoPrimitivesCurve25519Ge_p3 0
#else
#define INCLUDE_ALL_ImDiyalogRuntimeCryptoPrimitivesCurve25519Ge_p3 1
#endif
#undef RESTRICT_ImDiyalogRuntimeCryptoPrimitivesCurve25519Ge_p3

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImDiyalogRuntimeCryptoPrimitivesCurve25519ge_p3_) && (INCLUDE_ALL_ImDiyalogRuntimeCryptoPrimitivesCurve25519Ge_p3 || defined(INCLUDE_ImDiyalogRuntimeCryptoPrimitivesCurve25519ge_p3))
#define ImDiyalogRuntimeCryptoPrimitivesCurve25519ge_p3_

@class IOSIntArray;

@interface ImDiyalogRuntimeCryptoPrimitivesCurve25519ge_p3 : NSObject {
 @public
  IOSIntArray *X_;
  IOSIntArray *Y_;
  IOSIntArray *Z_;
  IOSIntArray *T_;
}

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogRuntimeCryptoPrimitivesCurve25519ge_p3)

J2OBJC_FIELD_SETTER(ImDiyalogRuntimeCryptoPrimitivesCurve25519ge_p3, X_, IOSIntArray *)
J2OBJC_FIELD_SETTER(ImDiyalogRuntimeCryptoPrimitivesCurve25519ge_p3, Y_, IOSIntArray *)
J2OBJC_FIELD_SETTER(ImDiyalogRuntimeCryptoPrimitivesCurve25519ge_p3, Z_, IOSIntArray *)
J2OBJC_FIELD_SETTER(ImDiyalogRuntimeCryptoPrimitivesCurve25519ge_p3, T_, IOSIntArray *)

FOUNDATION_EXPORT void ImDiyalogRuntimeCryptoPrimitivesCurve25519ge_p3_init(ImDiyalogRuntimeCryptoPrimitivesCurve25519ge_p3 *self);

FOUNDATION_EXPORT ImDiyalogRuntimeCryptoPrimitivesCurve25519ge_p3 *new_ImDiyalogRuntimeCryptoPrimitivesCurve25519ge_p3_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogRuntimeCryptoPrimitivesCurve25519ge_p3 *create_ImDiyalogRuntimeCryptoPrimitivesCurve25519ge_p3_init();

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogRuntimeCryptoPrimitivesCurve25519ge_p3)

@compatibility_alias ImDiyalogRuntimeCryptoPrimitivesCurve25519Ge_p3 ImDiyalogRuntimeCryptoPrimitivesCurve25519ge_p3;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogRuntimeCryptoPrimitivesCurve25519Ge_p3")
