//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/modules/misc/DeviceInfoModule.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreModulesMiscDeviceInfoModule")
#ifdef RESTRICT_ImDiyalogCoreModulesMiscDeviceInfoModule
#define INCLUDE_ALL_ImDiyalogCoreModulesMiscDeviceInfoModule 0
#else
#define INCLUDE_ALL_ImDiyalogCoreModulesMiscDeviceInfoModule 1
#endif
#undef RESTRICT_ImDiyalogCoreModulesMiscDeviceInfoModule

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImDiyalogCoreModulesMiscDeviceInfoModule_) && (INCLUDE_ALL_ImDiyalogCoreModulesMiscDeviceInfoModule || defined(INCLUDE_ImDiyalogCoreModulesMiscDeviceInfoModule))
#define ImDiyalogCoreModulesMiscDeviceInfoModule_

#define RESTRICT_ImDiyalogCoreModulesAbsModule 1
#define INCLUDE_ACAbsModule 1
#include "../../../../../im/diyalog/core/modules/AbsModule.h"

@protocol ACModuleContext;

@interface ImDiyalogCoreModulesMiscDeviceInfoModule : ACAbsModule

#pragma mark Public

- (instancetype)initWithACModuleContext:(id<ACModuleContext>)context;

- (void)run;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogCoreModulesMiscDeviceInfoModule)

FOUNDATION_EXPORT void ImDiyalogCoreModulesMiscDeviceInfoModule_initWithACModuleContext_(ImDiyalogCoreModulesMiscDeviceInfoModule *self, id<ACModuleContext> context);

FOUNDATION_EXPORT ImDiyalogCoreModulesMiscDeviceInfoModule *new_ImDiyalogCoreModulesMiscDeviceInfoModule_initWithACModuleContext_(id<ACModuleContext> context) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogCoreModulesMiscDeviceInfoModule *create_ImDiyalogCoreModulesMiscDeviceInfoModule_initWithACModuleContext_(id<ACModuleContext> context);

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogCoreModulesMiscDeviceInfoModule)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreModulesMiscDeviceInfoModule")
