//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/modules/usagetracker/usages/UsageEvent.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreModulesUsagetrackerUsagesUsageEvent")
#ifdef RESTRICT_ImDiyalogCoreModulesUsagetrackerUsagesUsageEvent
#define INCLUDE_ALL_ImDiyalogCoreModulesUsagetrackerUsagesUsageEvent 0
#else
#define INCLUDE_ALL_ImDiyalogCoreModulesUsagetrackerUsagesUsageEvent 1
#endif
#undef RESTRICT_ImDiyalogCoreModulesUsagetrackerUsagesUsageEvent

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImDiyalogCoreModulesUsagetrackerUsagesUsageEvent_) && (INCLUDE_ALL_ImDiyalogCoreModulesUsagetrackerUsagesUsageEvent || defined(INCLUDE_ImDiyalogCoreModulesUsagetrackerUsagesUsageEvent))
#define ImDiyalogCoreModulesUsagetrackerUsagesUsageEvent_

@interface ImDiyalogCoreModulesUsagetrackerUsagesUsageEvent : NSObject {
 @public
  jlong pressedTime_;
}

#pragma mark Public

- (instancetype)init;

- (jlong)getPressedTime;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogCoreModulesUsagetrackerUsagesUsageEvent)

FOUNDATION_EXPORT void ImDiyalogCoreModulesUsagetrackerUsagesUsageEvent_init(ImDiyalogCoreModulesUsagetrackerUsagesUsageEvent *self);

FOUNDATION_EXPORT ImDiyalogCoreModulesUsagetrackerUsagesUsageEvent *new_ImDiyalogCoreModulesUsagetrackerUsagesUsageEvent_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogCoreModulesUsagetrackerUsagesUsageEvent *create_ImDiyalogCoreModulesUsagetrackerUsagesUsageEvent_init();

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogCoreModulesUsagetrackerUsagesUsageEvent)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreModulesUsagetrackerUsagesUsageEvent")
