//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/entity/content/internal/LocalFastThumb.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreEntityContentInternalLocalFastThumb")
#ifdef RESTRICT_ImDiyalogCoreEntityContentInternalLocalFastThumb
#define INCLUDE_ALL_ImDiyalogCoreEntityContentInternalLocalFastThumb 0
#else
#define INCLUDE_ALL_ImDiyalogCoreEntityContentInternalLocalFastThumb 1
#endif
#undef RESTRICT_ImDiyalogCoreEntityContentInternalLocalFastThumb

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ACLocalFastThumb_) && (INCLUDE_ALL_ImDiyalogCoreEntityContentInternalLocalFastThumb || defined(INCLUDE_ACLocalFastThumb))
#define ACLocalFastThumb_

#define RESTRICT_ImDiyalogRuntimeBserBserObject 1
#define INCLUDE_ARBserObject 1
#include "../../../../../../im/diyalog/runtime/bser/BserObject.h"

@class ACFastThumb;
@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

@interface ACLocalFastThumb : ARBserObject

#pragma mark Public

- (instancetype)initWithByteArray:(IOSByteArray *)data;

- (instancetype)initWithACFastThumb:(ACFastThumb *)fastThumb;

- (instancetype)initWithInt:(jint)w
                    withInt:(jint)h
              withByteArray:(IOSByteArray *)image;

- (jint)getH;

- (IOSByteArray *)getImage;

- (jint)getW;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

@end

J2OBJC_EMPTY_STATIC_INIT(ACLocalFastThumb)

FOUNDATION_EXPORT void ACLocalFastThumb_initWithACFastThumb_(ACLocalFastThumb *self, ACFastThumb *fastThumb);

FOUNDATION_EXPORT ACLocalFastThumb *new_ACLocalFastThumb_initWithACFastThumb_(ACFastThumb *fastThumb) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACLocalFastThumb *create_ACLocalFastThumb_initWithACFastThumb_(ACFastThumb *fastThumb);

FOUNDATION_EXPORT void ACLocalFastThumb_initWithInt_withInt_withByteArray_(ACLocalFastThumb *self, jint w, jint h, IOSByteArray *image);

FOUNDATION_EXPORT ACLocalFastThumb *new_ACLocalFastThumb_initWithInt_withInt_withByteArray_(jint w, jint h, IOSByteArray *image) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACLocalFastThumb *create_ACLocalFastThumb_initWithInt_withInt_withByteArray_(jint w, jint h, IOSByteArray *image);

FOUNDATION_EXPORT void ACLocalFastThumb_initWithByteArray_(ACLocalFastThumb *self, IOSByteArray *data);

FOUNDATION_EXPORT ACLocalFastThumb *new_ACLocalFastThumb_initWithByteArray_(IOSByteArray *data) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACLocalFastThumb *create_ACLocalFastThumb_initWithByteArray_(IOSByteArray *data);

J2OBJC_TYPE_LITERAL_HEADER(ACLocalFastThumb)

@compatibility_alias ImDiyalogCoreEntityContentInternalLocalFastThumb ACLocalFastThumb;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreEntityContentInternalLocalFastThumb")
