//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/runtime/runtime-shared/src/main/java/im/diyalog/runtime/storage/ListEngineDisplayExt.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogRuntimeStorageListEngineDisplayExt")
#ifdef RESTRICT_ImDiyalogRuntimeStorageListEngineDisplayExt
#define INCLUDE_ALL_ImDiyalogRuntimeStorageListEngineDisplayExt 0
#else
#define INCLUDE_ALL_ImDiyalogRuntimeStorageListEngineDisplayExt 1
#endif
#undef RESTRICT_ImDiyalogRuntimeStorageListEngineDisplayExt

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARListEngineDisplayExt_) && (INCLUDE_ALL_ImDiyalogRuntimeStorageListEngineDisplayExt || defined(INCLUDE_ARListEngineDisplayExt))
#define ARListEngineDisplayExt_

#define RESTRICT_ImDiyalogRuntimeStorageListEngine 1
#define INCLUDE_ARListEngine 1
#include "../../../../im/diyalog/runtime/storage/ListEngine.h"

@protocol ARListEngineDisplayListener;
@protocol ARListEngineDisplayLoadCallback;

@protocol ARListEngineDisplayExt < ARListEngine, NSObject, JavaObject >

- (void)subscribeWithListener:(id<ARListEngineDisplayListener>)listener;

- (void)unsubscribeWithListener:(id<ARListEngineDisplayListener>)listener;

- (void)loadForwardWithLimit:(jint)limit
                withCallback:(id<ARListEngineDisplayLoadCallback>)callback;

- (void)loadForwardAfterSortKey:(jlong)afterSortKey
                      withLimit:(jint)limit
                   withCallback:(id<ARListEngineDisplayLoadCallback>)callback;

- (void)loadForwardWithQuery:(NSString *)query
                   withLimit:(jint)limit
                withCallback:(id<ARListEngineDisplayLoadCallback>)callback;

- (void)loadForwardWithQuery:(NSString *)query
                afterSortKey:(jlong)afterSortKey
                   withLimit:(jint)limit
                withCallback:(id<ARListEngineDisplayLoadCallback>)callback;

- (void)loadBackwardWithLimit:(jint)limit
                 withCallback:(id<ARListEngineDisplayLoadCallback>)callback;

- (void)loadBackwardBeforeSortKey:(jlong)beforeSortKey
                        withLimit:(jint)limit
                     withCallback:(id<ARListEngineDisplayLoadCallback>)callback;

- (void)loadBackwardWithQuery:(NSString *)query
                    withLimit:(jint)limit
                 withCallback:(id<ARListEngineDisplayLoadCallback>)callback;

- (void)loadBackwardWithQuery:(NSString *)query
                beforeSortKey:(jlong)beforeSortKey
                    withLimit:(jint)limit
                 withCallback:(id<ARListEngineDisplayLoadCallback>)callback;

- (void)loadCenterWithSortKey:(jlong)centerSortKey
                    withLimit:(jint)limit
                 withCallback:(id<ARListEngineDisplayLoadCallback>)callback;

@end

J2OBJC_EMPTY_STATIC_INIT(ARListEngineDisplayExt)

J2OBJC_TYPE_LITERAL_HEADER(ARListEngineDisplayExt)

#define ImDiyalogRuntimeStorageListEngineDisplayExt ARListEngineDisplayExt

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogRuntimeStorageListEngineDisplayExt")
