//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/api/ApiContactRecord.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreApiApiContactRecord")
#ifdef RESTRICT_ImDiyalogCoreApiApiContactRecord
#define INCLUDE_ALL_ImDiyalogCoreApiApiContactRecord 0
#else
#define INCLUDE_ALL_ImDiyalogCoreApiApiContactRecord 1
#endif
#undef RESTRICT_ImDiyalogCoreApiApiContactRecord

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARApiContactRecord_) && (INCLUDE_ALL_ImDiyalogCoreApiApiContactRecord || defined(INCLUDE_ARApiContactRecord))
#define ARApiContactRecord_

#define RESTRICT_ImDiyalogRuntimeBserBserObject 1
#define INCLUDE_ARBserObject 1
#include "../../../../im/diyalog/runtime/bser/BserObject.h"

@class ARApiContactType;
@class ARBserValues;
@class ARBserWriter;
@class JavaLangLong;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARApiContactRecord : ARBserObject

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithARApiContactType:(ARApiContactType * __nonnull)type
                            withNSString:(NSString * __nullable)typeSpec
                            withNSString:(NSString * __nullable)stringValue
                        withJavaLangLong:(JavaLangLong * __nullable)longValue
                            withNSString:(NSString * __nullable)title
                            withNSString:(NSString * __nullable)subtitle;

- (JavaLangLong * __nullable)getLongValue;

- (NSString * __nullable)getStringValue;

- (NSString * __nullable)getSubtitle;

- (NSString * __nullable)getTitle;

- (ARApiContactType * __nonnull)getType;

- (NSString * __nullable)getTypeSpec;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARApiContactRecord)

FOUNDATION_EXPORT void ARApiContactRecord_initWithARApiContactType_withNSString_withNSString_withJavaLangLong_withNSString_withNSString_(ARApiContactRecord *self, ARApiContactType *type, NSString *typeSpec, NSString *stringValue, JavaLangLong *longValue, NSString *title, NSString *subtitle);

FOUNDATION_EXPORT ARApiContactRecord *new_ARApiContactRecord_initWithARApiContactType_withNSString_withNSString_withJavaLangLong_withNSString_withNSString_(ARApiContactType *type, NSString *typeSpec, NSString *stringValue, JavaLangLong *longValue, NSString *title, NSString *subtitle) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARApiContactRecord *create_ARApiContactRecord_initWithARApiContactType_withNSString_withNSString_withJavaLangLong_withNSString_withNSString_(ARApiContactType *type, NSString *typeSpec, NSString *stringValue, JavaLangLong *longValue, NSString *title, NSString *subtitle);

FOUNDATION_EXPORT void ARApiContactRecord_init(ARApiContactRecord *self);

FOUNDATION_EXPORT ARApiContactRecord *new_ARApiContactRecord_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARApiContactRecord *create_ARApiContactRecord_init();

J2OBJC_TYPE_LITERAL_HEADER(ARApiContactRecord)

@compatibility_alias ImDiyalogCoreApiApiContactRecord ARApiContactRecord;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreApiApiContactRecord")
