//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/api/ApiConfig.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreApiApiConfig")
#ifdef RESTRICT_ImDiyalogCoreApiApiConfig
#define INCLUDE_ALL_ImDiyalogCoreApiApiConfig 0
#else
#define INCLUDE_ALL_ImDiyalogCoreApiApiConfig 1
#endif
#undef RESTRICT_ImDiyalogCoreApiApiConfig

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARApiConfig_) && (INCLUDE_ALL_ImDiyalogCoreApiApiConfig || defined(INCLUDE_ARApiConfig))
#define ARApiConfig_

#define RESTRICT_ImDiyalogRuntimeBserBserObject 1
#define INCLUDE_ARBserObject 1
#include "../../../../im/diyalog/runtime/bser/BserObject.h"

@class ARBserValues;
@class ARBserWriter;

@interface ARApiConfig : ARBserObject

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithInt:(jint)maxGroupSize;

- (jint)getMaxGroupSize;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARApiConfig)

FOUNDATION_EXPORT void ARApiConfig_initWithInt_(ARApiConfig *self, jint maxGroupSize);

FOUNDATION_EXPORT ARApiConfig *new_ARApiConfig_initWithInt_(jint maxGroupSize) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARApiConfig *create_ARApiConfig_initWithInt_(jint maxGroupSize);

FOUNDATION_EXPORT void ARApiConfig_init(ARApiConfig *self);

FOUNDATION_EXPORT ARApiConfig *new_ARApiConfig_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARApiConfig *create_ARApiConfig_init();

J2OBJC_TYPE_LITERAL_HEADER(ARApiConfig)

@compatibility_alias ImDiyalogCoreApiApiConfig ARApiConfig;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreApiApiConfig")
