//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/api/ApiParameter.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreApiApiParameter")
#ifdef RESTRICT_ImDiyalogCoreApiApiParameter
#define INCLUDE_ALL_ImDiyalogCoreApiApiParameter 0
#else
#define INCLUDE_ALL_ImDiyalogCoreApiApiParameter 1
#endif
#undef RESTRICT_ImDiyalogCoreApiApiParameter

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARApiParameter_) && (INCLUDE_ALL_ImDiyalogCoreApiApiParameter || defined(INCLUDE_ARApiParameter))
#define ARApiParameter_

#define RESTRICT_ImDiyalogRuntimeBserBserObject 1
#define INCLUDE_ARBserObject 1
#include "../../../../im/diyalog/runtime/bser/BserObject.h"

@class ARBserValues;
@class ARBserWriter;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARApiParameter : ARBserObject

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString * __nonnull)key
                    withNSString:(NSString * __nonnull)value;

- (NSString * __nonnull)getKey;

- (NSString * __nonnull)getValue;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARApiParameter)

FOUNDATION_EXPORT void ARApiParameter_initWithNSString_withNSString_(ARApiParameter *self, NSString *key, NSString *value);

FOUNDATION_EXPORT ARApiParameter *new_ARApiParameter_initWithNSString_withNSString_(NSString *key, NSString *value) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARApiParameter *create_ARApiParameter_initWithNSString_withNSString_(NSString *key, NSString *value);

FOUNDATION_EXPORT void ARApiParameter_init(ARApiParameter *self);

FOUNDATION_EXPORT ARApiParameter *new_ARApiParameter_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARApiParameter *create_ARApiParameter_init();

J2OBJC_TYPE_LITERAL_HEADER(ARApiParameter)

@compatibility_alias ImDiyalogCoreApiApiParameter ARApiParameter;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreApiApiParameter")
