//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/api/ApiRawValueUnsupported.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreApiApiRawValueUnsupported")
#ifdef RESTRICT_ImDiyalogCoreApiApiRawValueUnsupported
#define INCLUDE_ALL_ImDiyalogCoreApiApiRawValueUnsupported 0
#else
#define INCLUDE_ALL_ImDiyalogCoreApiApiRawValueUnsupported 1
#endif
#undef RESTRICT_ImDiyalogCoreApiApiRawValueUnsupported

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARApiRawValueUnsupported_) && (INCLUDE_ALL_ImDiyalogCoreApiApiRawValueUnsupported || defined(INCLUDE_ARApiRawValueUnsupported))
#define ARApiRawValueUnsupported_

#define RESTRICT_ImDiyalogCoreApiApiRawValue 1
#define INCLUDE_ARApiRawValue 1
#include "../../../../im/diyalog/core/api/ApiRawValue.h"

@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

@interface ARApiRawValueUnsupported : ARApiRawValue

#pragma mark Public

- (instancetype)initWithInt:(jint)key
              withByteArray:(IOSByteArray *)content;

- (jint)getHeader;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

@end

J2OBJC_EMPTY_STATIC_INIT(ARApiRawValueUnsupported)

FOUNDATION_EXPORT void ARApiRawValueUnsupported_initWithInt_withByteArray_(ARApiRawValueUnsupported *self, jint key, IOSByteArray *content);

FOUNDATION_EXPORT ARApiRawValueUnsupported *new_ARApiRawValueUnsupported_initWithInt_withByteArray_(jint key, IOSByteArray *content) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARApiRawValueUnsupported *create_ARApiRawValueUnsupported_initWithInt_withByteArray_(jint key, IOSByteArray *content);

J2OBJC_TYPE_LITERAL_HEADER(ARApiRawValueUnsupported)

@compatibility_alias ImDiyalogCoreApiApiRawValueUnsupported ARApiRawValueUnsupported;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreApiApiRawValueUnsupported")
