//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/api/ApiSearchPeerCondition.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreApiApiSearchPeerCondition")
#ifdef RESTRICT_ImDiyalogCoreApiApiSearchPeerCondition
#define INCLUDE_ALL_ImDiyalogCoreApiApiSearchPeerCondition 0
#else
#define INCLUDE_ALL_ImDiyalogCoreApiApiSearchPeerCondition 1
#endif
#undef RESTRICT_ImDiyalogCoreApiApiSearchPeerCondition

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARApiSearchPeerCondition_) && (INCLUDE_ALL_ImDiyalogCoreApiApiSearchPeerCondition || defined(INCLUDE_ARApiSearchPeerCondition))
#define ARApiSearchPeerCondition_

#define RESTRICT_ImDiyalogCoreApiApiSearchCondition 1
#define INCLUDE_ARApiSearchCondition 1
#include "../../../../im/diyalog/core/api/ApiSearchCondition.h"

@class ARApiOutPeer;
@class ARBserValues;
@class ARBserWriter;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface ARApiSearchPeerCondition : ARApiSearchCondition

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithARApiOutPeer:(ARApiOutPeer * __nonnull)peer;

- (jint)getHeader;

- (ARApiOutPeer * __nonnull)getPeer;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARApiSearchPeerCondition)

FOUNDATION_EXPORT void ARApiSearchPeerCondition_initWithARApiOutPeer_(ARApiSearchPeerCondition *self, ARApiOutPeer *peer);

FOUNDATION_EXPORT ARApiSearchPeerCondition *new_ARApiSearchPeerCondition_initWithARApiOutPeer_(ARApiOutPeer *peer) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARApiSearchPeerCondition *create_ARApiSearchPeerCondition_initWithARApiOutPeer_(ARApiOutPeer *peer);

FOUNDATION_EXPORT void ARApiSearchPeerCondition_init(ARApiSearchPeerCondition *self);

FOUNDATION_EXPORT ARApiSearchPeerCondition *new_ARApiSearchPeerCondition_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARApiSearchPeerCondition *create_ARApiSearchPeerCondition_init();

J2OBJC_TYPE_LITERAL_HEADER(ARApiSearchPeerCondition)

@compatibility_alias ImDiyalogCoreApiApiSearchPeerCondition ARApiSearchPeerCondition;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreApiApiSearchPeerCondition")
