//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/util/PreferenceApiStorage.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreUtilPreferenceApiStorage")
#ifdef RESTRICT_ImDiyalogCoreUtilPreferenceApiStorage
#define INCLUDE_ALL_ImDiyalogCoreUtilPreferenceApiStorage 0
#else
#define INCLUDE_ALL_ImDiyalogCoreUtilPreferenceApiStorage 1
#endif
#undef RESTRICT_ImDiyalogCoreUtilPreferenceApiStorage

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ACPreferenceApiStorage_) && (INCLUDE_ALL_ImDiyalogCoreUtilPreferenceApiStorage || defined(INCLUDE_ACPreferenceApiStorage))
#define ACPreferenceApiStorage_

#define RESTRICT_ImDiyalogCoreNetworkAuthKeyStorage 1
#define INCLUDE_ACAuthKeyStorage 1
#include "../../../../im/diyalog/core/network/AuthKeyStorage.h"

@class IOSByteArray;
@protocol ARPreferencesStorage;

@interface ACPreferenceApiStorage : NSObject < ACAuthKeyStorage >

#pragma mark Public

- (instancetype)initWithARPreferencesStorage:(id<ARPreferencesStorage>)preferencesStorage;

- (jlong)getAuthKey;

- (IOSByteArray *)getAuthMasterKey;

- (void)saveAuthKey:(jlong)key;

- (void)saveMasterKey:(IOSByteArray *)masterKey;

@end

J2OBJC_EMPTY_STATIC_INIT(ACPreferenceApiStorage)

FOUNDATION_EXPORT void ACPreferenceApiStorage_initWithARPreferencesStorage_(ACPreferenceApiStorage *self, id<ARPreferencesStorage> preferencesStorage);

FOUNDATION_EXPORT ACPreferenceApiStorage *new_ACPreferenceApiStorage_initWithARPreferencesStorage_(id<ARPreferencesStorage> preferencesStorage) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACPreferenceApiStorage *create_ACPreferenceApiStorage_initWithARPreferencesStorage_(id<ARPreferencesStorage> preferencesStorage);

J2OBJC_TYPE_LITERAL_HEADER(ACPreferenceApiStorage)

@compatibility_alias ImDiyalogCoreUtilPreferenceApiStorage ACPreferenceApiStorage;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreUtilPreferenceApiStorage")
