//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/entity/content/FastThumb.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreEntityContentFastThumb")
#ifdef RESTRICT_ImDiyalogCoreEntityContentFastThumb
#define INCLUDE_ALL_ImDiyalogCoreEntityContentFastThumb 0
#else
#define INCLUDE_ALL_ImDiyalogCoreEntityContentFastThumb 1
#endif
#undef RESTRICT_ImDiyalogCoreEntityContentFastThumb

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ACFastThumb_) && (INCLUDE_ALL_ImDiyalogCoreEntityContentFastThumb || defined(INCLUDE_ACFastThumb))
#define ACFastThumb_

@class ACLocalFastThumb;
@class ARApiFastThumb;
@class IOSByteArray;

@interface ACFastThumb : NSObject

#pragma mark Public

- (instancetype)initWithARApiFastThumb:(ARApiFastThumb *)fastThumb;

- (instancetype)initWithInt:(jint)w
                    withInt:(jint)h
              withByteArray:(IOSByteArray *)image;

- (instancetype)initWithACLocalFastThumb:(ACLocalFastThumb *)localFastThumb;

- (jint)getH;

- (IOSByteArray *)getImage;

- (jint)getW;

@end

J2OBJC_EMPTY_STATIC_INIT(ACFastThumb)

FOUNDATION_EXPORT void ACFastThumb_initWithACLocalFastThumb_(ACFastThumb *self, ACLocalFastThumb *localFastThumb);

FOUNDATION_EXPORT ACFastThumb *new_ACFastThumb_initWithACLocalFastThumb_(ACLocalFastThumb *localFastThumb) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACFastThumb *create_ACFastThumb_initWithACLocalFastThumb_(ACLocalFastThumb *localFastThumb);

FOUNDATION_EXPORT void ACFastThumb_initWithARApiFastThumb_(ACFastThumb *self, ARApiFastThumb *fastThumb);

FOUNDATION_EXPORT ACFastThumb *new_ACFastThumb_initWithARApiFastThumb_(ARApiFastThumb *fastThumb) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACFastThumb *create_ACFastThumb_initWithARApiFastThumb_(ARApiFastThumb *fastThumb);

FOUNDATION_EXPORT void ACFastThumb_initWithInt_withInt_withByteArray_(ACFastThumb *self, jint w, jint h, IOSByteArray *image);

FOUNDATION_EXPORT ACFastThumb *new_ACFastThumb_initWithInt_withInt_withByteArray_(jint w, jint h, IOSByteArray *image) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACFastThumb *create_ACFastThumb_initWithInt_withInt_withByteArray_(jint w, jint h, IOSByteArray *image);

J2OBJC_TYPE_LITERAL_HEADER(ACFastThumb)

@compatibility_alias ImDiyalogCoreEntityContentFastThumb ACFastThumb;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreEntityContentFastThumb")
