//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/entity/content/ServiceGroupTitleChanged.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreEntityContentServiceGroupTitleChanged")
#ifdef RESTRICT_ImDiyalogCoreEntityContentServiceGroupTitleChanged
#define INCLUDE_ALL_ImDiyalogCoreEntityContentServiceGroupTitleChanged 0
#else
#define INCLUDE_ALL_ImDiyalogCoreEntityContentServiceGroupTitleChanged 1
#endif
#undef RESTRICT_ImDiyalogCoreEntityContentServiceGroupTitleChanged

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ACServiceGroupTitleChanged_) && (INCLUDE_ALL_ImDiyalogCoreEntityContentServiceGroupTitleChanged || defined(INCLUDE_ACServiceGroupTitleChanged))
#define ACServiceGroupTitleChanged_

#define RESTRICT_ImDiyalogCoreEntityContentServiceContent 1
#define INCLUDE_ACServiceContent 1
#include "../../../../../im/diyalog/core/entity/content/ServiceContent.h"

@class ACContentRemoteContainer;

@interface ACServiceGroupTitleChanged : ACServiceContent

#pragma mark Public

- (instancetype)initWithACContentRemoteContainer:(ACContentRemoteContainer *)remoteContainer;

+ (ACServiceGroupTitleChanged *)createWithNSString:(NSString *)title;

- (NSString *)getNewTitle;

@end

J2OBJC_EMPTY_STATIC_INIT(ACServiceGroupTitleChanged)

FOUNDATION_EXPORT ACServiceGroupTitleChanged *ACServiceGroupTitleChanged_createWithNSString_(NSString *title);

FOUNDATION_EXPORT void ACServiceGroupTitleChanged_initWithACContentRemoteContainer_(ACServiceGroupTitleChanged *self, ACContentRemoteContainer *remoteContainer);

FOUNDATION_EXPORT ACServiceGroupTitleChanged *new_ACServiceGroupTitleChanged_initWithACContentRemoteContainer_(ACContentRemoteContainer *remoteContainer) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACServiceGroupTitleChanged *create_ACServiceGroupTitleChanged_initWithACContentRemoteContainer_(ACContentRemoteContainer *remoteContainer);

J2OBJC_TYPE_LITERAL_HEADER(ACServiceGroupTitleChanged)

@compatibility_alias ImDiyalogCoreEntityContentServiceGroupTitleChanged ACServiceGroupTitleChanged;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreEntityContentServiceGroupTitleChanged")
