//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/modules/domainsecurity/DomainSecurity.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreModulesDomainsecurityDomainSecurity")
#ifdef RESTRICT_ImDiyalogCoreModulesDomainsecurityDomainSecurity
#define INCLUDE_ALL_ImDiyalogCoreModulesDomainsecurityDomainSecurity 0
#else
#define INCLUDE_ALL_ImDiyalogCoreModulesDomainsecurityDomainSecurity 1
#endif
#undef RESTRICT_ImDiyalogCoreModulesDomainsecurityDomainSecurity

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ImDiyalogCoreModulesDomainsecurityDomainSecurity_) && (INCLUDE_ALL_ImDiyalogCoreModulesDomainsecurityDomainSecurity || defined(INCLUDE_ImDiyalogCoreModulesDomainsecurityDomainSecurity))
#define ImDiyalogCoreModulesDomainsecurityDomainSecurity_

@interface ImDiyalogCoreModulesDomainsecurityDomainSecurity : NSObject

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ImDiyalogCoreModulesDomainsecurityDomainSecurity)

FOUNDATION_EXPORT void ImDiyalogCoreModulesDomainsecurityDomainSecurity_init(ImDiyalogCoreModulesDomainsecurityDomainSecurity *self);

FOUNDATION_EXPORT ImDiyalogCoreModulesDomainsecurityDomainSecurity *new_ImDiyalogCoreModulesDomainsecurityDomainSecurity_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ImDiyalogCoreModulesDomainsecurityDomainSecurity *create_ImDiyalogCoreModulesDomainsecurityDomainSecurity_init();

J2OBJC_TYPE_LITERAL_HEADER(ImDiyalogCoreModulesDomainsecurityDomainSecurity)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreModulesDomainsecurityDomainSecurity")
