//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/runtime/runtime-shared/src/main/java/im/diyalog/runtime/Assets.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogRuntimeAssets")
#ifdef RESTRICT_ImDiyalogRuntimeAssets
#define INCLUDE_ALL_ImDiyalogRuntimeAssets 0
#else
#define INCLUDE_ALL_ImDiyalogRuntimeAssets 1
#endif
#undef RESTRICT_ImDiyalogRuntimeAssets

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARAssets_) && (INCLUDE_ALL_ImDiyalogRuntimeAssets || defined(INCLUDE_ARAssets))
#define ARAssets_

@class IOSByteArray;

@interface ARAssets : NSObject

#pragma mark Public

- (instancetype)init;

+ (jboolean)hasAssetWithNSString:(NSString *)name;

+ (NSString *)loadAssetWithNSString:(NSString *)name;

+ (IOSByteArray *)loadBinAssetWithNSString:(NSString *)name;

@end

J2OBJC_STATIC_INIT(ARAssets)

FOUNDATION_EXPORT jboolean ARAssets_hasAssetWithNSString_(NSString *name);

FOUNDATION_EXPORT NSString *ARAssets_loadAssetWithNSString_(NSString *name);

FOUNDATION_EXPORT IOSByteArray *ARAssets_loadBinAssetWithNSString_(NSString *name);

FOUNDATION_EXPORT void ARAssets_init(ARAssets *self);

FOUNDATION_EXPORT ARAssets *new_ARAssets_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARAssets *create_ARAssets_init();

J2OBJC_TYPE_LITERAL_HEADER(ARAssets)

@compatibility_alias ImDiyalogRuntimeAssets ARAssets;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogRuntimeAssets")
