//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/runtime/runtime-cocoa/src/main/java/im/diyalog/runtime/HttpRuntimeProvider.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogRuntimeHttpRuntimeProvider")
#ifdef RESTRICT_ImDiyalogRuntimeHttpRuntimeProvider
#define INCLUDE_ALL_ImDiyalogRuntimeHttpRuntimeProvider 0
#else
#define INCLUDE_ALL_ImDiyalogRuntimeHttpRuntimeProvider 1
#endif
#undef RESTRICT_ImDiyalogRuntimeHttpRuntimeProvider

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ARHttpRuntimeProvider_) && (INCLUDE_ALL_ImDiyalogRuntimeHttpRuntimeProvider || defined(INCLUDE_ARHttpRuntimeProvider))
#define ARHttpRuntimeProvider_

#define RESTRICT_ImDiyalogRuntimeCocoaCocoaHttpProxyProvider 1
#define INCLUDE_ARCocoaHttpProxyProvider 1
#include "../../../im/diyalog/runtime/cocoa/CocoaHttpProxyProvider.h"

@interface ARHttpRuntimeProvider : ARCocoaHttpProxyProvider

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ARHttpRuntimeProvider)

FOUNDATION_EXPORT void ARHttpRuntimeProvider_init(ARHttpRuntimeProvider *self);

FOUNDATION_EXPORT ARHttpRuntimeProvider *new_ARHttpRuntimeProvider_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ARHttpRuntimeProvider *create_ARHttpRuntimeProvider_init();

J2OBJC_TYPE_LITERAL_HEADER(ARHttpRuntimeProvider)

@compatibility_alias ImDiyalogRuntimeHttpRuntimeProvider ARHttpRuntimeProvider;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogRuntimeHttpRuntimeProvider")
