//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/viewmodel/ConversationVM.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreViewmodelConversationVM")
#ifdef RESTRICT_ImDiyalogCoreViewmodelConversationVM
#define INCLUDE_ALL_ImDiyalogCoreViewmodelConversationVM 0
#else
#define INCLUDE_ALL_ImDiyalogCoreViewmodelConversationVM 1
#endif
#undef RESTRICT_ImDiyalogCoreViewmodelConversationVM

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ACConversationVM_) && (INCLUDE_ALL_ImDiyalogCoreViewmodelConversationVM || defined(INCLUDE_ACConversationVM))
#define ACConversationVM_

#define RESTRICT_ImDiyalogRuntimeMvvmBaseValueModel 1
#define INCLUDE_ARBaseValueModel 1
#include "../../../../im/diyalog/runtime/mvvm/BaseValueModel.h"

@class ACBooleanValueModel;
@class ACConversationState;
@class ARValueModel;
@protocol ARValueModelCreator;

@interface ACConversationVM : ARBaseValueModel

+ (id<ARValueModelCreator>)CREATOR;

+ (void)setCREATOR:(id<ARValueModelCreator>)value;

#pragma mark Public

- (instancetype)initWithACConversationState:(ACConversationState *)rawObj;

- (ACBooleanValueModel *)getIsLoaded;

- (ARValueModel *)getOwnReadDate;

- (ARValueModel *)getReadDate;

- (ARValueModel *)getReceiveDate;

#pragma mark Protected

- (void)updateValuesWithId:(ACConversationState *)rawObj;

@end

J2OBJC_STATIC_INIT(ACConversationVM)

inline id<ARValueModelCreator> ACConversationVM_get_CREATOR();
inline id<ARValueModelCreator> ACConversationVM_set_CREATOR(id<ARValueModelCreator> value);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT id<ARValueModelCreator> ACConversationVM_CREATOR;
J2OBJC_STATIC_FIELD_OBJ(ACConversationVM, CREATOR, id<ARValueModelCreator>)

FOUNDATION_EXPORT void ACConversationVM_initWithACConversationState_(ACConversationVM *self, ACConversationState *rawObj);

FOUNDATION_EXPORT ACConversationVM *new_ACConversationVM_initWithACConversationState_(ACConversationState *rawObj) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ACConversationVM *create_ACConversationVM_initWithACConversationState_(ACConversationState *rawObj);

J2OBJC_TYPE_LITERAL_HEADER(ACConversationVM)

@compatibility_alias ImDiyalogCoreViewmodelConversationVM ACConversationVM;

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreViewmodelConversationVM")
