//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/viewmodel/FileVMCallback.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreViewmodelFileVMCallback")
#ifdef RESTRICT_ImDiyalogCoreViewmodelFileVMCallback
#define INCLUDE_ALL_ImDiyalogCoreViewmodelFileVMCallback 0
#else
#define INCLUDE_ALL_ImDiyalogCoreViewmodelFileVMCallback 1
#endif
#undef RESTRICT_ImDiyalogCoreViewmodelFileVMCallback

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ACFileVMCallback_) && (INCLUDE_ALL_ImDiyalogCoreViewmodelFileVMCallback || defined(INCLUDE_ACFileVMCallback))
#define ACFileVMCallback_

@protocol ARFileSystemReference;

/*!
 @brief File State View Model callback.
 All methods are called in Main Thread.
 */
@protocol ACFileVMCallback < NSObject, JavaObject >

/*!
 @brief On file not downloaded
 */
- (void)onNotDownloaded;

/*!
 @brief On file started download
 @param progress progress in [0..1]
 */
- (void)onDownloading:(jfloat)progress;

/*!
 @brief On file downloaded
 @param reference FileSystemReference of downloaded file
 */
- (void)onDownloaded:(id<ARFileSystemReference>)reference;

@end

J2OBJC_EMPTY_STATIC_INIT(ACFileVMCallback)

J2OBJC_TYPE_LITERAL_HEADER(ACFileVMCallback)

#define ImDiyalogCoreViewmodelFileVMCallback ACFileVMCallback

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreViewmodelFileVMCallback")
