//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Volumes/DATA/Diyalog/sdk-core/core/core-shared/src/main/java/im/diyalog/core/viewmodel/UploadFileCallback.java
//

@import j2objc;

#pragma push_macro("INCLUDE_ALL_ImDiyalogCoreViewmodelUploadFileCallback")
#ifdef RESTRICT_ImDiyalogCoreViewmodelUploadFileCallback
#define INCLUDE_ALL_ImDiyalogCoreViewmodelUploadFileCallback 0
#else
#define INCLUDE_ALL_ImDiyalogCoreViewmodelUploadFileCallback 1
#endif
#undef RESTRICT_ImDiyalogCoreViewmodelUploadFileCallback

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ACUploadFileCallback_) && (INCLUDE_ALL_ImDiyalogCoreViewmodelUploadFileCallback || defined(INCLUDE_ACUploadFileCallback))
#define ACUploadFileCallback_

/*!
 @brief Upload file callback.
 Methods always called on background thread.
 */
@protocol ACUploadFileCallback < NSObject, JavaObject >

/*!
 @brief On File not uploading
 */
- (void)onNotUploading;

/*!
 @brief On File upload in progress
 @param progress progress value in [0..1]
 */
- (void)onUploading:(jfloat)progress;

/*!
 @brief On file uploaded
 */
- (void)onUploaded;

@end

J2OBJC_EMPTY_STATIC_INIT(ACUploadFileCallback)

J2OBJC_TYPE_LITERAL_HEADER(ACUploadFileCallback)

#define ImDiyalogCoreViewmodelUploadFileCallback ACUploadFileCallback

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ImDiyalogCoreViewmodelUploadFileCallback")
